import {FocusTimer} from './LifeTools';
import {TaskIcon} from './TaskIcon';
import {FocusAgeTools} from './FocusAgeTools';
import {ageExamples,SupportHint} from './AgePlanning';
import type {Band} from './engine';
import React,{useState} from 'react';
import {createTask,localDate,dependencyBlocked,type Workspace,type PlannerTask,type Mode} from './workspace';
import {emptyPractice} from './CognitiveActivity';
import {focusRoutePrompt,focusRouteReady} from './focusRoutes';
type Props={band:Band;lower?:boolean;data:Workspace;commit:(w:Workspace)=>void;open:(id:string)=>void;mode:Mode;complete:(t:PlannerTask,actual:number,help:'none'|'some',note:string)=>void};
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return localDate(d);}
function examples(){return [['발표 자료 찾기','수업 자료 펼치기',15],['발표 내용 정리','핵심 세 가지 적기',20],['발표 연습','첫 문장 소리 내어 말하기',10]].map(([title,first,n])=>({...createTask(String(title),String(first)),minutes:Number(n)}));}
export function PlanningDesk({data,commit,open,mode,lower}:Props){
 const [title,setTitle]=useState('');
 const today=localDate(),tasks=data.tasks.filter(t=>t.status!=='done'&&t.date===today),total=tasks.reduce((n,t)=>n+t.minutes,0);
 function move(id:string,d:number){const at=data.tasks.findIndex(t=>t.id===id),i=tasks.findIndex(t=>t.id===id),other=data.tasks.findIndex(t=>t.id===tasks[i+d]?.id);if(other<0)return;const list=[...data.tasks];[list[at],list[other]]=[list[other],list[at]];commit({...data,tasks:list});}
 return <section className="np-card np-planning-desk" data-testid="planning-desk"><span className="np-eyebrow">{mode==='demo'?'A · ':''}하루 계획 조립</span><h2>오늘 할 일을 순서와 시간에 맞춰 놓아요</h2><SupportHint data={data}><p>{lower?'그림 카드를 골라요. 먼저 할 일을 위로 옮기고, 준비물을 챙긴 뒤 시작해요.':'오늘 할 일의 순서를 정하고, 한 번에 할 분량을 나눠요.'}</p></SupportHint><div className="age-materials">{['숙제하기','준비물 챙기기','운동하기'].map((x,i)=><button key={x} disabled={data.tasks.length>=500} onClick={()=>commit({...data,tasks:[...data.tasks,createTask(x,'필요한 것 꺼내기')]})}><TaskIcon kind={i}/>{x} +</button>)}</div>
 {!lower&&<div className="np-budget"><label>오늘 쓸 수 있는 시간<input aria-label="오늘 사용 가능 시간" type="number" min={1} max={1440} value={data.dailyCapacity} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=1440)commit({...data,dailyCapacity:n});}}/>분</label><div><b>{total} / {data.dailyCapacity}분</b><progress max={data.dailyCapacity} value={Math.min(total,data.dailyCapacity)}/><small>{total>data.dailyCapacity?`${total-data.dailyCapacity}분 초과 · 카드 하나를 내일로 옮기거나 분량을 나눠보세요.`:`${data.dailyCapacity-total}분 여유가 있어요.`}</small></div></div>}
 <form className="np-add-row" onSubmit={e=>{e.preventDefault();if(title.trim()&&data.tasks.length<500){commit({...data,tasks:[...data.tasks,createTask(title,'시작할 행동을 구체적으로 적기')]});setTitle('');}}}><input aria-label="계획에 넣을 할 일" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="오늘 할 일을 한 장씩 추가해요"/><button disabled={!title.trim()||data.tasks.length>=500}>카드 추가</button></form>
 <div className="np-plan-lanes">{tasks.length?tasks.map((t,i)=><article key={t.id} data-testid="plan-card"><span className="np-order-badge">{i+1}</span><div className="np-plan-card-main"><input aria-label={`${i+1}번째 할 일 이름`} maxLength={160} value={t.title} onChange={e=>{if(e.target.value.trim())commit({...data,tasks:data.tasks.map(x=>x.id===t.id?{...x,title:e.target.value}:x)});}}/>{!lower&&<label>배정 시간<input aria-label={`${t.title} 배정 시간`} type="number" min={1} max={1440} value={t.minutes} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=1440)commit({...data,tasks:data.tasks.map(x=>x.id===t.id?{...x,minutes:n}:x)});}}/>분</label>}<button onClick={()=>open(t.id)}>이 일 나누고 시작하기 →</button></div><div className="np-plan-card-controls"><button aria-label={`${t.title} 앞으로`} disabled={i===0} onClick={()=>move(t.id,-1)}>↑</button><button aria-label={`${t.title} 뒤로`} disabled={i===tasks.length-1} onClick={()=>move(t.id,1)}>↓</button><button onClick={()=>commit({...data,tasks:data.tasks.map(x=>x.id===t.id?{...x,date:tomorrow()}:x)})}>내일로</button></div></article>):['맨 먼저 할 일','그다음 할 일','마지막에 할 일'].map((label,i)=><div className="np-empty-slot" key={label}><b>{i+1}</b>{label}</div>)}</div>
 {mode==='demo'&&!data.tasks.length&&<button className="np-primary" onClick={()=>commit({...data,tasks:ageExamples('A'),dailyCapacity:40})}>초등 생활 예시로 체험하기</button>}
 <details className="np-details"><summary>다른 날짜·완료한 할 일</summary>{data.tasks.filter(t=>t.date!==today||t.status==='done').map(t=><div className="np-backlog-row" key={t.id}><button onClick={()=>open(t.id)}>{t.date||'날짜 미정'} · {t.title}{t.status==='done'?' ✓':''}</button>{t.status!=='done'&&<button onClick={()=>commit({...data,tasks:data.tasks.map(x=>x.id===t.id?{...x,date:today}:x)})}>오늘로 가져오기</button>}</div>)}</details>
 </section>;
}
export function FocusDesk({data,commit,open,mode,complete,band,lower}:Props){
 const [selected,setSelected]=useState(''),[title,setTitle]=useState(''),[first,setFirst]=useState(''),[actual,setActual]=useState(''),[help,setHelp]=useState<'none'|'some'>('none');
 const todo=data.tasks.filter(t=>t.status!=='done');
 const t=todo.find(t=>t.status==='active')||todo.find(t=>t.id===selected)||todo.find(t=>t.status==='paused'&&!dependencyBlocked(t,data.tasks)&&!t.waiting)||todo.find(t=>!dependencyBlocked(t,data.tasks)&&!t.waiting)||todo[0];
 const s=t?.steps.find(s=>!s.done),active=t?.status==='active',paused=t?.status==='paused',blocked=t?dependencyBlocked(t,data.tasks)||t.waiting:false;
 const practice={...emptyPractice,...t?.practice};
 function patch(changes:Partial<PlannerTask>){if(t)commit({...data,tasks:data.tasks.map(x=>x.id===t.id?{...x,...changes}:x)});}
 function patchTask(id:string,changes:Partial<PlannerTask>){commit({...data,tasks:data.tasks.map(x=>x.id===id?{...x,...changes}:x)});}
 const routeReady=!!t&&focusRouteReady(t,band,!!lower,!!paused);
 const pauseReady=!!t&&(band!=='B'||(Boolean(t.remainingScope?.trim())&&Boolean(t.nextTenAction?.trim())));
 function start(){if(!t||blocked||!routeReady)return;commit({...data,tasks:data.tasks.map(x=>x.id===t.id?{...x,status:'active',startedAt:x.startedAt||new Date().toISOString(),practice:{...practice,returns:practice.returns+(paused?1:0)}}:x.status==='active'?{...x,status:'paused'}:x)});}
 const routeTitle=band==='A'?(lower?'그림 루틴으로 준비하고 시작해요':'숙제 단계 카드에서 지금 한 장을 골라요'):band==='B'?'과목과 오늘 범위를 정해, 다음 10분으로 돌아와요':band==='C'?'마감별로 계속할 일·나눌 일·미룰 일을 판단해요':'업무의 다음 행동·답변 대기·확인 요청을 구분해요';
 return <section className="np-card np-focus-desk" data-testid="focus-desk"><span className="np-eyebrow">{mode==='demo'?'B · ':''}연령별 실행 루틴</span><h2>{routeTitle}</h2><SupportHint data={data}><p>{band==='A'?(lower?'그림/짧은 말로 준비 → 시작 → 확인을 해봐요.':'숙제 단계를 카드로 보고 지금 할 한 장과 복귀 위치를 정해요.'):band==='B'?'과목·범위·오늘 분량을 정하고, 중단 때는 남은 범위와 다음 10분 행동을 남겨요.':band==='C'?'여러 마감의 학습 과제를 비교해 지금 계속·작게 나누기·다른 날로 옮기기를 직접 결정해요.':'즉시 할 일, 답변 대기, 다른 사람에게 확인할 일을 구분하고 인계 메모를 남겨요.'}</p></SupportHint>
 {!t?<>{lower&&<div className="age-materials">{['숙제하기','준비물 챙기기','운동하기'].map((x,i)=><button key={x} disabled={data.tasks.length>=500} onClick={()=>commit({...data,tasks:[...data.tasks,createTask(x,'필요한 것 꺼내기')]})}><TaskIcon kind={i}/>{x}</button>)}</div>}<div className="np-focus-empty"><span>◎</span><h3>여기에 지금 할 일 하나를 놓아요</h3><p>시간표를 채우기 전에, 첫 행동부터 시작해요.</p></div><form onSubmit={e=>{e.preventDefault();if(title.trim()&&first.trim()&&data.tasks.length<500){const task=createTask(title,first);commit({...data,tasks:[...data.tasks,task]});setSelected(task.id);setTitle('');setFirst('');}}}><label>지금 끝낼 일<input aria-label="집중할 할 일" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>시작할 행동 하나<input aria-label="집중 첫 행동" maxLength={160} value={first} onChange={e=>setFirst(e.target.value)}/></label><button className="np-primary" disabled={!title.trim()||!first.trim()}>이 일에 집중하기 →</button></form>{mode==='demo'&&!data.tasks.length&&<button className="np-text-button" onClick={()=>commit({...data,tasks:ageExamples(band)})}>학년별 실행 예시로 체험하기</button>}</>:<>
 <FocusAgeTools key={t.id} band={band} lower={!!lower} t={t} tasks={todo} patch={patch} patchTask={patchTask} choose={id=>{setSelected(id);setActual('');}} active={!!active}/>{band!=='A'||!lower?<FocusTimer key={t.id} active={!!active} minutes={t.minutes}/>:null}<div className="np-focus-stage"><span>{paused?'다시 돌아올 자리':active?'지금 실행 중':'이번에 집중할 일'}</span><h3>{t.title}</h3><div className="np-focus-action"><small>지금 할 행동</small><b>{s?.title||'빠진 준비물 확인'}</b></div>{paused&&<label>이어갈 위치<input aria-label="이어갈 위치" maxLength={500} value={t.resumeNote} onChange={e=>patch({resumeNote:e.target.value})}/></label>}
 {!active?<><label>보조 도구 · 시작 전 방해 줄이기 <span className="np-optional">선택</span><select aria-label="집중 준비 행동" value={practice.focusAction} onChange={e=>patch({practice:{...practice,focusAction:e.target.value}})}><option value="">사용하지 않음</option><option value="notifications">알림 끄기</option><option value="materials">필요한 자료만 남기기</option><option value="park">다른 할 일은 메모에 맡기기</option></select></label>{!routeReady&&<p className="np-activity-prompt">{focusRoutePrompt(t,band,!!lower,!!paused)}</p>}<button className="np-primary" data-testid="focus-start" disabled={blocked||!routeReady} onClick={start}>{paused?'남긴 자리에서 다시 시작 →':'연령별 준비를 마치고 시작 ▶'}</button></>:<div className="np-actions"><button data-testid="focus-pause" disabled={!pauseReady} onClick={()=>patch({status:'paused',resumeNote:band==='B'?`남은 범위: ${t.remainingScope} / 다음 10분: ${t.nextTenAction}`:s?.title||'마무리 확인'})}>{band==='B'?'복귀 계획을 남기고 멈추기':'잠깐 멈추기 Ⅱ'}</button>{s&&<button className="np-primary" data-testid="focus-step-done" disabled={blocked} onClick={()=>patch({steps:t.steps.map(x=>x.id===s.id?{...x,done:true}:x)})}>이 행동을 끝냈어요 ✓</button>}</div>}
 {blocked&&<p>선행 작업 또는 외부 답변을 기다리는 일이에요. 아래 세부 내용을 확인해 주세요.</p>}</div>
 {active&&<div className="np-parking"><h3>다른 일이 생각나면 여기에 맡겨요</h3><input aria-label="다른 일 보관 메모" maxLength={500} value={practice.parked} onChange={e=>patch({practice:{...practice,parked:e.target.value}})} placeholder="지금 하지 않아도 되는 일"/><button data-testid="focus-park" disabled={!practice.parked.trim()} onClick={()=>patch({status:'paused',resumeNote:s?.title||'마무리 확인'})}>보관하고 원래 행동 확인하기 ↪</button></div>}
 {!active&&practice.parked&&<p className="np-resume">나중에 할 일: {practice.parked}</p>}
 {active&&!s&&<div className="np-finish"><h3>마무리 확인</h3>{t.materials.map(m=><label className="np-check" key={m.id}><input type="checkbox" checked={m.done} onChange={e=>patch({materials:t.materials.map(x=>x.id===m.id?{...x,done:e.target.checked}:x)})}/>{m.title}</label>)}<label>실제로 쓴 시간(분)<input aria-label="집중 실제 시간" type="number" min={0} max={1440} value={actual} onChange={e=>setActual(e.target.value)}/></label><label>도움 여부<select value={help} onChange={e=>setHelp(e.target.value as 'none'|'some')}><option value="none">스스로 했어요</option><option value="some">도움을 받았어요</option></select></label><button className="np-primary" data-testid="focus-complete" disabled={blocked||!actual.trim()||Number(actual)<0||Number(actual)>1440||!t.materials.every(m=>m.done)||(band==='D'&&!t.adjustment.trim())} onClick={()=>{complete(t,Number(actual),help,t.adjustment);setActual('');setSelected('');}}>이 일 완료하기 ✓</button></div>}
 <small>복귀 버튼 실행 {practice.returns}회 · 실제 집중력 점수는 아니에요.</small>
 <details className="np-details"><summary>나중에 할 일 추가</summary><form onSubmit={e=>{e.preventDefault();if(title.trim()&&first.trim()&&data.tasks.length<500){commit({...data,tasks:[...data.tasks,createTask(title,first)]});setTitle('');setFirst('');}}}><label>새 할 일<input aria-label="대기 할 일 이름" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>첫 행동<input aria-label="대기 할 일 첫 행동" maxLength={160} value={first} onChange={e=>setFirst(e.target.value)}/></label><button disabled={!title.trim()||!first.trim()||data.tasks.length>=500}>대기 목록에 넣기</button></form></details>
 <details className="np-details"><summary>이 일의 제목·단계·준비물 편집</summary><button onClick={()=>open(t.id)}>세부 편집 열기</button></details>
 <details className="np-details"><summary>대기 중인 다른 일 {Math.max(0,todo.length-1)}개 · 필요할 때만 열기</summary>{todo.filter(x=>x.id!==t.id).map(x=><button className="np-text-button" key={x.id} disabled={!!active} onClick={()=>{setSelected(x.id);setActual('');}}>{x.title}</button>)}{active&&<small>다른 일을 열려면 먼저 현재 일을 잠깐 멈춰 주세요.</small>}</details>
 </>}
 </section>;
}
