import {BridgePath,FollowupTask} from './TransferBridge';
import TimeBlockBoard,{SubjectMark} from './TimeBlockBoard';
import {mergeLegacyWorkspace} from './timeBlocks';
import {nextRepeat,weeklyRecordDays} from './LifeTools';
import {AgePlanning} from './AgePlanning';
import {PlanningDesk,FocusDesk} from './ActivityDesks';
import {CognitiveActivity,emptyPractice,practiceReady} from './CognitiveActivity';
import React,{useState,useEffect,useRef,useCallback} from 'react';
import {AXES,AXIS_LABEL,LEVEL_LABEL,BAND_LABEL,DEMOS,STAGE_BAND,validateAssessment,resolveTraining,profileKey,validateVerification,type Assessment,type Assignment,type Band,type TrainingRecord} from './engine';
import {blankWorkspace,scopeFor,storageKey,validateWorkspace,verifyBackupRoundTrip,exportWorkspaceJson,restoreWorkspaceJson,createTask,uid,localDate,weekDates,canDependOn,dependencyBlocked,type Mode,type Workspace,type PlannerTask} from './workspace';
import {feelgoodLogo} from './brandAssets';
import {CapacityShelf,DomainMark,TimeAdjustmentPrompt,timeAdjustmentLabel,timeDifferenceText} from './PlannerEnhancements';
import './personal-planner.css';
import './planner-2-5.css';
type Result={ok:boolean;error?:string};
type WorkspaceAPI={getWorkspace:()=>Workspace|null;setWorkspace:(raw:unknown)=>Result;getRecords:()=>TrainingRecord[];setVerification:(raw:unknown)=>Result;};
declare global {interface Window {NUVIA_PLANNER_MODE?:Mode;NUVIA_PLANNER_ASSESSMENT?:unknown;NUVIAPlanner?:WorkspaceAPI&{setAssessment:(raw:unknown)=>Result;clearAssessment:()=>void;};}}
const emptyAPI:WorkspaceAPI={getWorkspace:()=>null,setWorkspace:()=>({ok:false,error:'검사 결과를 먼저 연결해 주세요.'}),getRecords:()=>[],setVerification:()=>({ok:false,error:'연결된 기록이 없어요.'})};
const STAGES:Record<Band,Assessment['educationStage']>={A:'elementary_4_6',B:'middle',C:'high',D:'adult'};
const descriptions:Record<Band,string>={A:'숙제와 준비물, 오늘 할 일을 직접 정해요.',B:'과목별 할 일과 마감을 이번 주에 나눠요.',C:'큰 목표를 날짜별 단계로 나누고, 가능한 시간에 맞춰요.',D:'프로젝트의 담당과 선행 작업을 정하고, 기다리는 일도 관리해요.'};
const supports:Record<Assignment['support'],string>={simultaneous:'전체 흐름으로 계획하기',successive:'한 단계씩 이어가기',planning:'목표와 완료 기준 확인하기',attention:'지금 필요한 단서 확인하기',universal:'첫 행동부터 작게 시작하기'};
function boot(){let assessment:Assessment|null=null,error='';try{if(window.NUVIA_PLANNER_ASSESSMENT!==undefined)assessment=validateAssessment(window.NUVIA_PLANNER_ASSESSMENT);}catch(e){error=(e as Error).message;}return {assessment,error,mode:window.NUVIA_PLANNER_MODE==='production'||window.NUVIA_PLANNER_ASSESSMENT!==undefined||new URLSearchParams(location.search).get('mode')==='production'?'production' as const:'demo' as const};}
export default function AdaptivePlanner(){
 const [view]=useState(()=>{try{const v=JSON.parse(sessionStorage.getItem('nuvia:demo-view')||'{}');return {demo:v.demo===1?1:0,lower:v.lower===true,band:(['A','B','C','D'].includes(v.band)?v.band:'A') as Band};}catch{return {demo:0,lower:false,band:'A' as Band};}});
 const [initial]=useState(boot),[mode,setMode]=useState<Mode>(initial.mode),[official,setOfficial]=useState(initial.assessment),[error,setError]=useState(initial.error),[demo,setDemo]=useState(view.demo),[lower,setLower]=useState(view.lower),[band,setBand]=useState<Band>(view.band),[generation,setGeneration]=useState(0);
 useEffect(()=>{if(mode==='demo')try{sessionStorage.setItem('nuvia:demo-view',JSON.stringify({demo,lower,band}));}catch{/* Workspace saving independently reports persistence errors. */}},[mode,demo,lower,band]);
 const workspaceAPI=useRef<WorkspaceAPI>(emptyAPI);
 const bind=useCallback((api:WorkspaceAPI)=>{workspaceAPI.current=api;},[]);
 useEffect(()=>{const api={setAssessment:(raw:unknown)=>{workspaceAPI.current=emptyAPI;setGeneration(n=>n+1);setMode('production');try{const a=validateAssessment(raw);setOfficial(a);setError('');return {ok:true};}catch(e){setOfficial(null);setError((e as Error).message);return {ok:false,error:(e as Error).message};}},clearAssessment:()=>{workspaceAPI.current=emptyAPI;window.NUVIA_PLANNER_ASSESSMENT=undefined;setMode('production');setOfficial(null);setError('');},getWorkspace:()=>workspaceAPI.current.getWorkspace(),setWorkspace:(raw:unknown)=>workspaceAPI.current.setWorkspace(raw),getRecords:()=>workspaceAPI.current.getRecords(),setVerification:(raw:unknown)=>workspaceAPI.current.setVerification(raw)};window.NUVIAPlanner=api;window.dispatchEvent(new CustomEvent('nuvia:planner-ready',{detail:{schemaVersion:'1.0',workspaceVersion:'2.0'}}));return()=>{if(window.NUVIAPlanner===api)delete window.NUVIAPlanner;};},[]);
 const assessment=mode==='demo'?{...DEMOS[demo],educationStage:band==='A'&&lower?'elementary_1_3' as const:STAGES[band],transfer:DEMOS[demo].transfer}:official;
 const actualBand=assessment?STAGE_BAND[assessment.educationStage]:'A';
 const assignment=assessment?resolveTraining(assessment):null;
 return <div className="np-shell"><header className="np-header"><div className="np-brand"><img src={feelgoodLogo} alt="FeelGood 필굿"/><h1>NUVIA <span>PLANNER</span></h1></div><span className="np-badge">{mode==='demo'?'DEMO 2.5':'결과지 연동 2.5'}</span></header>
  <div className="np-intro"><p className="np-eyebrow">MY DAY, ONE STEP AT A TIME</p><h2>내가 정한 하루,<br className="np-mobile"/> 나의 강점으로 완성.</h2><p>할 일을 적고, 하나씩 해보고, 다음 계획을 조정해요.</p></div>
  {mode==='demo'&&<section className="np-demo" aria-label="데모 설정"><div className="np-demo-tabs" role="group" aria-label="임시 인지 프로필">{[0,1].map(i=><button key={i} data-testid={`profile-${i}`} aria-pressed={demo===i} onClick={()=>{if(i!==demo){workspaceAPI.current=emptyAPI;setDemo(i);}}}><b>프로필 {i===0?'A':'B'}</b><span>{i===0?'여러 일의 순서·시간 조립':'한 가지 일 실행·중단·복귀'}</span><small>{i===0?'동시처리 강점 · 계획 지원':'순차처리 강점 · 주의 지원'}</small></button>)}</div><div className="np-stage"><strong>활동 단계</strong><div>{(['A','B','C','D'] as Band[]).map(b=><button key={b} aria-pressed={actualBand===b} data-testid={`band-${b}`} onClick={()=>{if(b!==band){workspaceAPI.current=emptyAPI;setBand(b);}}}>{BAND_LABEL[b]}</button>)}</div>{band==='A'&&<div className="age-substage">{[true,false].map(v=><button key={String(v)} data-testid={v?'elementary-lower':'elementary-upper'} aria-pressed={lower===v} onClick={()=>setLower(v)}>{v?'초1~3 · 그림 선택':'초4~6 · 직접 계획'}</button>)}</div>}<small>임시 검사 프로필입니다. 각 프로필·학년의 할 일은 따로 보관해요.</small></div></section>}
  {assessment&&assignment?<><details className="np-profile"><summary>{supports[assignment.support]} <span>· {BAND_LABEL[actualBand]} <i>인지 지원 보기</i></span></summary><div className="np-axes">{AXES.map(axis=><div key={axis} className={assessment.axes[axis].level}><span>{AXIS_LABEL[axis]}</span><b>{LEVEL_LABEL[assessment.axes[axis].level]}</b>{assessment.axes[axis].value!==undefined&&<small>{assessment.axes[axis].value} {assessment.axes[axis].unit}</small>}</div>)}</div><p>{assignment.reason} {assignment.remainingTargets.length>0&&`추가 지원 대상: ${assignment.remainingTargets.map(a=>AXIS_LABEL[a]).join(', ')}.`}</p><small>검사 분류는 초기 도움의 기준이에요. 도움은 필요할 때 다시 열 수 있어요.</small></details>
  <PersonalPlanner key={scopeFor(mode,assessment,actualBand)+':'+generation} mode={mode} assessment={assessment} band={actualBand} assignment={assignment} bind={bind}/></>:<section className="np-card np-empty"><div className="np-empty-icon">↗</div><h2>검사 결과를 기다리고 있어요</h2><p role="status">{error||'결과지에서 인지 프로필과 학습 단계가 전달되면 내 플래너가 열립니다.'}</p><small>필굿 서비스에서 검사 결과를 연결해 주세요.</small></section>}
  <footer>FeelGood · NUVIA PLANNER<br/>검사 결과는 지원의 출발점입니다. 완료 기록만으로 인지능력 향상을 판정하지 않아요.</footer>
 </div>;
}
function PersonalPlanner({mode,assessment,band,assignment,bind}:{mode:Mode;assessment:Assessment;band:Band;assignment:Assignment;bind:(api:WorkspaceAPI)=>void}){
 const scope=scopeFor(mode,assessment,band);
 const [initial]=useState(()=>{try{const raw=localStorage.getItem(storageKey(scope));return {data:raw?validateWorkspace(JSON.parse(raw),scope):blankWorkspace(scope),error:''};}catch{return {data:blankWorkspace(scope),error:'저장된 자료를 읽지 못했어요. 이 화면의 새 입력은 기존 자료를 덮어쓸 수 있어요. 필요한 백업 파일을 먼저 가져와 주세요.'};}});
 const [data,setData]=useState(initial.data),[storageError,setStorageError]=useState(initial.error),[notice,setNotice]=useState(''),[tab,setTab]=useState<'today'|'week'|'growth'>('today'),[selected,setSelected]=useState<string>(''),[title,setTitle]=useState(''),[first,setFirst]=useState(''),[showDone,setShowDone]=useState(false),[followup,setFollowup]=useState(false);
 const ref=useRef(data);ref.current=data;
 useEffect(()=>{if(selected&&tab==='today')document.querySelector('[data-testid="task-editor"]')?.scrollIntoView({block:'start'});},[selected,tab]);
 function commit(next:Workspace){if(next.tasks.length>500){setNotice('할 일은 최대 500개예요. 기존 항목을 정리한 뒤 추가해 주세요.');return;}if(next.tasks.filter(t=>t.status==='active').length>1&&next.tasks.some(t=>t.timeBlock)){setNotice('현재 블록을 먼저 중단하거나 종료해 주세요.');return;}ref.current=next;setData(next);try{localStorage.setItem(storageKey(scope),JSON.stringify(next));setStorageError('');}catch{setStorageError('이 브라우저에 저장하지 못했어요. 화면을 닫기 전에 백업 내려받기를 해 주세요.');}window.dispatchEvent(new CustomEvent('nuvia:planner-workspace-changed',{detail:{schemaVersion:'2.0',mode,assessmentId:assessment.assessmentId,subjectId:assessment.subjectId,taskCount:next.tasks.length}}));}
 const commitRef=useRef(commit);commitRef.current=commit;
 useEffect(()=>{bind({getWorkspace:()=>structuredClone(ref.current),getRecords:()=>structuredClone(ref.current.records),setWorkspace:(raw:unknown)=>{try{const next=validateWorkspace(raw,scope);commitRef.current(next);return {ok:true};}catch(e){return {ok:false,error:(e as Error).message};}},setVerification:(raw:unknown)=>{try{const v=validateVerification(raw,ref.current.records);commitRef.current({...ref.current,records:ref.current.records.map(r=>r.id===v.recordId?{...r,verification:v}:r)});return {ok:true};}catch(e){return {ok:false,error:(e as Error).message};}}});return()=>bind(emptyAPI);},[bind,scope]);
 function patch(id:string,changes:Partial<PlannerTask>){commit({...ref.current,tasks:ref.current.tasks.map(t=>t.id===id?{...t,...changes}:t)});}
 function add(){if(!title.trim()||!first.trim())return;if(data.tasks.length>=500){setNotice('할 일은 최대 500개예요. 필요 없는 항목을 정리해 주세요.');return;}const task=createTask(title,first);commit({...ref.current,tasks:[...ref.current.tasks,task]});setSelected(task.id);setTitle('');setFirst('');setNotice('내 할 일을 추가했어요. 제목·단계·준비물은 언제든 고칠 수 있어요.');}
 function remove(id:string){commit({...ref.current,tasks:ref.current.tasks.filter(t=>t.id!==id).map(t=>t.dependsOn===id?{...t,dependsOn:''}:t)});if(selected===id)setSelected('');setNotice('할 일을 삭제했어요. 이 일에 연결된 선행 관계도 해제했어요.');}
 function recordCompletion(t:PlannerTask,actual:number,help:'none'|'some',adjustment:string){
  if(ref.current.tasks.find(x=>x.id===t.id)?.status==='done')return;
  const next=nextRepeat(t);
  const addRepeat=next&&!ref.current.tasks.some(x=>x.repeatOf===t.id)&&ref.current.tasks.length<500;
  const r:TrainingRecord={id:uid(),createdAt:new Date().toISOString(),kind:'real_task',source:'self_report',context:{mode,assessmentId:assessment.assessmentId,subjectId:assessment.subjectId,profileVersion:assessment.profileVersion,profileKey:profileKey(assessment),band,route:assignment.route,target:assignment.target,support:assignment.support,rulesVersion:'planner-2.0',axes:structuredClone(assessment.axes),transfer:assessment.transfer??null,strategyId:assessment.transfer?.strategyId??'PLAN_DO_CHECK'},measures:{taskId:t.id,taskDomain:t.domain||'미지정',strategyApplied:!!assessment.transfer&&t.transferUsed===true,predictedMinutes:t.minutes,actualMinutes:actual,...(t.timeBlock?{}:{helpReceived:help==='some'}),stepCount:t.steps.length,materialCount:t.materials.length,completed:'yes',adjustmentRecorded:!!adjustment.trim(),contentStoredLocally:true,processEvidenceSource:'self_report',practiceType:assignment.target==='attention'||assignment.support==='successive'?'attention_return':'planning_priority',priorityReason:t.practice?.reason??'',focusAction:t.practice?.focusAction??'',returnActions:t.practice?.returns??0,ageActivityRoute:t.focusRoute??'',routeConfirmed:t.routeConfirmed===true,deadlineDecision:t.deadlineDecision??'',handoffState:t.handoffState??'',resumePlanCaptured:!!t.resumeNote.trim()}};
  commit({...ref.current,tasks:[...ref.current.tasks.map(x=>x.id===t.id?{...x,status:'done' as const,completedAt:r.createdAt,actualMinutes:actual,help,adjustment}:x),...(addRepeat?[next!]:[])],records:[...ref.current.records,r].slice(-5000)});
  window.dispatchEvent(new CustomEvent('nuvia:planner-record',{detail:structuredClone(r)}));setNotice(addRepeat?'완료를 기록하고 다음 반복 할 일을 만들었어요.':next&&ref.current.tasks.length>=500?'완료를 기록했어요. 할 일이 500개라 다음 반복은 추가하지 못했어요.':'완료와 돌아보기를 기록했어요.');
 }
 function backup(){try{verifyBackupRoundTrip(ref.current,scope);const blob=new Blob([exportWorkspaceJson(ref.current,true)],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`NUVIA_PLANNER_backup_${mode}_${band}_${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('백업 파일에 할 일·준비물·메모가 함께 들어 있어요. 같은 검증 경로의 JSON 왕복도 통과했어요.');}catch(e){setNotice(`백업 검증 실패: ${(e as Error).message}`);}}
 async function restore(file?:File){if(!file)return;try{if(file.size>50_000_000)throw new Error('50MB 이하의 백업 파일을 선택해 주세요.');const next=restoreWorkspaceJson(await file.text(),scope);commit(next);setSelected('');setNotice('백업을 가져왔어요. 현재 프로필의 자료를 교체했어요.');}catch(e){setNotice((e as Error).message);}}
 function loadDemoHistory(){if(mode!=='demo'||!assessment.transfer||ref.current.demoExampleLoaded){setNotice('이 데모 예시 기록은 이미 불러왔어요.');return;}const now=new Date().toISOString(),task={...createTask('예시 전략 사용 · 자료 정리','자료를 세 묶음으로 나누기'),focusRoute:'step_card' as const,transferUsed:true,domain:'학습' as const,status:'done' as const,completedAt:now,actualMinutes:15,help:'none' as const,adjustment:'데모용 예시 기록',materials:[{id:uid(),title:'자료 카드',done:true}],steps:[{id:uid(),title:'자료를 세 묶음으로 나누기',done:true,date:''}]};const record:TrainingRecord={id:uid(),createdAt:now,kind:'real_task',source:'self_report',context:{mode,assessmentId:assessment.assessmentId,subjectId:assessment.subjectId,profileVersion:assessment.profileVersion,profileKey:profileKey(assessment),band,route:assignment.route,target:assignment.target,support:assignment.support,rulesVersion:'planner-2.0',axes:structuredClone(assessment.axes),transfer:assessment.transfer,strategyId:assessment.transfer.strategyId},measures:{taskId:task.id,taskDomain:'학습',strategyApplied:true,predictedMinutes:task.minutes,actualMinutes:15,helpReceived:false,stepCount:1,materialCount:1,completed:'yes',adjustmentRecorded:true,contentStoredLocally:true,processEvidenceSource:'self_report',practiceType:'demo_example',priorityReason:'',focusAction:'',returnActions:0,demoExample:true}};commit({...ref.current,demoExampleLoaded:true,tasks:[...ref.current.tasks,task],records:[...ref.current.records,record]});setNotice('데모용 예시 전략 이력을 불러왔어요. 실제 KIDS/HISTORY 이력이 아닙니다.');}
 const linkedPrevious=[...data.records].reverse().find(r=>r.kind==='real_task'&&r.measures.strategyApplied===true&&assessment.transfer&&r.context.transfer?.bridgeId===assessment.transfer.bridgeId&&r.context.strategyId===assessment.transfer.strategyId);
 const previousTask=data.tasks.find(t=>t.id===linkedPrevious?.measures.taskId);
 function saveFollowup(measures:TrainingRecord['measures']){if(!linkedPrevious||!assessment.transfer)return;const r:TrainingRecord={id:uid(),createdAt:new Date().toISOString(),kind:'followup_task',source:'self_report',context:structuredClone(linkedPrevious.context),measures:{...measures,previousRecordId:linkedPrevious.id}};commit({...ref.current,records:[...ref.current.records,r].slice(-5000)});window.dispatchEvent(new CustomEvent('nuvia:planner-record',{detail:structuredClone(r)}));setFollowup(false);setNotice('다른 영역의 적용 자기보고를 남겼어요. 작성 원문은 저장하지 않았어요.');}
 const done=data.tasks.filter(t=>t.status==='done');
 function commitLegacy(next:Workspace){commit(mergeLegacyWorkspace(ref.current,next));}
 const task=data.tasks.find(t=>t.id===selected);
 const visible=data.tasks.filter(t=>showDone||t.status!=='done');
 const week=weekDates(),today=localDate();
 const weekRecord=weeklyRecordDays(data.tasks,week),pendingAdjustment=[...done].reverse().find(t=>!t.timeAdjustment);
 useEffect(()=>{if(mode!=='demo')return;const listener=()=>loadDemoHistory();window.addEventListener('nuvia:load-demo-history',listener);return()=>window.removeEventListener('nuvia:load-demo-history',listener);},[mode,data.demoExampleLoaded]);
 return <>
  <nav className="np-nav" aria-label="플래너 메뉴">{(['today','week','growth'] as const).map((x,i)=><button key={x} aria-current={tab===x?'page':undefined} onClick={()=>{setTab(x);if(x==='growth')commit({...ref.current,lastWeeklyReviewWeek:weekDates()[0]});}} data-testid={`tab-${x}`}>{[(assignment.target==='attention'||assignment.support==='successive')?'지금 · 한 가지 실행':'오늘 · 계획 조립','이번 주 · 일정','성장 · 돌아보기'][i]}</button>)}</nav>
  {storageError&&<p className="np-alert" role="alert">{storageError}</p>}{notice&&<div className="np-notice" role="status">{notice}<button aria-label="알림 닫기" onClick={()=>setNotice('')}>×</button></div>}
  <div className="np-layout"><main>{data.lastWeeklyReviewWeek!==week[0]&&<div className="np-review-banner">이번 주, 계획에서 바꿀 한 가지를 살펴볼까요? <button onClick={()=>{commit({...ref.current,lastWeeklyReviewWeek:week[0]});setTab('growth');}}>주간 돌아보기</button><button aria-label="이번 주 리뷰 안내 닫기" onClick={()=>commit({...ref.current,lastWeeklyReviewWeek:week[0]})}>나중에</button></div>}
  {tab==='today'&&<>{assessment.transfer&&<details className="np-details np-transfer-choice"><summary>HISTORY에서 가져온 전략을 이번 일에 써보기</summary><p>실제로 사용한 일에만 표시해 주세요. 완료 표시만으로 전략 적용을 판단하지 않아요.</p>{data.tasks.filter(t=>t.status!=='done').map(t=><div key={t.id}><label className="np-check"><input type="checkbox" checked={!!t.transferUsed} onChange={e=>patch(t.id,{transferUsed:e.target.checked})}/>{t.title} · 가져온 전략 사용</label><label>이 일의 영역<select aria-label={`${t.title} 적용 영역`} value={t.domain||''} onChange={e=>patch(t.id,{domain:e.target.value as PlannerTask['domain']})}><option value="">영역 선택</option><option>학습</option><option>생활</option><option>업무</option></select></label></div>)}</details>}
   <TimeBlockBoard data={data} band={band} lower={assessment.educationStage==='elementary_1_3'} focused={assignment.target==='attention'||assignment.support==='successive'} selected={selected} select={setSelected} commit={commit} complete={recordCompletion}/>
   <details className="np-details"><summary>기존 할 일·단계 플래너 열기 (저장된 2.4 자료 유지)</summary>
   {assignment.target==='attention'||assignment.support==='successive'?<FocusDesk lower={assessment.educationStage==='elementary_1_3'} band={band} data={{...data,tasks:data.tasks.filter(t=>!t.timeBlock)}} commit={commitLegacy} open={setSelected} mode={mode} complete={recordCompletion}/>:band==='A'?<PlanningDesk lower={assessment.educationStage==='elementary_1_3'} band={band} data={{...data,tasks:data.tasks.filter(t=>!t.timeBlock)}} commit={commitLegacy} open={setSelected} mode={mode} complete={recordCompletion}/>:<AgePlanning band={band} data={{...data,tasks:data.tasks.filter(t=>!t.timeBlock)}} commit={commitLegacy} open={setSelected} mode={mode}/>}
   </details>
   {task&&!task.timeBlock&&<><button className="np-text-button" onClick={()=>setSelected('')}>세부 편집 닫고 내 플래너로 ↑</button><TaskEditor key={task.id} task={task} tasks={data.tasks} band={band} assignment={assignment} patch={changes=>patch(task.id,changes)} remove={()=>remove(task.id)} complete={(a,h,n)=>recordCompletion(task,a,h,n)} notify={setNotice}/></>}
  </>}
  {tab==='week'&&<section className="np-card"><span className="np-eyebrow">MAKE ROOM FOR YOUR WEEK</span><h2>{band==='A'?'이번 주에 챙길 일':band==='B'?'과목과 마감을 한눈에':band==='C'?'단계별 일정과 시간 배분':'프로젝트 일정과 대기 작업'}</h2><p>이름을 누르면 할 일을 열어요. 날짜를 바꾸면 이 일정에도 반영됩니다.</p>
   <CapacityShelf tasks={data.tasks.filter(t=>t.date===today)} capacity={data.dailyCapacity} onCapacity={n=>commit({...ref.current,dailyCapacity:n})}/>
   <div className="np-week">{week.map((date,i)=>{const list=data.tasks.filter(t=>t.date===date),milestones=(band==='C'||band==='D')?data.tasks.flatMap(t=>t.steps.filter(s=>s.date===date).map(s=>({t,s}))):[];const total=list.filter(t=>t.status!=='done').reduce((n,t)=>n+t.minutes,0);return <section key={date} className={date===today?'today':''}><header><b>{['월','화','수','목','금','토','일'][i]}</b><span>{date.slice(5)}</span><small className={total>data.dailyCapacity?'np-warning':''}>{total}/{data.dailyCapacity}분</small></header>{list.map(t=><button className={'np-week-task np-domain-block-'+(t.domain||'미지정')} key={t.id} onClick={()=>{setSelected(t.id);setTab('today');}}>{t.timeBlock?<><SubjectMark task={t}/><small>{t.timeBlock.startTime} · {t.minutes}분 · {t.learningScope}</small>{t.timeBlock.nextStart&&<small>↪ {t.timeBlock.nextStart}</small>}</>:<DomainMark domain={t.domain}/>}{t.status==='done'?'✓ ':''}{t.subject&&<small>{t.subject}</small>}{t.title}</button>)}{milestones.map(({t,s})=><button className="milestone" key={s.id} onClick={()=>{setSelected(t.id);setTab('today');}}><small>단계 · {t.title}</small>{s.done?'✓ ':''}{s.title}</button>)}{!list.length&&!milestones.length&&<span className="np-free">비워 둔 하루</span>}</section>;})}</div>
   <details className="np-details"><summary>이번 주 밖의 할 일 · 날짜 미정</summary>{data.tasks.filter(t=>!week.includes(t.date)).map(t=><button className="np-text-button" key={t.id} onClick={()=>{setSelected(t.id);setTab('today');}}>{t.date||'날짜 미정'} · {t.title}</button>)}</details>
   {band==='D'&&<div className="np-waiting"><h3>기다리는 동안 확인할 일</h3>{data.tasks.filter(t=>t.status!=='done'&&(t.waiting||dependencyBlocked(t,data.tasks))).map(t=><p key={t.id}><b>{t.title}</b> · {t.owner||'담당 미정'}{t.dependsOn&&` · 선행: ${data.tasks.find(x=>x.id===t.dependsOn)?.title}`}<button onClick={()=>{setSelected(t.id);setTab('today');}}>열기</button></p>)}<small>담당자 이름은 기록용이에요. 초대나 알림을 보내지 않아요.</small></div>}
  </section>}
  {tab==='growth'&&<section className="np-card"><span className="np-eyebrow">03 / REFLECT</span><h2>해본 만큼, 다음 계획을 조금 더 잘.</h2><BridgePath link={assessment.transfer} records={data.records} demo={mode==='demo'} canFollowup={!!linkedPrevious&&!!previousTask&&['학습','생활','업무'].includes(String(linkedPrevious.measures.taskDomain))} onFollowup={()=>setFollowup(v=>!v)}/>{pendingAdjustment&&<TimeAdjustmentPrompt task={pendingAdjustment} data={data} commit={commit}/>} {!linkedPrevious&&<p>실제 할 일에서 가져온 전략을 사용했다고 표시하고 완료하면 다른 영역 재적용을 열 수 있어요.</p>}{linkedPrevious&&!previousTask&&<p>이전 할 일이 삭제되어 재적용을 열 수 없어요. 새 할 일에서 전략을 사용하고 완료해 주세요.</p>}{linkedPrevious&&!(["학습","생활","업무"].includes(String(linkedPrevious.measures.taskDomain)))&&<p>다음 적용에서는 완료 전에 학습·생활·업무 중 영역을 선택해 주세요.</p>}{followup&&linkedPrevious&&previousTask&&assessment.transfer&&<FollowupTask key={linkedPrevious.id} strategy={assessment.transfer.strategyId} previousDomain={String(linkedPrevious.measures.taskDomain)} previousTask={previousTask.title} onDone={saveFollowup}/>}<div className="np-stats"><div><b>{weekRecord.count}/7</b><span>이번 주 기록한 날</span></div><div><b>{data.tasks.filter(t=>t.status==='paused').length}</b><span>이어갈 일</span></div><div><b>{data.records.length}</b><span>누적 활동 자기보고</span></div></div><p>완료는 직접 해봤다고 남긴 기록이에요. 실제 수행의 외부 확인이나 인지 점수와는 달라요.</p><label>다음 주에 바꿔볼 한 가지<textarea maxLength={1000} value={data.weeklyNote} onChange={e=>commit({...ref.current,weeklyNote:e.target.value})} placeholder="예: 예상보다 길었던 과제는 이틀로 나누기"/></label>
   {done.length===0?<p className="np-empty-small">할 일을 마치면 예상 시간과 실제 시간을 함께 볼 수 있어요.</p>:done.map(t=><article className="np-review" key={t.id}><b>{t.title}</b><p>{timeDifferenceText(t.minutes,t.actualMinutes)} · {t.timeBlock?'도움 여부는 따로 묻지 않았어요':t.help==='some'?'도움을 받았어요':'스스로 했어요'}</p><p>{t.timeAdjustment?'다음 계획 참고: '+timeAdjustmentLabel(t.timeAdjustment):t.adjustment||'다음 조정 선택을 기다리고 있어요.'}</p><small>{new Date(t.completedAt).toLocaleDateString('ko-KR')} · 자기보고</small></article>)}
   {data.records.some(r=>r.verification)&&<details className="np-details"><summary>외부 확인 기록</summary>{data.records.filter(r=>r.verification).map(r=><p key={r.id}>{r.verification!.reviewId} · {{supported:'근거 충족',not_supported:'근거 미충족',insufficient:'근거 부족'}[r.verification!.outcome]}</p>)}<small>연결한 서비스가 제공한 확인입니다. 이 HTML은 검토자 인증을 수행하지 않아요.</small></details>}
  </section>}
  </main><aside><GrowthIsland record={weekRecord}/><p className="np-streak">이번 주 7일 중 {weekRecord.count}일 기록</p><div className="np-side-card"><span className="np-eyebrow">나의 실행 안내</span><h3>{supports[assignment.support]}</h3><p>{assignment.support==='simultaneous'?'목표와 단계가 어떻게 이어지는지 보며, 시작할 순서를 정해요.':assignment.support==='successive'?'지금 할 한 가지를 마친 뒤, 다음 행동으로 넘어가요.':assignment.support==='planning'?'무엇을 끝낼지 먼저 확인하고, 마무리에서 기준과 비교해요.':assignment.support==='attention'?'필요한 자료와 지금 할 일에 표시하며 진행해요.':'작은 첫 행동을 정하고, 진행 뒤 빠진 것을 확인해요.'}</p><ol><li>할 일 적기</li><li>지금 시작하기</li><li>끝나고 조정하기</li></ol></div><div className="np-side-card np-saving"><h3>내 기록 보관</h3><p>이 브라우저에 자동 저장해요. 공용 기기에서도 남을 수 있어요. 기기·브라우저를 바꾸기 전 백업해 주세요.</p><button onClick={backup}>백업 내려받기</button><details><summary>백업 가져오기</summary><p>현재 프로필·학년의 자료를 파일 내용으로 교체해요. 먼저 백업을 내려받아 주세요.</p><label className="np-file">JSON 파일 선택<input aria-label="백업 파일" type="file" accept=".json,application/json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value='';}}/></label></details><details><summary>현재 자료 지우기</summary><p>현재 프로필·학년의 할 일과 기록을 지워요. 다른 프로필의 자료는 유지됩니다.</p><button className="np-danger" onClick={()=>{commit(blankWorkspace(scope));setSelected('');setNotice('현재 프로필의 자료를 지웠어요.');}}>이 자료 모두 지우기</button></details></div></aside></div>
 </>;
}
function TaskEditor({task:t,tasks,band,assignment,patch,remove,complete,notify}:{task:PlannerTask;tasks:PlannerTask[];band:Band;assignment:Assignment;patch:(changes:Partial<PlannerTask>)=>void;remove:()=>void;complete:(actual:number,help:'none'|'some',adjustment:string)=>void;notify:(message:string)=>void}){
 const [newStep,setNewStep]=useState(''),[newMaterial,setNewMaterial]=useState(''),[helpOpen,setHelpOpen]=useState(true),[finishing,setFinishing]=useState(false),[actual,setActual]=useState(''),[help,setHelp]=useState<'none'|'some'>('none'),[adjustment,setAdjustment]=useState(''),[deleteOpen,setDeleteOpen]=useState(false);
 const focused=assignment.support==='successive'||assignment.target==='attention';
 const current=t.steps.find(s=>!s.done),next=t.steps.filter(s=>!s.done)[1];
 const blocked=dependencyBlocked(t,tasks)||t.waiting;
 const done=t.status==='done',running=t.status==='active';
 const allChecked=t.steps.every(s=>s.done)&&t.materials.every(s=>s.done);
 function move(i:number,d:number){const steps=[...t.steps];[steps[i],steps[i+d]]=[steps[i+d],steps[i]];patch({steps});}
 function addStep(){if(!newStep.trim()||t.steps.length>=50)return;patch({steps:[...t.steps,{id:uid(),title:newStep.trim(),done:false,date:''}]});setNewStep('');}
 function addMaterial(){if(!newMaterial.trim()||t.materials.length>=100)return;patch({materials:[...t.materials,{id:uid(),title:newMaterial.trim(),done:false}]});setNewMaterial('');}
 function toggleStep(id:string){patch({steps:t.steps.map(s=>s.id===id?{...s,done:!s.done}:s)});}
 function start(){if(blocked||!practiceReady(t,focused))return;patch({status:'active',startedAt:t.startedAt||new Date().toISOString(),practice:{...emptyPractice,...t.practice,returns:(t.practice?.returns??0)+(focused&&t.status==='paused'?1:0)}});notify(t.status==='paused'?'남겨 둔 메모를 확인하고 이어가요.':'화면 밖에서 실제로 해본 뒤, 끝낸 단계를 체크해 주세요.');}
 function suggest(){patch({steps:[...t.steps,...['중간 결과 확인하기','마무리하고 빠진 것 살피기'].map(title=>({id:uid(),title,done:false,date:''}))]});notify('일반적인 단계 예시를 추가했어요. 내 과제에 맞게 고쳐 주세요.');}
 const planEditor=<div className="np-steps">{t.steps.map((s,i)=><div className="np-step-editor" key={s.id}><span className="np-step-index">{i+1}</span><div><label className="np-sr" htmlFor={`step-${s.id}`}>{i+1}번째 단계</label><input id={`step-${s.id}`} value={s.title} maxLength={160} disabled={done} onChange={e=>{if(e.target.value.trim())patch({steps:t.steps.map(x=>x.id===s.id?{...x,title:e.target.value}:x)});}}/>{(band==='C'||band==='D')&&<label className="np-step-date">이 단계의 날짜<input type="date" value={s.date} disabled={done} onChange={e=>patch({steps:t.steps.map(x=>x.id===s.id?{...x,date:e.target.value}:x)})}/></label>}</div>{!done&&<div className="np-step-tools"><button aria-label={`${i+1}단계 위로`} disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button aria-label={`${i+1}단계 아래로`} disabled={i===t.steps.length-1} onClick={()=>move(i,1)}>↓</button><button aria-label={`${i+1}단계 삭제`} disabled={t.steps.length===1} onClick={()=>patch({steps:t.steps.filter(x=>x.id!==s.id)})}>×</button></div>}</div>)}{!done&&<><form className="np-add-row" onSubmit={e=>{e.preventDefault();addStep();}}><input aria-label="새 단계" placeholder="다음 행동 직접 적기" maxLength={160} value={newStep} onChange={e=>setNewStep(e.target.value)}/><button type="submit" disabled={!newStep.trim()||t.steps.length>=50}>단계 추가</button></form>{t.steps.length===1&&<button className="np-text-button" onClick={suggest}>막막할 때 · 고쳐 쓸 단계 예시 넣기</button>}</>}</div>;
 return <section className={`np-card np-editor ${focused?'np-focus-mode':'np-map-mode'}`} data-testid="task-editor"><div className="np-section-heading"><div><span className="np-eyebrow">02 / DO · MY REAL TASK</span><h2>{done?'내가 완성한 일':running?'지금, 실제로 해볼 시간':t.status==='paused'?'잠깐 멈춘 자리에서':'시작할 준비를 해요'}</h2></div><span className="np-status">{{planned:'시작 전',active:'진행 중',paused:'잠깐 중단',done:'완료'}[t.status]}</span></div>
 <label>할 일 이름<input aria-label="할 일 이름 수정" value={t.title} maxLength={160} disabled={done} onChange={e=>{if(e.target.value.trim())patch({title:e.target.value});}}/></label>
 <label>할 일 영역<select aria-label="할 일 영역" value={t.domain||''} disabled={done} onChange={e=>patch({domain:(e.target.value||undefined) as PlannerTask['domain']})}><option value="">영역 미정</option><option>학습</option><option>생활</option><option>업무</option></select></label>
 <details className="np-details" open={band==='D'?true:undefined}><summary>{band==='A'?'날짜와 예상 시간':band==='B'?'과목·마감과 예상 시간':band==='C'?'목표 날짜와 예상 시간':'담당·일정·선행 작업'}</summary><div className="np-fields">{band!=='A'&&<label>{band==='D'?'프로젝트·분야':'과목'}<input maxLength={80} value={t.subject} disabled={done} onChange={e=>patch({subject:e.target.value})}/></label>}<label>할 날짜<input type="date" value={t.date} disabled={done} onChange={e=>patch({date:e.target.value})}/></label>{band!=='A'&&<label>제출·최종 마감<input type="date" value={t.deadline||''} disabled={done} onChange={e=>patch({deadline:e.target.value})}/></label>}<label>반복<select aria-label="할 일 반복" disabled={done} value={t.repeat||'none'} onChange={e=>patch({repeat:e.target.value as PlannerTask['repeat']})}><option value="none">반복 안 함</option><option value="daily">매일</option><option value="weekdays">평일</option></select></label><label>예상 시간(분)<input aria-label="예상 시간" type="number" min={1} max={1440} value={t.minutes} disabled={done} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=1440)patch({minutes:n});}}/></label>{band==='D'&&<><label>담당자<input maxLength={80} value={t.owner} disabled={done} onChange={e=>patch({owner:e.target.value})}/></label><label>먼저 끝나야 하는 일<select aria-label="선행 작업" value={t.dependsOn} disabled={done} onChange={e=>patch({dependsOn:e.target.value})}><option value="">없음 · 바로 가능</option>{tasks.filter(x=>canDependOn(tasks,t.id,x.id)).map(x=><option key={x.id} value={x.id}>{x.title}{x.status==='done'?' ✓':''}</option>)}</select></label><label className="np-check"><input type="checkbox" checked={t.waiting} disabled={done} onChange={e=>patch({waiting:e.target.checked,...(e.target.checked&&running?{status:'paused' as const}:{})})}/>외부 답변을 기다리는 중</label><small>실제 초대·알림은 전송하지 않아요.</small></>}</div></details>
 <CognitiveActivity task={t} focused={focused} patch={patch}/>
 <div className="np-support-head"><h3>{focused?'한 단계씩 이어가기':'전체 흐름을 보고 순서 정하기'}</h3><button onClick={()=>setHelpOpen(!helpOpen)} aria-expanded={helpOpen}>{helpOpen?'도움 접기':'도움 다시 보기'}</button></div>
 {helpOpen&&<div className="np-guidance" data-testid="support-guidance">{focused?<><b>규칙은 하나예요. 실제로 끝낸 뒤 다음 단계로.</b><p>현재 행동 하나만 보고 시작해요. 중단하면 돌아올 행동을 아래에 남겨요.</p></>:<><b>목표까지 가는 순서를 눈으로 확인해요.</b><p>단계의 위·아래 화살표로 순서를 바꾸고, 시작할 첫 행동을 정해요.</p><div className="np-flow" aria-label="전체 계획 지도"><strong>{t.title}</strong>{t.steps.map((s,i)=><div key={s.id}><span>{s.done?'✓':i+1}</span>{s.title}</div>)}</div></>}</div>}
 {focused&&running?<><div className="np-current"><span>지금 할 한 가지</span><h3>{current?.title||'마무리 확인하기'}</h3>{current&&<button className="np-primary" data-testid="finish-current-step" disabled={blocked} onClick={()=>toggleStep(current.id)}>이 단계를 실제로 끝냈어요 ✓</button>}<p>다음: {next?.title||(current?'마무리 확인':'모든 단계를 끝냈어요')}</p></div><details className="np-details"><summary>전체 단계 편집·체크 수정</summary>{planEditor}<div className="np-checklist">{t.steps.filter(s=>s.done).map(s=><label className="np-check" key={s.id}><input type="checkbox" checked onChange={()=>toggleStep(s.id)}/>{s.title}</label>)}</div></details></>:<>{focused?<details className="np-details"><summary>필요할 때 · 단계 추가와 순서 편집</summary>{planEditor}</details>:planEditor}{running&&<div className="np-checklist"><h3>실제로 끝낸 행동을 체크해요</h3>{t.steps.map(s=><label className="np-check" key={s.id}><input type="checkbox" disabled={blocked} checked={s.done} onChange={()=>toggleStep(s.id)}/>{s.title}</label>)}</div>}</>}
 <details className="np-details np-materials" open={band==='A'?true:undefined}><summary>내 준비물 · {t.materials.filter(m=>m.done).length}/{t.materials.length}</summary><p>목록에 없는 준비물도 직접 적을 수 있어요.</p>{t.materials.map(m=><div className="np-material" key={m.id}><input type="checkbox" aria-label={`${m.title} 챙김`} checked={m.done} disabled={done} onChange={e=>patch({materials:t.materials.map(x=>x.id===m.id?{...x,done:e.target.checked}:x)})}/><input aria-label="준비물 이름 수정" value={m.title} maxLength={160} disabled={done} onChange={e=>{if(e.target.value.trim())patch({materials:t.materials.map(x=>x.id===m.id?{...x,title:e.target.value}:x)});}}/>{!done&&<button aria-label={`${m.title} 삭제`} onClick={()=>patch({materials:t.materials.filter(x=>x.id!==m.id)})}>×</button>}</div>)}{!done&&<form className="np-add-row" onSubmit={e=>{e.preventDefault();addMaterial();}}><input aria-label="새 준비물" value={newMaterial} maxLength={160} onChange={e=>setNewMaterial(e.target.value)} placeholder="예: 색연필, 충전기, 내 자료"/><button disabled={!newMaterial.trim()||t.materials.length>=100}>준비물 추가</button></form>}</details>
 {blocked&&!done&&<p className="np-alert">{t.waiting?'외부 답변을 기다리고 있어요. 답변이 오면 대기 체크를 해제해 주세요.':`먼저 “${tasks.find(x=>x.id===t.dependsOn)?.title}”을 끝내 주세요.`}</p>}
 {!done&&<><label>중단하면 어디부터 이어갈까요? <span className="np-optional">선택</span><input aria-label="복귀 메모" maxLength={500} value={t.resumeNote} onChange={e=>patch({resumeNote:e.target.value})} placeholder="예: 3번 문제부터 다시 풀기"/></label>{t.status==='paused'&&<p className="np-resume">↪ 돌아올 자리: {t.resumeNote||current?.title||'준비물·마무리 확인'}</p>}
 {!running&&!practiceReady(t,focused)&&<p className="np-activity-prompt">{focused?'위에서 방해를 줄일 행동 하나를 정하면 시작할 수 있어요.':'위에서 첫 행동과 그 이유를 고르면 시작할 수 있어요.'}</p>}<div className="np-actions">{!running?<button className="np-primary" disabled={blocked||!practiceReady(t,focused)} data-testid="start-task" onClick={start}>{t.status==='paused'?(focused?'돌아올 행동 확인 · 이어하기 →':'이 자리부터 이어하기 →'):(focused?'방해를 줄였어요 · 지금 시작 →':'내가 정한 순서로 시작 →')}</button>:<><button onClick={()=>patch({status:'paused'})}>잠깐 멈추기</button><button className="np-primary" data-testid="review-task" disabled={!allChecked||blocked} onClick={()=>setFinishing(true)}>끝내고 돌아보기 →</button></>}</div>{running&&!allChecked&&<small>실제로 끝낸 단계와 준비물을 확인하면 마무리할 수 있어요. 필요 없는 항목은 삭제해도 돼요.</small>}
 {finishing&&running&&<form className="np-finish" onSubmit={e=>{e.preventDefault();if(allChecked&&!blocked&&actual.trim()&&Number(actual)>=0&&Number(actual)<=1440){complete(Number(actual),help,adjustment);setFinishing(false);}}}><h3>끝난 뒤, 세 가지만 확인해요</h3><label>실제로 쓴 시간(분)<input aria-label="실제 시간" required type="number" min={0} max={1440} value={actual} onChange={e=>setActual(e.target.value)}/></label><small>화면에 머문 시간이 아니라, 직접 확인한 시간을 적어 주세요.</small><label>도움은 받았나요?<select value={help} onChange={e=>setHelp(e.target.value as 'none'|'some')}><option value="none">스스로 했어요</option><option value="some">도움을 받았어요</option></select></label><label>다음에는 어떻게 바꿀까요? <span className="np-optional">선택</span><input aria-label="다음 조정" maxLength={500} value={adjustment} onChange={e=>setAdjustment(e.target.value)} placeholder="예: 자료 찾는 시간을 조금 더 잡기"/></label><button className="np-primary" type="submit" disabled={!allChecked||blocked||!actual.trim()||Number(actual)<0||Number(actual)>1440}>완료 기록 남기기 ✓</button></form>}
 </>}
 {done&&<div className="np-finish"><h3>완료한 일을 확인해요 ✓</h3><p>{timeDifferenceText(t.minutes,t.actualMinutes)}</p><p>{t.timeAdjustment?'다음 계획 참고: '+timeAdjustmentLabel(t.timeAdjustment):t.adjustment||'위의 다음 계획 선택에서 한 가지를 고를 수 있어요.'}</p><small>직접 완료했다고 기록한 자기보고이며 점수나 등급이 아니에요.</small></div>}
 <details className="np-details"><summary>할 일 삭제</summary><p>이 할 일과 준비물은 삭제합니다. 이미 남긴 완료 자기보고는 누적 기록에 남아요.</p>{!deleteOpen?<button className="np-danger" onClick={()=>setDeleteOpen(true)}>삭제 준비</button>:<div className="np-actions"><button className="np-danger" onClick={remove}>이 할 일 삭제 확정</button><button onClick={()=>setDeleteOpen(false)}>취소</button></div>}</details>
 </section>;
}
function GrowthIsland({record}:{record:{count:number;days:boolean[]}}){return <section className="np-island-card"><span className="np-eyebrow">MY NUVIA PATH</span><h3>이번 주에 지나온 길</h3><div className="np-island" role="img" aria-label={"이번 주 7일 중 "+record.count+"일 기록한 경로"}><div className="np-island-base"/><div className="np-desk"><div className="np-screen">✓</div><div className="np-keyboard"/></div><div className="np-orange-block">N</div><div className="np-purple-block">↗</div><div className="np-plant"><i/><b/></div><div className="np-week-path">{record.days.map((filled,i)=><i key={i} className={filled?"filled":""} aria-hidden="true"/>)}</div></div><div className="np-island-caption"><span><b>이번 주 7일 중 {record.count}일 기록</b><br/><small>빠진 날을 벌점이나 실패로 계산하지 않아요.</small></span></div><small>직접 남긴 완료 자기보고를 날짜별 경로로 보여 줍니다.</small></section>;}
