import React,{useState} from 'react';
import {createTask,uid,localDate,canDependOn,dependencyBlocked,type Workspace,type PlannerTask} from './workspace';
import type {Band} from './engine';
import './age-planning.css';
export function afterDays(n:number,from=localDate()){const d=new Date(from+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d);}
export function ageExamples(band:Band):PlannerTask[]{
 if(band==='A')return [['숙제 끝내기','문제집 펼치기'],['내일 준비물 챙기기','시간표 확인하기'],['운동하기','운동화 신기']].map(([a,b],i)=>({...createTask(a,b),minutes:10+i*5,materials:i===1?[{id:uid(),title:'색연필',done:false},{id:uid(),title:'체육복',done:false}]:[]}));
 if(band==='B')return [['수학 과제','수학','문제집 20쪽 풀기'],['과학 수행평가','과학','발표 주제 적기'],['영어 단어 복습','영어','단어 10개 확인하기']].map(([a,b,c],i)=>({...createTask(a,c),subject:b,deadline:afterDays(i+2),date:localDate(),minutes:20}));
 if(band==='C')return [{...createTask('탐구 발표 완성','탐구 질문 정하기'),subject:'과학',deadline:afterDays(7),steps:[['탐구 질문 정하기',0],['자료 정리하기',2],['초안 만들기',4],['검토하고 제출하기',7]].map(([title,n])=>({id:uid(),title:String(title),date:afterDays(Number(n)),done:false}))}];
 const one={...createTask('자료 조사','조사할 항목 정하기'),owner:'나',subject:'팀 발표',deadline:afterDays(2)};
 const two={...createTask('발표 초안 취합','팀원 자료 확인하기'),owner:'팀원',subject:'팀 발표',deadline:afterDays(4),dependsOn:one.id};
 return [one,two,{...createTask('최종 검토·제출','초안 읽기'),owner:'나',subject:'팀 발표',deadline:afterDays(6),dependsOn:two.id}];
}
export function SupportHint({data,children}:{data:Workspace;children:React.ReactNode}){
 const independent=data.records.slice(-2).length===2&&data.records.slice(-2).every(r=>r.measures.helpReceived===false);
 return <details className="np-details age-hint" open={independent?undefined:true}><summary>도움이 필요하면 열기</summary>{children}{independent&&<small>최근 두 완료 기록에서 스스로 수행했다고 남겼어요. 이번에는 도움을 접어 시작해요.</small>}</details>;
}
export function AgePlanning({band,data,commit,open,mode}:{band:Band;data:Workspace;commit:(w:Workspace)=>void;open:(id:string)=>void;mode:string}){
 const [title,setTitle]=useState(''),[subject,setSubject]=useState(''),[selected,setSelected]=useState(''),[milestone,setMilestone]=useState(''),[date,setDate]=useState(localDate()),[error,setError]=useState('');
 const tasks=data.tasks.filter(t=>t.status!=='done'),t=tasks.find(x=>x.id===selected)||tasks[0];
 const patch=(id:string,c:Partial<PlannerTask>)=>commit({...data,tasks:data.tasks.map(x=>x.id===id?{...x,...c}:x)});
 const titles={A:'오늘 준비하기',B:'과목별 할 일을 일주일에 나눠요',C:'마감에서 거꾸로, 중간 목표를 놓아요',D:'누가 무엇을 끝내야 다음으로 갈까요?'};
 return <section className={`np-card age-desk age-${band}`} data-testid={`age-plan-${band}`}><span className="np-eyebrow">{band==='B'?'WEEK / 과목별 배치':band==='C'?'GOAL / 거꾸로 계획':'TEAM / 역할과 연결'}</span><h2>{titles[band]}</h2>
 <SupportHint data={data}><p>{band==='B'?'할 일을 적고 할 날짜와 마감을 따로 정해요. 과목별 분량이 한날에 몰리면 다른 날로 옮겨요.':band==='C'?'마감일을 먼저 정해요. 그 전에 무엇이 끝나야 할지 중간 목표와 날짜를 하나씩 놓아요.': '담당자를 적고 먼저 끝나야 하는 일을 연결해요. 답변 대기와 선행 작업이 해결되면 실행할 수 있어요.'}</p></SupportHint>
 <form className="age-create" onSubmit={e=>{e.preventDefault();if(!title.trim()||data.tasks.length>=500)return;const x={...createTask(title,'첫 행동 직접 정하기'),subject};commit({...data,tasks:[...data.tasks,x]});setSelected(x.id);setTitle('');}}><label>{band==='D'?'프로젝트': '과목'}<input aria-label="새 과목 또는 프로젝트" maxLength={80} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>{band==='C'?'완성할 목표':'내 할 일'}<input aria-label="학년별 새 할 일" maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder={band==='C'?'예: 다음 주 탐구 발표 완성':'내 과제를 직접 적어 주세요'}/></label><button className="np-primary" disabled={!title.trim()||data.tasks.length>=500}>추가</button></form>
 {mode==='demo'&&!data.tasks.length&&<button data-testid="age-example" onClick={()=>commit({...data,tasks:ageExamples(band)})}>학년별 예시로 체험하기</button>}
 {band==='B'&&<><div className="age-week-totals">{Array.from({length:7},(_,i)=>afterDays(i)).map(d=>{const n=tasks.filter(x=>x.date===d).reduce((s,x)=>s+x.minutes,0);return <div key={d}><b>{d.slice(5)}</b><span>{n}분</span>{n>data.dailyCapacity&&<small>분량 조정</small>}</div>;})}</div><label>하루 가능한 시간(분)<input aria-label="주간 하루 가능 시간" type="number" min={1} max={1440} value={data.dailyCapacity} onChange={e=>{const n=+e.target.value;if(n>0&&n<=1440)commit({...data,dailyCapacity:n});}}/></label><div className="age-assignment-list">{tasks.map(x=><article key={x.id} data-testid="weekly-task"><b>{x.subject||'과목 미정'} · {x.title}</b><div className="age-fields"><label>할 날짜<input aria-label={`${x.title} 할 날짜`} type="date" value={x.date} onChange={e=>patch(x.id,{date:e.target.value})}/></label><label>제출 마감<input aria-label={`${x.title} 제출 마감`} type="date" value={x.deadline||''} onChange={e=>patch(x.id,{deadline:e.target.value})}/></label><label>오늘 분량(분)<input aria-label={`${x.title} 분량`} type="number" min={1} max={1440} value={x.minutes} onChange={e=>{const n=+e.target.value;if(n>0&&n<=1440)patch(x.id,{minutes:n});}}/></label></div>{x.deadline&&x.date>x.deadline&&<p role="status" className="np-warning">할 날짜가 제출 마감보다 늦어요.</p>}<button onClick={()=>open(x.id)}>과제 나누고 실행하기 →</button></article>)}</div></>}
 {band==='C'&&tasks.length>0&&<><label>계획할 목표<select aria-label="계획할 목표" value={t.id} onChange={e=>{setSelected(e.target.value);setError('');}}>{tasks.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><div className="age-deadline"><b>도착점 · {t.title}</b><label>최종 마감<input aria-label="목표 최종 마감" type="date" value={t.deadline||''} onChange={e=>patch(t.id,{deadline:e.target.value})}/></label></div><form className="age-create" onSubmit={e=>{e.preventDefault();if(!milestone.trim()||!date||t.steps.length>=50)return;if(t.deadline&&date>t.deadline){setError('중간 목표는 최종 마감 이전에 놓아 주세요.');return;}patch(t.id,{steps:[...t.steps,{id:uid(),title:milestone.trim(),date,done:false}]});setMilestone('');setError('');}}><label>그 전에 끝낼 일<input aria-label="중간 목표 이름" value={milestone} maxLength={160} onChange={e=>setMilestone(e.target.value)}/></label><label>끝낼 날짜<input aria-label="중간 목표 날짜" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button disabled={!milestone.trim()||!date||t.steps.length>=50}>중간 목표 놓기</button></form>{error&&<p role="alert">{error}</p>}<div className="age-milestones">{[...t.steps].sort((a,b)=>b.date.localeCompare(a.date)).map(s=><article key={s.id}><span>{s.done?'✓':'↥'}</span><b>{s.title}</b><label>날짜 조정<input aria-label={`${s.title} 중간 날짜`} type="date" value={s.date} onChange={e=>patch(t.id,{steps:t.steps.map(x=>x.id===s.id?{...x,date:e.target.value}:x)})}/></label>{s.date&&t.deadline&&s.date>t.deadline&&<small className="np-warning">최종 마감 이후예요</small>}</article>)}</div><button data-testid="chronological-plan" onClick={()=>patch(t.id,{steps:[...t.steps].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')),date:[...t.steps].filter(s=>!s.done&&s.date).sort((a,b)=>a.date.localeCompare(b.date))[0]?.date||t.date})}>이 날짜 순서로 실행 계획 만들기</button><button onClick={()=>open(t.id)}>단계별 실행 열기 →</button></>}
 {band==='D'&&<div className="age-team">{tasks.map(x=><article key={x.id} data-testid="team-task"><span className="age-state">{x.waiting?'답변 기다림':dependencyBlocked(x,data.tasks)?'선행 작업 기다림':'시작 가능'}</span><h3>{x.title}</h3><div className="age-fields"><label>담당자<input aria-label={`${x.title} 담당자`} maxLength={80} value={x.owner} onChange={e=>patch(x.id,{owner:e.target.value})}/></label><label>중간 마감<input aria-label={`${x.title} 팀 마감`} type="date" value={x.deadline||''} onChange={e=>patch(x.id,{deadline:e.target.value})}/></label><label>먼저 끝나야 하는 일<select aria-label={`${x.title} 선행 작업`} value={x.dependsOn} onChange={e=>patch(x.id,{dependsOn:e.target.value})}><option value="">없음</option>{data.tasks.filter(y=>canDependOn(data.tasks,x.id,y.id)).map(y=><option key={y.id} value={y.id}>{y.title}{y.status==='done'?' ✓':''}</option>)}</select></label></div>{x.dependsOn&&<p>← {data.tasks.find(y=>y.id===x.dependsOn)?.title}</p>}<label className="np-check"><input aria-label={`${x.title} 답변 대기`} type="checkbox" checked={x.waiting} onChange={e=>patch(x.id,{waiting:e.target.checked,...(e.target.checked&&x.status==='active'?{status:'paused' as const}:{})})}/>외부 답변 대기</label><button onClick={()=>open(x.id)}>담당 작업 열기 →</button></article>)}<small>담당·연결 상태는 내 플래너 기록입니다. 팀원에게 초대나 알림을 보내지 않습니다.</small></div>}
 {!tasks.length&&<p className="np-empty-small">내 할 일을 추가하면 여기에서 직접 계획할 수 있어요.</p>}
 <details className="np-details"><summary>완료한 일</summary>{data.tasks.filter(t=>t.status==='done').map(x=><button key={x.id} onClick={()=>open(x.id)}>✓ {x.title}</button>)}</details>
 </section>;
}
