import React,{useEffect,useState} from 'react';
import {type Band} from './engine';
import {createTask,localDate,uid,type PlannerTask,type Workspace} from './workspace';
import {blockActivityReady,extendFiveMinutes,actualBlockMinutes,closeTimeBlock,continueTimeBlock,newTimeBlock,remainingSeconds,startTimeBlock,stopTimeBlock,type TimeBlock} from './timeBlocks';
import {CapacityShelf,timeAdjustmentLabel,TimeAdjustmentPrompt,dateForReschedule} from './PlannerEnhancements';
import './time-blocks.css';

type Props={data:Workspace;band:Band;lower:boolean;focused:boolean;selected:string;select:(id:string)=>void;commit:(w:Workspace)=>void;complete:(t:PlannerTask,a:number,h:'none'|'some',n:string)=>void};
const phaseText:Record<TimeBlock['phase'],string>={ready:'시작 전',running:'실행 중',paused:'잠시 보관',review:'10초 기록',closed:'이어갈 카드'};
export function SubjectMark({task:t}:{task:PlannerTask}){return <span className={'tb-subject tb-'+(t.domain==='생활'?'life':t.domain==='업무'?'work':/수학/.test(t.subject)?'math':/국어|영어/.test(t.subject)?'language':'study')}><span aria-hidden="true">{t.domain==='생활'?'⌂':t.domain==='업무'?'▣':/수학/.test(t.subject)?'∑':'▤'}</span> {t.subject||t.domain||'학습'} · {t.domain||'학습'}</span>;}
export default function TimeBlockBoard({data,band,lower,focused,selected,select,commit,complete}:Props){
 const [message,setMessage]=useState(''),[editing,setEditing]=useState(false),[clock,setClock]=useState(Date.now()),[timerHidden,setTimerHidden]=useState(false),[completion,setCompletion]=useState(''),[action,setAction]=useState(''),[title,setTitle]=useState(''),[subject,setSubject]=useState('수학'),[scope,setScope]=useState(''),[domain,setDomain]=useState<PlannerTask['domain']>('학습'),[minutes,setMinutes]=useState('25'),[date,setDate]=useState(localDate()),[start,setStart]=useState('19:00');
 const blocks=data.tasks.filter(t=>t.timeBlock),unfinished=blocks.filter(t=>t.status!=='done');
 const running=blocks.find(t=>t.timeBlock?.phase==='running'),review=blocks.find(t=>t.timeBlock?.phase==='review');
 const next=(focused?unfinished.find(t=>t.timeBlock?.phase==='paused'):undefined)||unfinished.find(t=>t.date===localDate()&&t.timeBlock?.phase==='ready')||unfinished.find(t=>t.timeBlock?.phase==='paused')||unfinished[0];
 const task=running||review||blocks.find(t=>t.id===selected)||next;
 const b=task?.timeBlock,nowSeconds=task?remainingSeconds(task,clock):0;
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setClock(Date.now()),500);return()=>clearInterval(id);},[running?.id]);
 useEffect(()=>{setEditing(false);setCompletion('');setAction('');},[task?.id,b?.phase]);
 const change=(t:PlannerTask)=>commit({...data,tasks:data.tasks.map(x=>x.id===t.id?t:x)});
 const patch=(p:Partial<PlannerTask>)=>task&&change({...task,...p});
 const patchBlock=(p:Partial<TimeBlock>)=>task&&b&&patch({timeBlock:{...b,...p}});
 const safely=(fn:()=>void)=>{try{fn();setMessage('');}catch(e){setMessage((e as Error).message);}};
 function add(){if(!title.trim()||!scope.trim()||!subject.trim()||!date||!start||Number(minutes)<1||Number(minutes)>1440||data.tasks.length>=500)return;const t={...createTask(title,scope),subject,domain,date,focusRoute:(band==='A'?(lower?'picture_routine':'step_card'):band==='B'?'subject_scope':band==='C'?'deadline_triage':'handoff') as PlannerTask['focusRoute'],minutes:Number(minutes),learningScope:scope,timeBlock:newTimeBlock(start,Number(minutes))};commit({...data,tasks:[...data.tasks,t]});select(t.id);setTitle('');setScope('');setMessage('시간 블록을 만들었어요. 준비를 확인하고 시작해요.');}
 function launch(t:PlannerTask){safely(()=>{change(startTimeBlock({...t,routeConfirmed:true},data.tasks));setClock(Date.now());select(t.id);});}
 function move(t:PlannerTask,d:number){const list=[...data.tasks],other=blocks[blocks.findIndex(x=>x.id===t.id)+d];if(!other)return;const i=list.findIndex(x=>x.id===t.id),j=list.findIndex(x=>x.id===other.id);[list[i],list[j]]=[list[j],list[i]];commit({...data,tasks:list});setMessage('블록 순서를 바꿨어요. 오늘의 길이 정리됐어요.');}
 function reschedule(choice:'today'|'tomorrow'|'week'){if(!task||!b||b.phase==='running'||b.phase==='review')return;patch({date:dateForReschedule(choice),rescheduleChoice:choice,rescheduledAt:new Date().toISOString()});setMessage('내가 고른 날짜로 옮겼어요. 완료 여부는 바꾸지 않았어요.');}
 function saveReview(){if(!task||!b||!completion||(completion==='no'&&!action))return;safely(()=>{
  const closed=closeTimeBlock(task,completion==='yes');
  if(completion==='yes'){change(closed);complete(closed,actualBlockMinutes(closed),'none','');return;}
  if(action==='five'){change(extendFiveMinutes(task,data.tasks));setClock(Date.now());}
  else if(action==='next'){if(data.tasks.length>=500)throw new Error('할 일이 500개예요. 먼저 목록을 정리해 주세요.');const following=continueTimeBlock(closed);commit({...data,tasks:[...data.tasks.map(x=>x.id===task.id?closed:x),following]});select(following.id);}
  else change(closed);
 });}
 const canStart=!!task&&blockActivityReady(task,band,lower);
 return <section className={'np-card tb-board '+(focused?'tb-execution':'tb-assembly')} data-testid="time-block-board">
  <span className="np-eyebrow">{focused?'B / FOCUS STATION':'A / BUILD YOUR DAY'}</span><h2>{focused?'지금 한 블록, 집중 스테이션':'오늘의 시간 블록 조립 보드'}</h2>
  <details><summary>왜 이 도움이 필요할까?</summary><p>{focused?'현재 행동과 돌아올 자리를 가까이 두어요.':'여러 과목의 시간·순서를 직접 배치하고 시작할 일을 골라요.'} 실제 시간은 다음 계획의 참고 자료예요. 점수·집중력·인지능력을 측정하지 않아요. 중단을 누르기 전까지의 시계 경과 시간을 기록하므로 화면 밖에서 쉬었다면 참고해서 해석해 주세요.</p></details>
  {message&&<p role="status" className="np-notice">{message}</p>}
  {!running&&!review&&<details className="tb-create" open={blocks.length===0?true:undefined}><summary>＋ {blocks.length?'새 시간 블록 만들기':'오늘 할 일 한 가지 적기'}</summary><form onSubmit={e=>{e.preventDefault();add();}}>
   <label>할 일<input aria-label="블록 할 일" required maxLength={160} placeholder="예: 수학 문제 풀기" value={title} onChange={e=>setTitle(e.target.value)}/></label>
   <div className="tb-fields"><label>영역<select aria-label="블록 영역" value={domain} onChange={e=>setDomain(e.target.value as PlannerTask['domain'])}><option>학습</option><option>생활</option><option>업무</option></select></label><label>과목·활동<input aria-label="블록 과목" required maxLength={80} value={subject} onChange={e=>setSubject(e.target.value)}/></label></div>
   <label>{lower&&band==='A'?'지금 할 한 가지':'범위 · 오늘 할 분량'}<input aria-label="블록 범위" required maxLength={160} value={scope} onChange={e=>setScope(e.target.value)} placeholder="예: 문제집 1~20번"/></label>
   <div className="tb-fields"><label>날짜<input aria-label="블록 날짜" type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>시작 시각<input aria-label="블록 시작 시각" type="time" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>예상 시간(분)<input aria-label="블록 예상 시간" type="number" required min={1} max={1440} value={minutes} onChange={e=>setMinutes(e.target.value)}/></label></div>
   <div className="tb-presets" aria-label="추천 시간">{[15,20,25,40,50].map(n=><button type="button" key={n} aria-pressed={Number(minutes)===n} onClick={()=>setMinutes(String(n))}>{n}분</button>)}</div><button className="np-primary" disabled={data.tasks.length>=500}>시간 블록 만들기</button>
  </form></details>}
  {task&&b&&<article key={task.id+':'+b.phase} className={'tb-station tb-phase-'+b.phase} data-testid="block-station">
   <div className="tb-station-head"><SubjectMark task={task}/><span>{task.status==='done'?'직접 완료 확인':phaseText[b.phase]}</span></div>
   <small>{task.date} · {b.startTime} · 계획 {task.minutes}분</small><h3>{task.title}</h3><p className="tb-scope">{task.learningScope||task.steps[0].title}</p>
   {(task.planningReference||task.timeAdjustment)&&<p className="tb-return">다음 계획 참고: {timeAdjustmentLabel(task.timeAdjustment||task.planningReference)}</p>}
   {b.nextStart&&<p className="tb-return">↪ 다음 시작 위치: <strong>{b.nextStart}</strong></p>}
   {b.phase==='running'?<><small>🎒 {task.materials.map(m=>m.title).join(' · ')||'준비물 따로 없음'}</small><p>지금: {task.steps.find(s=>s.id===b.chosenStepId)?.title||task.nextTenAction||task.steps.find(s=>!s.done)?.title}</p><div className="tb-clock"><button onClick={()=>setTimerHidden(v=>!v)}>{timerHidden?'시간 보기':'시간 숨기기'}</button>{!timerHidden&&(nowSeconds>0?<span role="timer">{Math.floor(nowSeconds/60)}:{String(nowSeconds%60).padStart(2,'0')} <small>남음</small></span>:<p role="status">계속할까요?</p>)}</div><div className="tb-controls"><button onClick={()=>safely(()=>change(stopTimeBlock(task,'paused')))}>중단</button><button className="np-primary" onClick={()=>safely(()=>change(stopTimeBlock(task,'review')))}>종료</button></div><small>시간이 끝나도 자동 완료되지 않아요.</small></>:
   b.phase==='review'?<div className="tb-review"><h4>끝난 뒤 10초 기록</h4><p>계획 {task.minutes}분 · 실제 경과 {task.actualMinutes}분 (중단 시간 제외)</p><label>어디까지 했나요?<input aria-label="어디까지 했나요" maxLength={500} value={b.covered} onChange={e=>patchBlock({covered:e.target.value})} placeholder="예: 12번까지"/></label><label>다음에는 어디서 시작할까요?<input aria-label="종료 다음 시작 위치" maxLength={500} value={b.nextStart} onChange={e=>patchBlock({nextStart:e.target.value})} placeholder="예: 13번부터"/></label><label>시간 느낌 · 선택<select aria-label="시간 느낌" value={b.comparison} onChange={e=>patchBlock({comparison:e.target.value as TimeBlock['comparison']})}><option value="">선택 안 함</option><option value="longer">예상보다 길었음</option><option value="similar">비슷했음</option><option value="shorter">짧았음</option></select></label><label>완료 여부 · 직접 선택<select aria-label="블록 완료 여부" value={completion} onChange={e=>setCompletion(e.target.value)}><option value="">직접 선택해 주세요</option><option value="yes">할 일·단계·준비물을 모두 마쳤어요</option><option value="no">이어서 할 일이 있어요</option></select></label>{completion==='no'&&<div role="group" aria-label="미완료 다음 선택" className="tb-presets">{[['five','5분 더 하기'],['next','다음 시간 블록 만들기'],['today','오늘 마치기']].map(([v,l])=><button key={v} aria-pressed={action===v} onClick={()=>setAction(v)}>{l}</button>)}</div>}<button className="np-primary" disabled={!completion||(completion==='no'&&!action)} onClick={saveReview}>짧은 기록 저장</button><small>완료는 자기보고예요. 외부 확인·교육 효과의 증명이 아니에요.</small></div>:
   task.status==='done'?<><p>계획 {task.minutes}분 · 실제 경과 {task.actualMinutes}분</p><p>한 곳: {b.covered||'따로 적지 않았어요'}</p>{!task.timeAdjustment&&<TimeAdjustmentPrompt task={task} data={data} commit={commit}/>}</>:
   <>
    {b.phase==='paused'&&<div className="tb-pause"><h4>▣ 잠시 보관함 · 돌아올 자리</h4><label>{band==='B'?'남은 범위 · 다음 시작 위치':'다음 시작 위치'}<input autoFocus aria-label="중단 다음 시작 위치" maxLength={500} value={b.nextStart} onChange={e=>patch({resumeNote:e.target.value,timeBlock:{...b,nextStart:e.target.value},...(band==='B'?{remainingScope:e.target.value}:{})})}/></label>{band==='B'&&<label>다음 10분 행동<input aria-label="다음 10분 행동" maxLength={160} value={task.nextTenAction||''} onChange={e=>patch({nextTenAction:e.target.value})}/></label>}{band==='D'&&<label>인계·후속 확인 메모<input aria-label="인계 메모" maxLength={500} value={b.handoffNote} onChange={e=>patchBlock({handoffNote:e.target.value})}/></label>}</div>}
    <div className="tb-age-tools" data-testid={'block-age-'+(band==='A'?(lower?'lower':'upper'):band)}>
     {band==='A'&&lower?<><p className="tb-picture">🎒 준비 → ▶ 시작 → ✓ 끝</p><p>한 가지: {task.steps[0].title}</p><label className="np-check"><input type="checkbox" checked={b.prepared} onChange={e=>patchBlock({prepared:e.target.checked})}/>🎒 준비물과 첫 행동을 확인했어요</label></>:
      band==='A'?<label>지금 할 단계 카드<select aria-label="지금 할 단계 카드" value={b.chosenStepId} onChange={e=>patchBlock({chosenStepId:e.target.value})}><option value="">단계를 골라요</option>{task.steps.filter(s=>!s.done).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>:
      band==='B'?<><label>이 과목의 오늘 분량<input aria-label="오늘 분량" maxLength={160} value={task.learningScope||''} onChange={e=>patch({learningScope:e.target.value})}/></label><p>오늘 {task.subject}: {blocks.filter(x=>x.subject===task.subject&&x.date===task.date).reduce((sum,x)=>sum+x.minutes,0)}분 배치</p></>:
      band==='C'?<><label>시험·마감 날짜<input aria-label="시험 날짜" type="date" value={task.deadline||''} onChange={e=>patch({deadline:e.target.value})}/></label>{task.deadline&&<p>{Math.ceil((new Date(task.deadline+'T00:00:00').getTime()-new Date(localDate()+'T00:00:00').getTime())/86400000)>=0?'D−':'D+'}{Math.abs(Math.ceil((new Date(task.deadline+'T00:00:00').getTime()-new Date(localDate()+'T00:00:00').getTime())/86400000))} · 여러 과목 중 지금 할 일을 판단해요</p>}<div className="tb-presets"><button aria-pressed={task.deadlineDecision==='continue'} onClick={()=>patch({deadlineDecision:'continue'})}>계속하기</button><button aria-pressed={task.deadlineDecision==='split'} onClick={()=>{patch({deadlineDecision:'split'});setEditing(true);}}>나누기 · 단계 편집</button><button aria-pressed={task.deadlineDecision==='defer'} onClick={()=>{patch({deadlineDecision:'defer',date:dateForReschedule('tomorrow')});setMessage('내일로 옮겼어요. 다른 블록을 고르거나 이 블록을 다시 선택해 시작할 수 있어요.');}}>다른 날 · 내일로</button></div></>:
      <><label>수업·업무·회의 전 가용 시간의 끝<input aria-label="가용 시간 끝" type="time" value={b.availableUntil} onChange={e=>patchBlock({availableUntil:e.target.value})}/></label>{b.availableUntil&&<p>시작 {b.startTime} → 다음 일정 {b.availableUntil} · 같은 날 기준 {Math.max(0,(Number(b.availableUntil.slice(0,2))*60+Number(b.availableUntil.slice(3)))-(Number(b.startTime.slice(0,2))*60+Number(b.startTime.slice(3))))}분 공간 / 계획 {task.minutes}분</p>}<label>다음 행동 상태<select aria-label="다음 행동 상태" value={task.handoffState||''} onChange={e=>patch({handoffState:e.target.value as PlannerTask['handoffState'],waiting:e.target.value==='waiting'})}><option value="">구분해 주세요</option><option value="now">즉시 할 다음 행동</option><option value="waiting">답변 대기</option><option value="check">다른 사람에게 확인 요청</option></select></label><label>인계·후속 확인 메모<input aria-label="후속 확인 메모" maxLength={500} value={b.handoffNote} onChange={e=>patchBlock({handoffNote:e.target.value})}/></label></>}
    </div>
    {b.phase!=='paused'&&<label>다음 시작 위치<input aria-label="계획 다음 시작 위치" maxLength={500} value={b.nextStart} onChange={e=>patchBlock({nextStart:e.target.value})}/></label>}
    <div className="tb-controls"><button className="np-primary" disabled={!canStart} onClick={()=>launch(task)}>{b.phase==='ready'?'시작':'재개'}</button>{b.phase==='paused'&&<button onClick={()=>safely(()=>change(stopTimeBlock(task,'review')))}>종료</button>}<button onClick={()=>setEditing(v=>!v)} aria-expanded={editing}>시간·범위·단계 수정</button></div>
    {!canStart&&<small>위의 준비 또는 활동 선택을 먼저 확인해 주세요.</small>}
    <details open={editing||undefined}><summary>블록 편집 · 반복 · 다시 배치하기</summary><BlockFields key={task.id} task={task} change={change}/><div className="tb-presets">{(['today','tomorrow','week'] as const).map((c,i)=><button key={c} onClick={()=>reschedule(c)}>{['오늘로','내일로','이번 주로'][i]}</button>)}</div></details>
   </>}
  </article>}
  {!running&&!review&&<CapacityShelf tasks={data.tasks.filter(t=>t.date===localDate())} capacity={data.dailyCapacity} onCapacity={n=>commit({...data,dailyCapacity:n})}/>}
  <details className="tb-queue" open={!focused?true:undefined}><summary>{focused?'다른 블록·이어갈 카드 보기':'과목별 블록 배치 · 위/아래로 순서 정하기'} ({unfinished.length})</summary><div className="tb-block-list">{blocks.map((t,i)=><article key={t.id} className={'tb-mini '+(task?.id===t.id?'selected':'')}><SubjectMark task={t}/><button className="tb-open" onClick={()=>{if(running&&running.id!==t.id){setMessage('현재 블록을 먼저 중단하거나 종료해 주세요.');return;}if(review&&review.id!==t.id){setMessage('현재 블록의 종료 기록을 먼저 저장해 주세요.');return;}select(t.id);}}><b>{t.title}</b><span>{t.date} · {t.timeBlock!.startTime} · {t.minutes}분</span><small>{t.learningScope} · {t.status==='done'?'완료':phaseText[t.timeBlock!.phase]}</small>{t.timeBlock!.nextStart&&<small>↪ {t.timeBlock!.nextStart}</small>}</button>{(!focused||band==='C')&&<div className="tb-order"><button aria-label={t.title+' 위로'} disabled={i===0||!!running||!!review} onClick={()=>move(t,-1)}>↑ 위로</button><button aria-label={t.title+' 아래로'} disabled={i===blocks.length-1||!!running||!!review} onClick={()=>move(t,1)}>↓ 아래로</button></div>}</article>)}</div></details>
 </section>;
}

function BlockFields({task:t,change}:{task:PlannerTask;change:(t:PlannerTask)=>void}){
 const [step,setStep]=useState(''),[material,setMaterial]=useState('');const b=t.timeBlock!;const patch=(p:Partial<PlannerTask>)=>change({...t,...p});
 return <div className="tb-edit">
  <label>할 일 이름<input aria-label="블록 이름 수정" maxLength={160} value={t.title} onChange={e=>{if(e.target.value.trim())patch({title:e.target.value});}}/></label>
  <div className="tb-fields"><label>과목·활동<input aria-label="블록 과목 수정" maxLength={80} value={t.subject} onChange={e=>patch({subject:e.target.value})}/></label><label>영역<select value={t.domain} onChange={e=>patch({domain:e.target.value as PlannerTask['domain']})}><option>학습</option><option>생활</option><option>업무</option></select></label></div>
  <label>범위<input aria-label="블록 범위 수정" maxLength={160} value={t.learningScope||''} onChange={e=>patch({learningScope:e.target.value})}/></label>
  <div className="tb-fields"><label>날짜<input aria-label="블록 날짜 수정" type="date" required value={t.date} onChange={e=>{if(e.target.value)patch({date:e.target.value});}}/></label><label>시작 시각<input aria-label="블록 시작 시각 수정" type="time" value={b.startTime} onChange={e=>{if(e.target.value)patch({timeBlock:{...b,startTime:e.target.value}});}}/></label><label>예상 시간(분)<input aria-label="블록 시간 수정" type="number" min={1} max={1440} value={t.minutes} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=1440)patch({minutes:n,timeBlock:{...b,budgetMinutes:n}});}}/></label><label>반복<select aria-label="블록 반복" value={t.repeat||'none'} onChange={e=>patch({repeat:e.target.value as PlannerTask['repeat']})}><option value="none">반복 없음</option><option value="daily">매일</option><option value="weekdays">평일</option></select></label></div>
  <h4>단계 카드</h4>{t.steps.map((s,i)=><div className="tb-child" key={s.id}><input type="checkbox" aria-label={s.title+' 단계 완료'} checked={s.done} onChange={e=>patch({steps:t.steps.map(x=>x.id===s.id?{...x,done:e.target.checked}:x)})}/><input aria-label={(i+1)+'번째 블록 단계'} maxLength={160} value={s.title} onChange={e=>{if(e.target.value.trim())patch({steps:t.steps.map(x=>x.id===s.id?{...x,title:e.target.value}:x)});}}/></div>)}
  <div className="tb-fields"><input aria-label="블록 새 단계" maxLength={160} value={step} onChange={e=>setStep(e.target.value)} placeholder="나눌 다음 행동"/><button disabled={!step.trim()||t.steps.length>=50} onClick={()=>{patch({steps:[...t.steps,{id:uid(),title:step.trim(),done:false,date:''}]});setStep('');}}>단계 추가</button></div>
  <h4>준비물</h4>{t.materials.map((m,i)=><div className="tb-child" key={m.id}><input aria-label={m.title+' 준비 완료'} type="checkbox" checked={m.done} onChange={e=>patch({materials:t.materials.map(x=>x.id===m.id?{...x,done:e.target.checked}:x)})}/><input aria-label={(i+1)+'번째 블록 준비물'} maxLength={160} value={m.title} onChange={e=>{if(e.target.value.trim())patch({materials:t.materials.map(x=>x.id===m.id?{...x,title:e.target.value}:x)});}}/></div>)}
  <div className="tb-fields"><input aria-label="블록 새 준비물" maxLength={160} value={material} onChange={e=>setMaterial(e.target.value)} placeholder="챙길 준비물"/><button disabled={!material.trim()||t.materials.length>=100} onClick={()=>{patch({materials:[...t.materials,{id:uid(),title:material.trim(),done:false}]});setMaterial('');}}>준비물 추가</button></div>
 </div>;
}
