import React,{useState} from 'react';
import {STRATEGY_LABELS} from './engine';
import type {TransferLink,TransferStrategy,TrainingRecord} from './engine';
export const STRATEGY_PROMPTS:Record<TransferStrategy,{before:string;after:string;support:string}>={
 PLAN_DO_CHECK:{before:'맨 먼저 할 행동을 적어주세요',after:'끝낸 뒤 빠진 것이 있었나요?',support:'순서를 정하고 → 하나씩 하고 → 빠진 것을 확인해요.'},
 STEP_BREAKDOWN:{before:'과제를 나눈 순서와 먼저 해야 할 이유를 적어주세요',after:'단계 중 빠뜨리거나 순서를 바꾼 부분은 무엇이었나요?',support:'목표를 떠올리고 → 실행 단위로 나누고 → 먼저 필요한 단계를 확인해요.'},
 EVIDENCE_COMPARE:{before:'비교할 근거 두 가지와 판단 기준을 적어주세요',after:'두 근거를 비교한 뒤 어떤 선택을 했나요?',support:'근거 두 개의 출처와 내용을 확인하고 → 같은 점·다른 점을 비교하고 → 선택의 이유를 정해요.'},
 JUDGMENT_REVISION:{before:'현재 판단과 그 판단을 바꿀 수 있는 조건을 적어주세요',after:'새 정보 때문에 판단을 유지하거나 수정한 이유는 무엇인가요?',support:'처음 판단과 이유를 적고 → 새 정보를 확인하고 → 판단을 유지할지 바꿀지 결정해요.'}
};
export function BridgePath({link,demo,records,onFollowup,canFollowup}:{onFollowup?:()=>void;canFollowup?:boolean;link?:TransferLink;demo:boolean;records:TrainingRecord[]}){
 const linked=records.filter(r=>link&&r.context.transfer?.bridgeId===link.bridgeId&&r.context.strategyId===link.strategyId);
 const applications=linked.filter(r=>r.kind==='real_task'&&r.measures.strategyApplied===true),followups=linked.filter(r=>r.kind==='followup_task');
 const verified=[...applications,...followups].filter(r=>r.verification?.outcome==='supported').length;
 return <section className="ad-panel ad-bridge" data-testid="transfer-bridge"><div className="ad-bridge-title"><div><span className="ad-kicker">KIDS → HISTORY → PLANNER → MY NUVIA</span><h2>배운 전략을, 다른 장면에서도.</h2>{demo&&<div className="np-demo-history"><b>데모 전용</b><p>예시 전략 이력은 기능 검수용이며 실제 KIDS/HISTORY 수행 이력이 아닙니다.</p><button data-testid="load-demo-history" onClick={()=>window.dispatchEvent(new Event('nuvia:load-demo-history'))}>예시 전략 이력 불러오기</button></div>}</div><span className="ad-pill">{demo?'예시 연결 기록':link?'HISTORY 기록 수신':'이전 활동 연결 대기'}</span></div><div className="ad-bridge-stages"><article><span>01 / KIDS</span><strong>인지전략의 기초</strong><small>{link?.kids?'출처 기록 연결됨':'기초 활동 기록 미연결'}</small></article><article><span>02 / HISTORY</span><strong>{link?STRATEGY_LABELS[link.strategyId]:'역사 속 사고전략'}</strong><small>{link?'역사 활동의 전략을 가져옴':'HISTORY 전략 수신 대기'}</small></article><article><span>03 / PLANNER</span><strong>실제 과제에 재사용</strong><small>{applications.length?`적용 자기보고 ${applications.length}회`:'실제 과제로 연결할 차례'}</small></article><article><span>04 / MY NUVIA</span><strong>근거를 따라 확인</strong><small>{verified?`외부 확인 근거 충족 ${verified}회`:followups.length?`다른 과제 재사용 자기보고 ${followups.length}회`:'독립 적용·외부 확인 대기'}</small>{onFollowup&&<button data-testid="open-followup" disabled={!canFollowup} onClick={onFollowup}>다른 영역에 써보기 →</button>}</article></div><p>{demo?'이 경로는 기능 확인을 위한 예시입니다. 실제 KIDS·HISTORY 수행 이력을 뜻하지 않습니다.':link?'전략의 출처와 실제 적용 기록을 연결합니다. 자기보고와 외부 확인은 별도로 표시합니다.':'이전 프로그램 기록이 없어도 현재 훈련은 가능합니다. 연결 전에는 프로그램 간 전이가 확인되었다고 표시하지 않습니다.'}</p></section>;
}
export function FollowupTask({strategy,previousDomain,previousTask,onDone}:{strategy:TransferStrategy;previousDomain:string;previousTask:string;onDone:(m:TrainingRecord['measures'])=>void}){
 const [task,setTask]=useState(''),[domain,setDomain]=useState(''),[plan,setPlan]=useState(''),[outcome,setOutcome]=useState(''),[help,setHelp]=useState('0'),[started,setStarted]=useState(false),[showSupport,setShowSupport]=useState(false),[usedSupport,setUsedSupport]=useState(false),[done,setDone]=useState('');
 const [sent,setSent]=useState(false);const prompt=STRATEGY_PROMPTS[strategy];
 return <section className="ad-panel ad-real"><span className="ad-kicker">04 / TRANSFER CHECK</span><h2>다른 과제에서도 스스로 써볼까요?</h2><p>이번에는 <strong>{STRATEGY_LABELS[strategy]}</strong>을 다른 영역의 과제에 다시 적용해요. 안내는 접어두었어요. 필요하면 언제든 열어도 괜찮아요.</p><button className="ad-btn secondary" aria-expanded={showSupport} data-testid="followup-support" onClick={()=>{if(!showSupport)setUsedSupport(true);setShowSupport(v=>!v);}}>{showSupport?'안내 접기':'전략 안내 다시 보기'}</button>{showSupport&&<p className="ad-feedback">{prompt.support}</p>}
 {!started?<><label>다른 과제 영역<select data-testid="followup-domain" value={domain} onChange={e=>setDomain(e.target.value)}><option value="">앞 과제와 다른 영역 선택</option>{['학습','생활','업무'].filter(d=>d!==previousDomain).map(d=><option key={d}>{d}</option>)}</select></label><label>새로 적용할 과제<input data-testid="followup-task" maxLength={120} value={task} onChange={e=>setTask(e.target.value)} placeholder="앞서 한 과제와 다른 일을 적어주세요"/></label><label>{prompt.before}<textarea data-testid="followup-plan" maxLength={400} value={plan} onChange={e=>setPlan(e.target.value)}/></label><button className="ad-btn" data-testid="start-followup" disabled={!task.trim()||task.replace(/\s/g,'').toLowerCase()===previousTask.replace(/\s/g,'').toLowerCase()||!plan.trim()||!domain||domain===previousDomain} onClick={()=>setStarted(true)}>다른 과제에서 실행</button></>:<><div className="ad-real-summary"><strong>{domain} · {task}</strong></div><p>실제로 해본 뒤 돌아와 아래 내용을 남겨주세요.</p><label>{prompt.after}<textarea data-testid="followup-outcome" maxLength={400} value={outcome} onChange={e=>setOutcome(e.target.value)}/></label><label>추가 도움을 받은 횟수<input data-testid="followup-help" type="number" min="0" max="100" step="1" value={help} onChange={e=>setHelp(e.target.value)}/></label><label>새 과제의 완료 여부<select data-testid="followup-completed" value={done} onChange={e=>setDone(e.target.value)}><option value="">실행 후 선택</option><option value="yes">완료했어요</option><option value="partial">일부 진행했어요</option></select></label><button className="ad-btn" data-testid="save-followup" disabled={sent||!outcome.trim()||!done||help.trim()===''||!Number.isInteger(Number(help))||Number(help)<0||Number(help)>100} onClick={()=>{if(sent)return;setSent(true);onDone({taskDomain:domain,previousTaskDomain:previousDomain,strategyId:strategy,helpCount:Number(help),supportOpened:usedSupport,independentSelfReport:Number(help)===0&&!usedSupport,completed:done,processEvidenceEntered:true,processEvidenceSource:'self_report',verificationStatus:'pending_external_review',taskContentStored:false});}}>재사용 기록 남기기</button></>}
 <small>도움 없이 했다는 응답도 자기보고입니다. 다른 영역을 선택했다는 사실만으로 전이 효과가 입증되지는 않습니다. 작성 내용은 현재 화면에서만 사용하며 원문 저장은 별도 동의·연결이 필요합니다.</small></section>;
}
