(function(){
'use strict';

var FALLBACK='ko';
var MODE=document.body.dataset.mode||'homeroom';
var state={locale:null,pack:null,fallback:null,manifest:[],filter:'all',selectedStudent:'A01',selectedClass:'A',selectedTrack:'BIZ',formationVersion:0};
var students=[
  {id:'A01',age:14,s:{planning:85,attention:89,simultaneous:71,sequential:85},tier:'priority'},
  {id:'A02',age:14,s:{planning:93,attention:107,simultaneous:84,sequential:85},tier:'support'},
  {id:'A03',age:15,s:{planning:103,attention:97,simultaneous:84,sequential:112},tier:'support'},
  {id:'A04',age:14,s:{planning:99,attention:86,simultaneous:106,sequential:113},tier:'watch'},
  {id:'A05',age:15,s:{planning:126,attention:111,simultaneous:108,sequential:116},tier:'growth'},
  {id:'A06',age:14,s:{planning:97,attention:75,simultaneous:102,sequential:81},tier:'priority'},
  {id:'A07',age:15,s:{planning:100,attention:108,simultaneous:85,sequential:78},tier:'support'},
  {id:'A08',age:14,s:{planning:112,attention:104,simultaneous:119,sequential:114},tier:'growth'}
];
var classes=[
  {id:'A',name:'Class A',count:24,s:[101.3,99.4,97.0,98.5],priority:3,completion:96},
  {id:'B',name:'Class B',count:23,s:[100.2,94.8,105.8,104.8],priority:4,completion:96},
  {id:'C',name:'Class C',count:24,s:[102.2,101.3,96.5,91.8],priority:6,completion:92},
  {id:'D',name:'Class D',count:22,s:[97.5,100.8,101.5,96.5],priority:3,completion:100}
];
var tracks=[
  {id:'BIZ',name:'Business & Public',count:24,s:[106.3,103.7,99.6,101.3]},
  {id:'EDU',name:'Education & Social',count:23,s:[105.0,106.9,102.3,106.1]},
  {id:'ART',name:'Arts & Media',count:20,s:[104.6,98.4,113.6,101.2]},
  {id:'MED',name:'Health & Medical',count:21,s:[100.6,108.8,98.0,105.5]},
  {id:'ICT',name:'ICT & Science',count:22,s:[107.5,102.8,104.1,99.9]}
];
var domainKeys=['planning','attention','simultaneous','sequential'];

function esc(v){return String(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function query(){var out={};new URLSearchParams(location.search).forEach(function(v,k){out[k]=v;});return out;}
function interpolate(text,vars){return String(text||'').replace(/\{(\w+)\}/g,function(_,k){return vars&&vars[k]!=null?vars[k]:'';});}
function t(key,vars){var a=state.pack&&state.pack.messages||{},b=state.fallback&&state.fallback.messages||{};var value=a[key]||b[key];if(!value){console.warn('[school-dashboard-demo]['+state.locale+'] missing '+key);return '';}return interpolate(value,vars);}
function localeAlias(code){var c=(code||'').toLowerCase();if(c==='zh'||c==='zh-cn'||c==='zh-hans')return'zh-CN';if(c==='zh-tw'||c==='zh-hant'||c==='zh-hk')return'zh-TW';return state.manifest.map(function(x){return x.code;}).find(function(x){return x.toLowerCase()===c;})||null;}
function resolveLocale(){var q=query(),requested=localeAlias(q.lang);if(requested)return requested;var stored;try{stored=localeAlias(localStorage.getItem('fg.schoolDashboard.locale'));}catch(e){}if(stored)return stored;return localeAlias(navigator.language)||localeAlias((navigator.language||'').split('-')[0])||FALLBACK;}
function loadPack(code){return fetch('locales/'+code+'.json',{headers:{Accept:'application/json'}}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();});}
function applyLocale(code,pack){state.locale=code;state.pack=pack;var meta=state.manifest.find(function(x){return x.code===code;})||{};document.documentElement.lang=code;document.documentElement.dir=meta.dir||'ltr';try{localStorage.setItem('fg.schoolDashboard.locale',code);}catch(e){}render();}
function changeLocale(code){if(code===state.locale)return;loadPack(code).then(function(pack){var url=new URL(location.href);url.searchParams.set('lang',code);history.replaceState(null,'',url.pathname+url.search+url.hash);applyLocale(code,pack);}).catch(function(e){console.error('[school-dashboard-demo] locale load failed',code,e);if(code!==FALLBACK)applyLocale(FALLBACK,state.fallback);});}

function storageKey(){return'fg.schoolDashboard.demo.v2.'+MODE+'.school-001.2026';}
function loadSaved(){try{return JSON.parse(localStorage.getItem(storageKey())||'{}')||{};}catch(e){return{};}}
function saveSaved(data){try{localStorage.setItem(storageKey(),JSON.stringify(data));}catch(e){}}
function actionKey(context,id){return[MODE,'school-001','2026',context,id].join('|');}
function getAction(context,id){var d=loadSaved();return(d.actions||{})[actionKey(context,id)]||'unreviewed';}
function setAction(context,id,value){var d=loadSaved();d.actions=d.actions||{};d.actions[actionKey(context,id)]=value;saveSaved(d);}
function getNote(id){var d=loadSaved();return(d.notes||{})[actionKey(state.selectedClass,id)]||'';}
function setNote(id,value){var d=loadSaved();d.notes=d.notes||{};d.notes[actionKey(state.selectedClass,id)]=value;saveSaved(d);}

function modeHref(mode){var p=mode==='homeroom'?'homeroom.html':mode==='school'?'school.html':'track.html';return p+'?lang='+encodeURIComponent(state.locale);}
function modeTitle(){return t('mode.'+MODE+'.title');}
function modeSubtitle(){return t('mode.'+MODE+'.subtitle');}
function currentScores(){if(MODE==='track')return tracks.find(function(x){return x.id===state.selectedTrack;}).s;if(MODE==='school')return classes.reduce(function(a,c){return a.map(function(v,i){return v+c.s[i];});},[0,0,0,0]).map(function(v){return v/classes.length;});return classes.find(function(x){return x.id===state.selectedClass;}).s;}
function fmt(v){return new Intl.NumberFormat(state.locale,{maximumFractionDigits:1,minimumFractionDigits:1}).format(v);}
function averageStudent(st){return domainKeys.reduce(function(n,k){return n+st.s[k];},0)/4;}

function headerHTML(){var modes=['homeroom','school','track'];return '<header class="top"><div class="top-inner"><div class="brand"><span class="mark" aria-hidden="true">KP</span><div class="brand-copy"><div class="brand-title">K-PASS Dashboard</div><div class="brand-sub">'+esc(t('app.organization'))+'</div></div></div><nav class="mode-nav" aria-label="'+esc(t('nav.dashboardTypes'))+'">'+modes.map(function(m){return'<a href="'+modeHref(m)+'"'+(m===MODE?' aria-current="page"':'')+'>'+esc(t('nav.'+m))+'</a>';}).join('')+'</nav><div class="language-control"><label for="language-select">🌐 '+esc(t('language.select'))+'</label><select id="language-select" class="language-select" aria-label="'+esc(t('language.select'))+'">'+state.manifest.map(function(x){return'<option value="'+x.code+'"'+(x.code===state.locale?' selected':'')+'>'+esc(x.label)+'</option>';}).join('')+'</select></div></div></header>';
}
function metricsHTML(){var scores=currentScores();var avg=scores.reduce(function(a,b){return a+b;},0)/4;var items=[['metric.students',MODE==='school'?93:MODE==='track'?110:24,'metric.people'],['metric.average',fmt(avg),'metric.standardScore'],['metric.priority',MODE==='school'?16:MODE==='track'?14:3,'metric.review'],['metric.completed',MODE==='school'?'96%':MODE==='track'?'95%':'96%','metric.currentCycle']];return'<section id="overview" class="summary" aria-label="'+esc(t('summary.title'))+'">'+items.map(function(x){return'<article class="metric"><div class="label">'+esc(t(x[0]))+'</div><div class="value">'+x[1]+'</div><div class="delta">'+esc(t(x[2]))+'</div></article>';}).join('')+'</section>';}
function profileHTML(){var scores=currentScores();return'<section id="profile" class="card"><div class="card-head"><div><h2>'+esc(t('profile.title'))+'</h2><p>'+esc(t('profile.help'))+'</p></div></div><div class="domain-list">'+domainKeys.map(function(k,i){var width=Math.max(4,Math.min(100,(scores[i]-60)/100*100));return'<div class="domain-row"><div class="domain-name">'+esc(t('domain.'+k))+'</div><div class="bar" role="img" aria-label="'+esc(t('profile.scoreLabel',{domain:t('domain.'+k),score:fmt(scores[i])}))+'"><span style="width:'+width+'%"></span></div><div class="score">'+fmt(scores[i])+'</div></div>';}).join('')+'</div><p class="muted">'+esc(t('profile.baseline'))+'</p></section>';}
function actionOptions(current){return['unreviewed','parent','counselor','retest','complete'].map(function(k){return'<option value="'+k+'"'+(current===k?' selected':'')+'>'+esc(t('action.'+k))+'</option>';}).join('');}
function attentionHTML(){var filtered=students.filter(function(s){return state.filter==='all'||s.tier===state.filter;});return'<section id="attention" class="card wide"><div class="card-head"><div><h2>'+esc(t('attention.title'))+'</h2><p>'+esc(t('attention.help'))+'</p></div></div><div class="filters">'+['all','priority','support','watch','growth'].map(function(k){var count=k==='all'?students.length:students.filter(function(s){return s.tier===k;}).length;return'<button class="chip" type="button" data-filter="'+k+'" aria-pressed="'+(state.filter===k)+'">'+esc(t('tier.'+k))+' '+count+'</button>';}).join('')+'</div><div class="table-wrap"><table class="table"><thead><tr><th>'+esc(t('table.student'))+'</th>'+domainKeys.map(function(k){return'<th>'+esc(t('domain.'+k))+'</th>';}).join('')+'<th>'+esc(t('table.reason'))+'</th><th>'+esc(t('table.action'))+'</th></tr></thead><tbody>'+filtered.map(function(s){return'<tr><td><button class="student-btn" type="button" data-student="'+s.id+'">'+s.id+'</button></td>'+domainKeys.map(function(k){return'<td>'+s.s[k]+'</td>';}).join('')+'<td><span class="tag '+(s.tier==='priority'?'danger':s.tier==='support'?'warn':'')+'">'+esc(t('tier.'+s.tier))+'</span></td><td><select class="control action-select" data-context="'+state.selectedClass+'" data-id="'+s.id+'" aria-label="'+esc(t('table.actionFor',{student:s.id}))+'">'+actionOptions(getAction(state.selectedClass,s.id))+'</select></td></tr>';}).join('')+'</tbody></table></div></section>';}
function studentHTML(){var st=students.find(function(x){return x.id===state.selectedStudent;})||students[0];var best=domainKeys.slice().sort(function(a,b){return st.s[b]-st.s[a];})[0];var low=domainKeys.slice().sort(function(a,b){return st.s[a]-st.s[b];})[0];return'<section id="student" class="card"><div class="card-head"><div><h2>'+esc(t('student.title'))+'</h2><p>'+esc(t('student.help'))+'</p></div></div><div class="student-grid"><div class="student-list">'+students.map(function(s){return'<button type="button" class="student-btn" data-student="'+s.id+'" aria-current="'+(s.id===st.id)+'"><strong>'+s.id+'</strong><br><span class="muted">'+esc(t('student.age',{age:s.age}))+'</span></button>';}).join('')+'</div><div><div class="notice">'+esc(t('student.summary',{student:st.id,best:t('domain.'+best),bestScore:st.s[best],low:t('domain.'+low),lowScore:st.s[low]}))+'</div><h3>'+esc(t('student.note'))+'</h3><textarea class="note" id="student-note" aria-label="'+esc(t('student.note'))+'" placeholder="'+esc(t('student.notePlaceholder'))+'">'+esc(getNote(st.id))+'</textarea><div class="row"><button class="btn" type="button" id="save-note">'+esc(t('common.save'))+'</button><span class="status" id="note-status" aria-live="polite"></span></div></div></div></section>';}
function homeroomExtra(){return studentHTML()+'<section id="guardian" class="card"><h2>'+esc(t('homeroom.parentTitle'))+'</h2><p class="muted">'+esc(t('homeroom.parentHelp'))+'</p><div class="notice warn">'+esc(t('homeroom.parentMessage'))+'</div><h3>'+esc(t('homeroom.pairTitle'))+'</h3><p>'+esc(t('homeroom.pairMessage'))+'</p></section>';}
function schoolExtra(){var groups=[[],[],[]];students.slice().sort(function(a,b){return averageStudent(b)-averageStudent(a);}).forEach(function(s,i){groups[i%3].push(s);});return'<section id="comparison" class="card wide"><div class="card-head"><div><h2>'+esc(t('school.compareTitle'))+'</h2><p>'+esc(t('school.compareHelp'))+'</p></div></div><div class="compare"><div class="compare-row compare-head"><strong>'+esc(t('school.class'))+'</strong>'+domainKeys.map(function(k){return'<span class="mini">'+esc(t('domain.'+k))+'</span>';}).join('')+'<span class="mini">'+esc(t('metric.completed'))+'</span></div>'+classes.map(function(c){return'<button class="compare-row" type="button" data-class="'+c.id+'"><strong>'+esc(c.name)+'</strong>'+c.s.map(function(v){return'<span class="mini">'+fmt(v)+'</span>';}).join('')+'<span class="mini">'+c.completion+'%</span></button>';}).join('')+'</div></section><section id="formation" class="card wide"><div class="card-head"><div><h2>'+esc(t('school.formationTitle'))+'</h2><p>'+esc(t('school.formationHelp'))+'</p></div><button class="btn secondary" id="rebalance" type="button">'+esc(t('school.rebalance'))+'</button></div><div class="formation">'+groups.map(function(g,i){return'<div class="group"><h3>'+esc(t('school.group',{number:i+1}))+'</h3>'+g.map(function(s){return'<div class="person"><span>'+s.id+'</span><strong>'+fmt(averageStudent(s))+'</strong></div>';}).join('')+'</div>';}).join('')+'</div><p class="muted">'+esc(t('school.formationNotice'))+'</p></section>';}
function trackExtra(){var tr=tracks.find(function(x){return x.id===state.selectedTrack;});return'<section id="track-choice" class="card wide"><div class="card-head"><div><h2>'+esc(t('track.compareTitle'))+'</h2><p>'+esc(t('track.compareHelp'))+'</p></div><select id="track-select" class="control" aria-label="'+esc(t('track.select'))+'">'+tracks.map(function(x){return'<option value="'+x.id+'"'+(x.id===tr.id?' selected':'')+'>'+esc(x.name)+'</option>';}).join('')+'</select></div></section><section id="recommendations" class="card wide"><div class="card-head"><div><h2>'+esc(t('track.recommendTitle'))+'</h2><p>'+esc(t('track.recommendHelp'))+'</p></div></div><div class="recs"><div class="rec"><h3>'+esc(t('track.careers'))+'</h3><ul><li>'+esc(t('track.career1'))+'</li><li>'+esc(t('track.career2'))+'</li><li>'+esc(t('track.career3'))+'</li></ul></div><div class="rec"><h3>'+esc(t('track.subjects'))+'</h3><ul><li>'+esc(t('track.subject1'))+'</li><li>'+esc(t('track.subject2'))+'</li><li>'+esc(t('track.subject3'))+'</li></ul></div><div class="rec"><h3>'+esc(t('track.record'))+'</h3><ul><li>'+esc(t('track.record1'))+'</li><li>'+esc(t('track.record2'))+'</li><li>'+esc(t('track.record3'))+'</li></ul></div></div><p class="notice warn">'+esc(t('track.notice'))+'</p></section>';}
function tocHTML(){var common=[['overview','summary.title'],['profile','profile.title']],extra=MODE==='homeroom'?[['student','student.title'],['guardian','homeroom.parentTitle']]:MODE==='school'?[['comparison','school.compareTitle'],['formation','school.formationTitle']]:[['track-choice','track.compareTitle'],['recommendations','track.recommendTitle']];return'<aside class="toc" aria-label="'+esc(t('nav.contents'))+'"><div class="toc-title">'+esc(t('nav.contents'))+'</div>'+common.concat(extra,[['attention','attention.title']]).map(function(x,i){return'<a href="#'+x[0]+'" data-toc="'+x[0]+'" aria-current="'+(i===0)+'">'+esc(t(x[1]))+'</a>';}).join('')+'</aside>';}
function setupTocSpy(){if(!('IntersectionObserver'in window))return;var links={};document.querySelectorAll('[data-toc]').forEach(function(a){links[a.dataset.toc]=a;});var io=new IntersectionObserver(function(entries){entries.filter(function(e){return e.isIntersecting;}).forEach(function(e){Object.keys(links).forEach(function(k){links[k].setAttribute('aria-current',String(k===e.target.id));});});},{rootMargin:'-18% 0px -70% 0px'});Object.keys(links).forEach(function(id){var el=document.getElementById(id);if(el)io.observe(el);});}
function render(){document.title=t('mode.'+MODE+'.title')+' · K-PASS';var extra=MODE==='homeroom'?homeroomExtra():MODE==='school'?schoolExtra():trackExtra();document.getElementById('app').innerHTML='<a class="skip-link" href="#main">'+esc(t('common.skip'))+'</a>'+headerHTML()+'<main id="main" class="layout"><div class="page-shell">'+tocHTML()+'<div class="page-content"><section class="hero"><div><div class="eyebrow">'+esc(t('app.eyebrow'))+'</div><h1>'+esc(modeTitle())+'</h1><p>'+esc(modeSubtitle())+'</p></div><div class="demo-pill">'+esc(t('app.demo'))+'</div></section>'+metricsHTML()+'<div class="grid">'+profileHTML()+extra+attentionHTML()+'</div></div></div></main><footer class="footer">'+esc(t('app.disclaimer'))+'</footer>';setupTocSpy();}

document.addEventListener('click',function(e){var lang=e.target.closest('[data-lang]');if(lang){changeLocale(lang.dataset.lang);return;}var filter=e.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;render();return;}var student=e.target.closest('[data-student]');if(student){state.selectedStudent=student.dataset.student;render();return;}var cls=e.target.closest('[data-class]');if(cls){state.selectedClass=cls.dataset.class;render();return;}if(e.target.id==='save-note'){setNote(state.selectedStudent,document.getElementById('student-note').value);document.getElementById('note-status').textContent=t('common.saved');return;}if(e.target.id==='rebalance'){state.formationVersion++;students.push(students.shift());render();}});
document.addEventListener('change',function(e){if(e.target.id==='language-select'){changeLocale(e.target.value);return;}if(e.target.classList.contains('action-select')){setAction(e.target.dataset.context,e.target.dataset.id,e.target.value);return;}if(e.target.id==='track-select'){state.selectedTrack=e.target.value;render();}});

Promise.all([fetch('locales/manifest.json').then(function(r){return r.json();}),loadPack(FALLBACK)]).then(function(values){state.manifest=values[0];state.fallback=values[1];var locale=resolveLocale();return locale===FALLBACK?applyLocale(locale,state.fallback):loadPack(locale).then(function(pack){applyLocale(locale,pack);}).catch(function(){applyLocale(FALLBACK,state.fallback);});}).catch(function(e){console.error('[school-dashboard-demo] startup failed',e);document.getElementById('app').textContent='K-PASS Dashboard';});
})();
