import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'locales');
const ko={
  'app.organization':'필굿 미래교육연구소','app.eyebrow':'학교 인지성장 지원','app.demo':'예시 데이터 · 데모','app.disclaimer':'이 화면은 교육적 선별과 지원 계획을 돕는 자료이며 진단이 아닙니다. 중요한 결정은 검사 원자료와 추가 평가를 함께 검토해 주세요.',
  'nav.dashboardTypes':'대시보드 유형','nav.contents':'목차','nav.homeroom':'우리 반','nav.school':'학교 전체','nav.track':'학과별','language.select':'언어 선택',
  'mode.homeroom.title':'우리 반 성장 대시보드','mode.homeroom.subtitle':'학생별 강점과 지원 필요를 빠르게 확인하고 상담 기록을 한 흐름에서 관리합니다.',
  'mode.school.title':'학교 전체 대시보드','mode.school.subtitle':'학급 간 차이, 검사 완료율과 지원 수요를 비교하고 검토 가능한 편성 초안을 만듭니다.',
  'mode.track.title':'학과별 인지 대시보드','mode.track.subtitle':'현재 학과 학생의 인지특성과 지원 수요를 비교하고 직무·진로 탐색에 참고합니다.',
  'summary.title':'핵심 지표','metric.students':'학생','metric.people':'명','metric.average':'평균 표준점수','metric.standardScore':'네 영역 평균','metric.priority':'우선 검토','metric.review':'추가 확인 권장','metric.completed':'검사 완료율','metric.currentCycle':'현재 회차',
  'profile.title':'PASS 네 영역 프로파일','profile.help':'규준 평균 100을 기준으로 집단의 상대적 경향을 봅니다.','profile.scoreLabel':'{domain} 평균 {score}','profile.baseline':'세로 기준선은 규준 평균 100입니다. 한 번의 점수만으로 개인을 판단하지 않습니다.',
  'domain.planning':'계획력','domain.attention':'주의력','domain.simultaneous':'동시처리','domain.sequential':'순차처리',
  'attention.title':'지원 검토 목록','attention.help':'우선순위와 현재 조치 상태를 함께 확인합니다. 필터는 진단이 아닌 검토 보조 기준입니다.',
  'tier.all':'전체','tier.priority':'우선 검토','tier.support':'지원 필요','tier.watch':'관찰','tier.growth':'강점 확장',
  'table.student':'학생','table.reason':'검토 이유','table.action':'조치 상태','table.actionFor':'{student} 조치 상태',
  'action.unreviewed':'확인 전','action.parent':'보호자 안내','action.counselor':'상담 연계','action.retest':'재검사 예정','action.complete':'조치 완료',
  'student.title':'학생 카드와 상담 기록','student.help':'학생을 선택하면 강점·보완 영역과 저장된 기록을 확인합니다.','student.age':'{age}세','student.summary':'{student} 학생은 {best} {bestScore}점이 상대 강점이고 {low} {lowScore}점은 함께 지원할 영역입니다.','student.note':'상담·관찰 기록','student.notePlaceholder':'상담 내용, 수업 관찰, 가정 연계 사항을 기록하세요.','common.save':'저장','common.saved':'저장되었습니다.','common.skip':'본문으로 건너뛰기',
  'homeroom.parentTitle':'보호자 상담 가이드','homeroom.parentHelp':'점수보다 관찰 사실과 다음 지원 행동을 중심으로 설명합니다.','homeroom.parentMessage':'강점을 먼저 설명하고, 보완 영역은 비교나 낙인 없이 연습 가능한 성장 목표로 안내하세요.','homeroom.pairTitle':'짝·모둠 제안','homeroom.pairMessage':'인지 점수만으로 편성을 확정하지 말고 관계, 생활 특성, 교사의 관찰을 함께 검토하세요.',
  'school.compareTitle':'학급 비교','school.compareHelp':'학급 평균과 검사 완료율을 같은 기준으로 비교합니다.','school.class':'학급','school.formationTitle':'편성 초안','school.formationHelp':'지원 필요 학생과 평균이 한 반에 몰리지 않도록 만든 검토용 초안입니다.','school.rebalance':'다시 배치','school.group':'{number}반','school.formationNotice':'자동 편성은 확정 결과가 아닙니다. 교우 관계, 생활지도와 학생 보호 요소를 검토한 뒤 승인하세요.',
  'track.compareTitle':'계열 선택','track.compareHelp':'계열별 집단 평균을 바꾸어 비교합니다.','track.select':'계열 선택','track.recommendTitle':'진로·과목·학교생활기록 제안','track.recommendHelp':'집단 경향을 바탕으로 만든 수업·상담 초안이며 개인 진단이 아닙니다.','track.careers':'추천 진로·직무군','track.career1':'기획·프로젝트 운영','track.career2':'데이터 기반 문제 해결','track.career3':'공공·조직 커뮤니케이션','track.subjects':'추천 선택과목','track.subject1':'확률과 통계','track.subject2':'사회문제 탐구','track.subject3':'정보·인공지능 기초','track.record':'학교생활기록 활동 아이디어','track.record1':'자료 조사 후 근거 기반 제안 발표','track.record2':'팀 프로젝트에서 계획과 점검 역할 수행','track.record3':'관심 직무 인터뷰와 성찰 기록','track.notice':'실제 학교생활기록은 학생이 수행한 사실과 교사의 관찰에 근거해 작성해야 합니다.'
};

const en={
  'app.organization':'FeelGood Future Education Lab','app.eyebrow':'School cognitive growth support','app.demo':'Sample data · Demo','app.disclaimer':'This dashboard supports educational screening and planning; it is not a diagnosis. Review source results and additional evidence before important decisions.',
  'nav.dashboardTypes':'Dashboard types','nav.contents':'Contents','nav.homeroom':'Homeroom','nav.school':'Whole school','nav.track':'Departments','language.select':'Select language',
  'mode.homeroom.title':'Homeroom Growth Dashboard','mode.homeroom.subtitle':'Review each learner’s strengths, support needs, and consultation notes in one workflow.','mode.school.title':'Whole-School Dashboard','mode.school.subtitle':'Compare classes, completion, and support demand, then prepare a reviewable placement draft.','mode.track.title':'Department Cognitive Dashboard','mode.track.subtitle':'Compare cognitive characteristics and support needs within the current department and inform career exploration.',
  'summary.title':'Key metrics','metric.students':'Students','metric.people':'people','metric.average':'Mean standard score','metric.standardScore':'Four-domain mean','metric.priority':'Priority review','metric.review':'Additional review advised','metric.completed':'Assessment completion','metric.currentCycle':'Current cycle',
  'profile.title':'PASS four-domain profile','profile.help':'View group tendencies against the normative mean of 100.','profile.scoreLabel':'{domain} mean {score}','profile.baseline':'The vertical marker is the normative mean of 100. Do not judge a learner from one score.',
  'domain.planning':'Planning','domain.attention':'Attention','domain.simultaneous':'Simultaneous','domain.sequential':'Sequential',
  'attention.title':'Support review list','attention.help':'Review priority and current action together. Filters support review and are not diagnoses.','tier.all':'All','tier.priority':'Priority review','tier.support':'Support needed','tier.watch':'Observe','tier.growth':'Extend strength',
  'table.student':'Student','table.reason':'Review reason','table.action':'Action status','table.actionFor':'Action status for {student}','action.unreviewed':'Not reviewed','action.parent':'Inform guardian','action.counselor':'Counselor referral','action.retest':'Retest planned','action.complete':'Completed',
  'student.title':'Student card and notes','student.help':'Select a learner to review strengths, support areas, and saved notes.','student.age':'Age {age}','student.summary':'{student} shows a relative strength in {best} ({bestScore}); {low} ({lowScore}) is an area to support.','student.note':'Consultation and observation notes','student.notePlaceholder':'Record consultation, classroom observations, and home-school follow-up.','common.save':'Save','common.saved':'Saved.','common.skip':'Skip to main content',
  'homeroom.parentTitle':'Guardian consultation guide','homeroom.parentHelp':'Lead with observed facts and next support actions rather than scores.','homeroom.parentMessage':'Start with strengths and present support areas as growth goals without comparison or labels.','homeroom.pairTitle':'Pair and group suggestion','homeroom.pairMessage':'Do not finalize grouping from cognitive scores alone; include relationships, behavior, and teacher observation.',
  'school.compareTitle':'Class comparison','school.compareHelp':'Compare class means and completion on the same basis.','school.class':'Class','school.formationTitle':'Placement draft','school.formationHelp':'A review draft that distributes support needs and class means.','school.rebalance':'Rebalance','school.group':'Class {number}','school.formationNotice':'Automated placement is not final. Review peer relationships, pastoral needs, and safeguarding factors before approval.',
  'track.compareTitle':'Select career track','track.compareHelp':'Switch tracks to compare group means.','track.select':'Select track','track.recommendTitle':'Career, subject, and school-record suggestions','track.recommendHelp':'A teaching and counseling draft based on group tendencies, not an individual diagnosis.','track.careers':'Suggested career families','track.career1':'Planning and project operations','track.career2':'Data-informed problem solving','track.career3':'Public and organizational communication','track.subjects':'Suggested electives','track.subject1':'Probability and statistics','track.subject2':'Social issue inquiry','track.subject3':'Information and AI foundations','track.record':'School-record activity ideas','track.record1':'Research and present an evidence-based proposal','track.record2':'Plan and monitor progress in a team project','track.record3':'Interview a professional and write a reflection','track.notice':'Official school records must be based on activities actually completed and teacher observation.'
};

Object.assign(ko,{
  'track.students.title':'학과 학생 비교','track.students.lead':'현재 학과 학생의 네 영역 점수와 지원 등급, 인지특성을 익명 ID 기준으로 비교해요.',
  'track.career.title':'학생별 추천 직무·진로군 Top 5','track.career.lead':'학생을 선택하면 현재 학과의 직무 후보군을 인지특성과 연결해 상위 5개 탐색 순위로 보여줘요.',
  'career.empty':'이 학과에는 아직 준비된 직무 후보군이 없어요. 관리자에게 직무 라이브러리 등록을 요청하세요.','career.student':'학생','career.selectAria':'진로 추천 학생 선택','career.top5':'{student} 추천 직무·진로군 Top 5','career.rank':'순위','career.job':'직무·진로군','career.strengths':'연결된 인지 강점','career.uses':'{strengths} 활용',
  'career.counsel.title':'진로 상담','career.counsel.start':'탐색 출발점: {strengths} 강점이 실제 활동에서 어떻게 나타났는지 확인해요.','career.counsel.experience':'경험 질문: {prompt}을 구체적으로 물어보세요.','career.counsel.job':'직무 확인: 1순위 {job}을 포함한 Top 5 중 관심 직무를 고르고, 실제 업무·필요 역량·근무 환경을 조사하게 해요.','career.counsel.decision':'결정 전 확인: 인지특성뿐 아니라 흥미, 가치관, 교과 경험, 생활 여건과 학생의 희망을 함께 봐요.',
  'career.essay.title':'학생별 자기소개서 상담','career.essay.situation':'상황·과제: {prompt}을 소재 후보로 찾습니다.','career.essay.action':'행동: 본인이 맡은 역할, 판단, 실행 순서를 사실 중심으로 확인합니다.','career.essay.result':'결과·근거: 결과와 주변 피드백, 배운 점을 구체적인 근거로 정리합니다.','career.essay.link':'진로 연결: {job} 탐색 과정과 앞으로 보완할 역량을 연결합니다.','career.essay.notice':'PASS 점수나 유형명을 자기소개서에 직접 쓰지 말고, 학생이 실제로 수행한 경험과 본인의 표현만 사용하세요.',
  'career.note.title':'진로·자기소개서 상담 기록','career.note.help':'관심 직무, 확인한 실제 경험, 다음 탐색 행동을 기록하세요. 이 브라우저에만 저장됩니다.','career.note.aria':'진로·자기소개서 상담 기록','career.note.placeholder':'예: 관심 직무, 학생이 직접 설명한 경험, 추가로 확인할 자료와 다음 행동','career.disclaimer':'현재 학과의 직무 후보군을 PASS 네 영역 가중치로 정렬한 탐색용 결과예요. 적성검사나 진로 진단이 아니며, 흥미·가치관·경험·희망과 실제 직무 정보를 함께 검토하세요.',
  'career.prompt.PLAN':'목표를 세우고 역할·일정을 조정해 끝까지 실행한 경험','career.prompt.ATT':'작은 오류나 변화를 발견하고 집중해서 품질을 높인 경험','career.prompt.SIM':'여러 자료를 연결해 전체 구조나 새로운 해결책을 만든 경험','career.prompt.SUC':'복잡한 절차를 순서대로 정리하거나 정확하게 설명한 경험',
  'career.job.ict.data':'데이터 분석가','career.job.ict.software':'SW 개발자','career.job.ict.robotics':'AI·로봇 엔지니어','career.job.ict.security':'정보보안 전문가','career.job.ict.ux':'UX 기술 디자이너','career.job.ict.cloud':'클라우드 엔지니어','career.job.ict.product':'디지털 제품기획자','career.job.ict.qa':'QA 자동화 엔지니어',
  'career.job.art.content':'콘텐츠 기획자','career.job.art.media':'영상·미디어 디자이너','career.job.art.ux':'UX 디자이너','career.job.art.exhibition':'공연·전시 기획자','career.job.art.brand':'브랜드 마케터','career.job.art.editor':'영상 편집자','career.job.art.curator':'문화예술 큐레이터','career.job.art.game':'게임 아티스트',
  'career.job.biz.strategy':'경영·전략기획자','career.job.biz.public':'공공행정 전문가','career.job.biz.finance':'회계·재무 전문가','career.job.biz.startup':'창업·서비스 기획자','career.job.biz.policy':'정책 분석가','career.job.biz.hr':'인사·조직 전문가','career.job.biz.market':'시장조사 분석가','career.job.biz.operations':'물류·운영 관리자',
  'career.job.med.nursing':'간호·보건 전문가','career.job.med.lab':'임상병리 전문가','career.job.med.rehab':'재활치료 전문가','career.job.med.policy':'보건정책 전문가','career.job.med.data':'의료데이터 관리자','career.job.med.emergency':'응급·안전 전문가','career.job.med.device':'의료기기 연구원','career.job.med.public':'공중보건 연구원',
  'career.job.edu.teacher':'교사·교육 전문가','career.job.edu.counsel':'상담·복지 전문가','career.job.edu.lifelong':'평생교육 기획자','career.job.edu.content':'교육 콘텐츠 개발자','career.job.edu.social':'사회복지사','career.job.edu.assessment':'교육평가 연구원','career.job.edu.career':'진로교육 전문가','career.job.edu.edtech':'에듀테크 기획자'
});
Object.assign(en,{
  'track.students.title':'Department student comparison','track.students.lead':'Compare four-domain scores, support tiers, and cognitive characteristics using anonymous student IDs within the current department.',
  'track.career.title':'Student career Top 5','track.career.lead':'Select a student to rank five career directions from the current department’s career library using cognitive characteristics as one input.',
  'career.empty':'No career library is registered for this department yet. Ask an administrator to add one.','career.student':'Student','career.selectAria':'Select student for career suggestions','career.top5':'Top 5 career directions for {student}','career.rank':'Rank','career.job':'Career direction','career.strengths':'Linked cognitive strengths','career.uses':'Uses {strengths}',
  'career.counsel.title':'Career counseling','career.counsel.start':'Starting point: Check how the student has demonstrated strengths in {strengths} through real activities.','career.counsel.experience':'Experience prompt: Ask for a concrete example of {prompt}.','career.counsel.job':'Career check: Choose an interesting direction from the Top 5, including {job}, and research its tasks, required capabilities, and work environment.','career.counsel.decision':'Before deciding: Consider interests, values, subject experiences, circumstances, and the student’s own aspirations as well as cognitive characteristics.',
  'career.essay.title':'Personal-statement counseling','career.essay.situation':'Situation and task: Look for an experience involving {prompt}.','career.essay.action':'Action: Verify the student’s own role, decisions, and sequence of actions using facts.','career.essay.result':'Result and evidence: Organize the outcome, feedback, learning, and specific evidence.','career.essay.link':'Career link: Connect the exploration of {job} with capabilities the student wants to develop next.','career.essay.notice':'Do not put PASS scores or profile labels in a personal statement. Use only experiences the student actually completed and the student’s own words.',
  'career.note.title':'Career and personal-statement counseling notes','career.note.help':'Record career interests, verified experiences, and the next exploration step. Notes are stored only in this browser.','career.note.aria':'Career and personal-statement counseling notes','career.note.placeholder':'Example: career interest, experience described by the student, evidence to verify, and next action','career.disclaimer':'This exploratory ranking applies PASS-domain weights to the current department’s career library. It is not an aptitude test or career diagnosis; review interests, values, experience, aspirations, and real occupational information together.',
  'career.prompt.PLAN':'setting a goal, coordinating roles and schedules, and following through','career.prompt.ATT':'spotting a small error or change and improving quality through sustained attention','career.prompt.SIM':'connecting several sources to form an overall structure or a new solution','career.prompt.SUC':'organizing a complex procedure in order or explaining it accurately',
  'career.job.ict.data':'Data analyst','career.job.ict.software':'Software developer','career.job.ict.robotics':'AI and robotics engineer','career.job.ict.security':'Cybersecurity specialist','career.job.ict.ux':'Technology UX designer','career.job.ict.cloud':'Cloud engineer','career.job.ict.product':'Digital product planner','career.job.ict.qa':'QA automation engineer',
  'career.job.art.content':'Content planner','career.job.art.media':'Video and media designer','career.job.art.ux':'UX designer','career.job.art.exhibition':'Performance and exhibition planner','career.job.art.brand':'Brand marketer','career.job.art.editor':'Video editor','career.job.art.curator':'Arts and culture curator','career.job.art.game':'Game artist',
  'career.job.biz.strategy':'Business strategy planner','career.job.biz.public':'Public administration specialist','career.job.biz.finance':'Accounting and finance specialist','career.job.biz.startup':'Startup and service planner','career.job.biz.policy':'Policy analyst','career.job.biz.hr':'Human resources specialist','career.job.biz.market':'Market research analyst','career.job.biz.operations':'Logistics and operations manager',
  'career.job.med.nursing':'Nursing and health professional','career.job.med.lab':'Clinical laboratory specialist','career.job.med.rehab':'Rehabilitation therapist','career.job.med.policy':'Health policy specialist','career.job.med.data':'Health data manager','career.job.med.emergency':'Emergency and safety specialist','career.job.med.device':'Medical device researcher','career.job.med.public':'Public health researcher',
  'career.job.edu.teacher':'Teacher and education professional','career.job.edu.counsel':'Counseling and welfare professional','career.job.edu.lifelong':'Lifelong education planner','career.job.edu.content':'Educational content developer','career.job.edu.social':'Social worker','career.job.edu.assessment':'Educational assessment researcher','career.job.edu.career':'Career education specialist','career.job.edu.edtech':'EdTech product planner'
});

const core={
  ja:['フィールグッド未来教育研究所','学校認知成長支援','サンプルデータ・デモ','学級','学校全体','進路系列','言語を選択','学級成長ダッシュボード','学校全体ダッシュボード','系列別進路ダッシュボード','生徒','平均標準得点','優先確認','検査完了率','計画力','注意力','同時処理','継次処理','全体','支援が必要','観察','強みを伸ばす','未確認','保護者へ案内','相談連携','再検査予定','対応完了','保存','保存しました。'],
  'zh-CN':['FeelGood未来教育研究所','学校认知成长支持','示例数据·演示','班级','全校','生涯方向','选择语言','班级成长仪表板','全校仪表板','方向生涯仪表板','学生','平均标准分','优先复核','测评完成率','计划能力','注意能力','同时性加工','继时性加工','全部','需要支持','持续观察','拓展优势','尚未复核','通知监护人','转介咨询','计划复测','处理完成','保存','已保存。'],
  'zh-TW':['FeelGood未來教育研究所','學校認知成長支持','範例資料·展示','班級','全校','生涯群組','選擇語言','班級成長儀表板','全校儀表板','群組生涯儀表板','學生','平均標準分數','優先檢視','測驗完成率','計畫能力','注意能力','同時性處理','序列性處理','全部','需要支持','持續觀察','延伸優勢','尚未檢視','通知家長','轉介輔導','預計複測','處理完成','儲存','已儲存。'],
  es:['Laboratorio FeelGood de Educación Futura','Apoyo al crecimiento cognitivo escolar','Datos de ejemplo · Demo','Grupo','Toda la escuela','Itinerarios','Seleccionar idioma','Panel de crecimiento del grupo','Panel de toda la escuela','Panel de itinerarios profesionales','Estudiantes','Puntuación estándar media','Revisión prioritaria','Evaluaciones completadas','Planificación','Atención','Procesamiento simultáneo','Procesamiento secuencial','Todo','Necesita apoyo','Observar','Ampliar fortalezas','Sin revisar','Informar a la familia','Derivar a orientación','Reevaluación prevista','Completado','Guardar','Guardado.'],
  fr:['Laboratoire FeelGood pour l’éducation future','Soutien à la croissance cognitive scolaire','Données exemples · Démo','Classe','École entière','Parcours','Choisir la langue','Tableau de progression de la classe','Tableau de bord de l’école','Tableau des parcours professionnels','Élèves','Score standard moyen','Examen prioritaire','Évaluations terminées','Planification','Attention','Traitement simultané','Traitement séquentiel','Tous','Soutien nécessaire','Observer','Développer les forces','Non examiné','Informer la famille','Orientation vers le conseil','Réévaluation prévue','Terminé','Enregistrer','Enregistré.'],
  ru:['Лаборатория образования будущего FeelGood','Поддержка когнитивного развития в школе','Пример данных · Демо','Класс','Вся школа','Профильные направления','Выбор языка','Панель развития класса','Общешкольная панель','Панель карьерных направлений','Ученики','Средний стандартный балл','Приоритетная проверка','Завершение обследования','Планирование','Внимание','Одновременная обработка','Последовательная обработка','Все','Нужна поддержка','Наблюдение','Развитие сильных сторон','Не проверено','Сообщить семье','Направить к консультанту','Запланирована повторная оценка','Завершено','Сохранить','Сохранено.'],
  vi:['Phòng nghiên cứu Giáo dục Tương lai FeelGood','Hỗ trợ phát triển nhận thức học đường','Dữ liệu mẫu · Bản demo','Lớp chủ nhiệm','Toàn trường','Nhóm định hướng','Chọn ngôn ngữ','Bảng tăng trưởng lớp học','Bảng điều khiển toàn trường','Bảng định hướng nghề nghiệp','Học sinh','Điểm chuẩn trung bình','Ưu tiên xem xét','Hoàn thành đánh giá','Lập kế hoạch','Chú ý','Xử lý đồng thời','Xử lý tuần tự','Tất cả','Cần hỗ trợ','Theo dõi','Phát triển điểm mạnh','Chưa xem xét','Thông báo gia đình','Kết nối tư vấn','Dự kiến đánh giá lại','Hoàn tất','Lưu','Đã lưu.'],
  th:['สถาบันการศึกษาอนาคต FeelGood','สนับสนุนการเติบโตด้านการรู้คิดในโรงเรียน','ข้อมูลตัวอย่าง · เดโม','ชั้นเรียน','ทั้งโรงเรียน','สายอาชีพ','เลือกภาษา','แดชบอร์ดพัฒนาการชั้นเรียน','แดชบอร์ดทั้งโรงเรียน','แดชบอร์ดสายอาชีพ','นักเรียน','คะแนนมาตรฐานเฉลี่ย','ทบทวนเร่งด่วน','การประเมินเสร็จสิ้น','การวางแผน','ความสนใจ','การประมวลผลพร้อมกัน','การประมวลผลตามลำดับ','ทั้งหมด','ต้องการการสนับสนุน','ติดตาม','ต่อยอดจุดแข็ง','ยังไม่ตรวจ','แจ้งผู้ปกครอง','ส่งต่อการปรึกษา','วางแผนประเมินซ้ำ','เสร็จสิ้น','บันทึก','บันทึกแล้ว'],
  ar:['مختبر فيل غود لتعليم المستقبل','دعم النمو المعرفي المدرسي','بيانات نموذجية · عرض','الصف','المدرسة كاملة','المسارات المهنية','اختيار اللغة','لوحة نمو الصف','لوحة المدرسة كاملة','لوحة المسارات المهنية','الطلاب','متوسط الدرجة المعيارية','مراجعة ذات أولوية','اكتمال التقييم','التخطيط','الانتباه','المعالجة المتزامنة','المعالجة المتتابعة','الكل','بحاجة إلى دعم','ملاحظة','تنمية نقاط القوة','لم تتم المراجعة','إبلاغ ولي الأمر','إحالة إلى الإرشاد','إعادة تقييم مخطط لها','مكتمل','حفظ','تم الحفظ.'],
  it:['Laboratorio FeelGood per l’Educazione Futura','Supporto alla crescita cognitiva scolastica','Dati di esempio · Demo','Classe','Intera scuola','Percorsi','Seleziona lingua','Dashboard di crescita della classe','Dashboard dell’intera scuola','Dashboard dei percorsi professionali','Studenti','Punteggio standard medio','Revisione prioritaria','Valutazioni completate','Pianificazione','Attenzione','Elaborazione simultanea','Elaborazione sequenziale','Tutti','Supporto necessario','Osservare','Sviluppare i punti di forza','Non esaminato','Informare la famiglia','Invio alla consulenza','Rivalutazione prevista','Completato','Salva','Salvato.'],
  az:['FeelGood Gələcək Təhsil Laboratoriyası','Məktəbdə koqnitiv inkişaf dəstəyi','Nümunə məlumat · Demo','Sinif','Bütün məktəb','Karyera istiqamətləri','Dil seçin','Sinif inkişaf paneli','Ümumməktəb paneli','Karyera istiqamətləri paneli','Şagirdlər','Orta standart bal','Prioritet baxış','Qiymətləndirmənin tamamlanması','Planlaşdırma','Diqqət','Eyni vaxtlı emal','Ardıcıl emal','Hamısı','Dəstək lazımdır','Müşahidə','Güclü tərəfi inkişaf etdir','Baxılmayıb','Ailəyə məlumat ver','Məsləhətə yönləndir','Təkrar qiymətləndirmə planlanıb','Tamamlandı','Yadda saxla','Yadda saxlanıldı.'],
  mn:['FeelGood Ирээдүйн боловсролын лаборатори','Сургуулийн танин мэдэхүйн өсөлтийн дэмжлэг','Жишээ өгөгдөл · Демо','Анги','Бүх сургууль','Мэргэжлийн чиглэл','Хэл сонгох','Ангийн өсөлтийн самбар','Сургуулийн нэгдсэн самбар','Мэргэжлийн чиглэлийн самбар','Сурагчид','Дундаж стандарт оноо','Нэн тэргүүний хяналт','Үнэлгээний гүйцэтгэл','Төлөвлөлт','Анхаарал','Зэрэгцээ боловсруулалт','Дараалсан боловсруулалт','Бүгд','Дэмжлэг хэрэгтэй','Ажиглах','Давуу талыг хөгжүүлэх','Хянаагүй','Гэр бүлд мэдээлэх','Зөвлөгөөнд холбох','Дахин үнэлэхээр төлөвлөсөн','Дууссан','Хадгалах','Хадгаллаа.'],
  km:['មន្ទីរពិសោធន៍អប់រំអនាគត FeelGood','ការគាំទ្រការលូតលាស់ការយល់ដឹងនៅសាលា','ទិន្នន័យគំរូ · ដេមូ','ថ្នាក់','សាលាទាំងមូល','ក្រុមអាជីព','ជ្រើសភាសា','ផ្ទាំងការលូតលាស់ថ្នាក់','ផ្ទាំងសាលាទាំងមូល','ផ្ទាំងទិសដៅអាជីព','សិស្ស','ពិន្ទុស្តង់ដារមធ្យម','ពិនិត្យអាទិភាព','ការវាយតម្លៃបានបញ្ចប់','ការធ្វើផែនការ','ការយកចិត្តទុកដាក់','ដំណើរការព្រមគ្នា','ដំណើរការតាមលំដាប់','ទាំងអស់','ត្រូវការគាំទ្រ','តាមដាន','ពង្រីកចំណុចខ្លាំង','មិនទាន់ពិនិត្យ','ជូនដំណឹងអាណាព្យាបាល','បញ្ជូនទៅប្រឹក្សា','គ្រោងវាយតម្លៃឡើងវិញ','បានបញ្ចប់','រក្សាទុក','បានរក្សាទុក។']
};
const coreKeys=['app.organization','app.eyebrow','app.demo','nav.homeroom','nav.school','nav.track','language.select','mode.homeroom.title','mode.school.title','mode.track.title','metric.students','metric.average','metric.priority','metric.completed','domain.planning','domain.attention','domain.simultaneous','domain.sequential','tier.all','tier.support','tier.watch','tier.growth','action.unreviewed','action.parent','action.counselor','action.retest','action.complete','common.save','common.saved'];
const labels={ko:'한국어',en:'English',ja:'日本語','zh-CN':'简体中文','zh-TW':'繁體中文',es:'Español',fr:'Français',ru:'Русский',vi:'Tiếng Việt',th:'ไทย',ar:'العربية',it:'Italiano',az:'Azərbaycan',mn:'Монгол',km:'ខ្មែរ'};
const contentsLabels={ja:'目次','zh-CN':'目录','zh-TW':'目錄',es:'Índice',fr:'Sommaire',ru:'Содержание',vi:'Mục lục',th:'สารบัญ',ar:'المحتويات',it:'Indice',az:'Mündəricat',mn:'Гарчиг',km:'មាតិកា'};
const departmentLabels={ja:['学科別','学科別認知ダッシュボード'],'zh-CN':['专业','专业认知仪表板'],'zh-TW':['學系','學系認知儀表板'],es:['Departamentos','Panel cognitivo por departamento'],fr:['Départements','Tableau cognitif par département'],ru:['Направления','Когнитивная панель по направлениям'],vi:['Ngành học','Bảng nhận thức theo ngành học'],th:['สาขาวิชา','แดชบอร์ดการรู้คิดตามสาขาวิชา'],ar:['التخصصات','لوحة القدرات المعرفية حسب التخصص'],it:['Dipartimenti','Dashboard cognitiva per dipartimento'],az:['İxtisaslar','İxtisas üzrə koqnitiv panel'],mn:['Мэргэжлийн хөтөлбөр','Мэргэжлийн хөтөлбөрийн танин мэдэхүйн самбар'],km:['ជំនាញសិក្សា','ផ្ទាំងការយល់ដឹងតាមជំនាញ']};
const packs={ko,en};
for(const [code,values] of Object.entries(core)){
  const messages={...en};
  coreKeys.forEach((key,i)=>{messages[key]=values[i];});
  messages['nav.contents']=contentsLabels[code];
  messages['nav.track']=departmentLabels[code][0];
  messages['mode.track.title']=departmentLabels[code][1];
  packs[code]=messages;
}
const extraKeys=['runtime.loading.class','runtime.loading.school','runtime.loading.track','runtime.error.title','runtime.error.help','runtime.error.missing_context','runtime.error.missing_endpoint','runtime.error.http_error','runtime.error.request_timeout','runtime.error.network_error','runtime.error.empty_results','runtime.error.adapter_error','runtime.error.unknown','runtime.empty','career.resultMissing','career.reportProvided','career.fitScore','career.aptitude.title','career.resultSource'];
const extras={
  ko:['학급 데이터를 불러오는 중이에요…','학교 데이터를 불러오는 중이에요…','학과 데이터를 불러오는 중이에요…','데이터를 불러오지 못했어요.','페이지를 새로고침하거나 관리자에게 문의하세요.','필수 조회 식별자가 없습니다: {key}','대시보드 API 경로가 설정되지 않았습니다.','결과지 서버 응답 오류가 발생했습니다.','결과지 데이터를 불러오는 시간이 초과되었습니다.','결과지 서버에 연결하지 못했습니다.','조회된 결과지 데이터가 없습니다.','결과지 데이터를 처리하지 못했습니다.','알 수 없는 오류가 발생했습니다.','표시할 학급 데이터가 없어요.','이 학생의 결과지에 진로적성·직무 Top 5 데이터가 없어요. 결과지 연동 필드를 확인하세요.','결과지 진로적성 분석','적합도 {score}','결과지 진로적성','직무 Top 5와 진로적성은 학생 결과지에서 연동한 값입니다. 상담 시 흥미·가치관·경험·희망도 함께 확인하세요.'],
  en:['Loading class data…','Loading school data…','Loading department data…','Could not load data.','Refresh the page or contact an administrator.','Required lookup identifier is missing: {key}','The dashboard API endpoint is not configured.','The result server returned an error.','The result request timed out.','Could not connect to the result server.','No result data was returned.','Could not process the result data.','An unknown error occurred.','No class data is available.','This student’s report has no career-aptitude or Job Top 5 data. Check the report field mapping.','Report career-aptitude analysis','Fit {score}','Report career aptitude','Job Top 5 and career aptitude are linked from the student report. Also review interests, values, experience, and aspirations in counseling.'],
  ja:['クラスデータを読み込み中…','学校データを読み込み中…','学科データを読み込み中…','データを読み込めませんでした。','ページを更新するか管理者にお問い合わせください。','必須の照会IDがありません: {key}','ダッシュボードAPIが設定されていません。','結果サーバーでエラーが発生しました。','結果データの読み込みがタイムアウトしました。','結果サーバーに接続できません。','結果データがありません。','結果データを処理できません。','不明なエラーが発生しました。','表示できるクラスデータがありません。','この生徒の結果票に進路適性・職務Top 5がありません。連携項目を確認してください。','結果票の進路適性分析','適合度 {score}','結果票の進路適性','職務Top 5と進路適性は生徒の結果票から連携されています。興味・価値観・経験・希望も確認してください。'],
  'zh-CN':['正在加载班级数据…','正在加载学校数据…','正在加载专业数据…','无法加载数据。','请刷新页面或联系管理员。','缺少必需的查询标识: {key}','未配置仪表板 API。','结果服务器返回错误。','加载结果数据超时。','无法连接结果服务器。','没有返回结果数据。','无法处理结果数据。','发生未知错误。','没有可显示的班级数据。','该学生的报告中没有职业倾向或岗位 Top 5 数据。请检查字段映射。','报告职业倾向分析','匹配度 {score}','报告职业倾向','岗位 Top 5 和职业倾向来自学生报告。咨询时还需结合兴趣、价值观、经验和意愿。'],
  'zh-TW':['正在載入班級資料…','正在載入學校資料…','正在載入學系資料…','無法載入資料。','請重新整理頁面或聯絡管理員。','缺少必要的查詢識別碼：{key}','尚未設定儀表板 API。','結果伺服器回傳錯誤。','載入結果資料逾時。','無法連線結果伺服器。','沒有回傳結果資料。','無法處理結果資料。','發生未知錯誤。','沒有可顯示的班級資料。','此學生的結果報告沒有生涯適性或職務 Top 5 資料。請確認欄位對應。','結果報告生涯適性分析','適配度 {score}','結果報告生涯適性','職務 Top 5 與生涯適性均連結自學生結果報告。諮詢時也請確認興趣、價值觀、經驗與意願。'],
  es:['Cargando datos de la clase…','Cargando datos de la escuela…','Cargando datos del departamento…','No se pudieron cargar los datos.','Actualiza la página o contacta con un administrador.','Falta el identificador obligatorio: {key}','La API del panel no está configurada.','El servidor de resultados devolvió un error.','La solicitud de resultados agotó el tiempo.','No se pudo conectar con el servidor de resultados.','No se devolvieron resultados.','No se pudieron procesar los resultados.','Ocurrió un error desconocido.','No hay datos de clase para mostrar.','El informe del estudiante no contiene aptitud profesional ni Top 5 de puestos. Revisa el mapeo.','Análisis de aptitud del informe','Afinidad {score}','Aptitud profesional del informe','El Top 5 y la aptitud proceden del informe del estudiante. Revisa también intereses, valores, experiencia y aspiraciones.'],
  fr:['Chargement des données de la classe…','Chargement des données de l’établissement…','Chargement des données du département…','Impossible de charger les données.','Actualisez la page ou contactez un administrateur.','Identifiant requis manquant : {key}','L’API du tableau de bord n’est pas configurée.','Le serveur de résultats a renvoyé une erreur.','Le chargement des résultats a expiré.','Connexion au serveur de résultats impossible.','Aucun résultat renvoyé.','Impossible de traiter les résultats.','Une erreur inconnue est survenue.','Aucune donnée de classe à afficher.','Le rapport de cet élève ne contient ni aptitude professionnelle ni Top 5 des métiers. Vérifiez le mappage.','Analyse d’aptitude du rapport','Adéquation {score}','Aptitude professionnelle du rapport','Le Top 5 des métiers et l’aptitude proviennent du rapport de l’élève. Vérifiez aussi intérêts, valeurs, expériences et aspirations.'],
  ru:['Загрузка данных класса…','Загрузка данных школы…','Загрузка данных направления…','Не удалось загрузить данные.','Обновите страницу или обратитесь к администратору.','Отсутствует обязательный идентификатор: {key}','API панели не настроен.','Сервер результатов вернул ошибку.','Время загрузки результатов истекло.','Нет соединения с сервером результатов.','Данные результатов не получены.','Не удалось обработать результаты.','Произошла неизвестная ошибка.','Нет данных класса для отображения.','В отчёте ученика нет профпригодности или Top 5 профессий. Проверьте сопоставление полей.','Анализ профпригодности из отчёта','Соответствие {score}','Профпригодность из отчёта','Top 5 профессий и профпригодность получены из отчёта ученика. Учитывайте также интересы, ценности, опыт и цели.'],
  vi:['Đang tải dữ liệu lớp…','Đang tải dữ liệu trường…','Đang tải dữ liệu ngành…','Không thể tải dữ liệu.','Hãy làm mới trang hoặc liên hệ quản trị viên.','Thiếu mã tra cứu bắt buộc: {key}','API bảng điều khiển chưa được cấu hình.','Máy chủ kết quả trả về lỗi.','Yêu cầu kết quả đã hết thời gian.','Không thể kết nối máy chủ kết quả.','Không có dữ liệu kết quả.','Không thể xử lý dữ liệu kết quả.','Đã xảy ra lỗi không xác định.','Không có dữ liệu lớp để hiển thị.','Báo cáo học sinh chưa có năng lực nghề nghiệp hoặc Top 5 công việc. Hãy kiểm tra ánh xạ trường.','Phân tích năng lực nghề từ báo cáo','Độ phù hợp {score}','Năng lực nghề từ báo cáo','Top 5 công việc và năng lực nghề được liên kết từ báo cáo học sinh. Cần xem thêm sở thích, giá trị, kinh nghiệm và nguyện vọng.'],
  th:['กำลังโหลดข้อมูลชั้นเรียน…','กำลังโหลดข้อมูลโรงเรียน…','กำลังโหลดข้อมูลสาขา…','ไม่สามารถโหลดข้อมูลได้','รีเฟรชหน้าหรือติดต่อผู้ดูแลระบบ','ไม่มีรหัสที่จำเป็น: {key}','ยังไม่ได้ตั้งค่า API แดชบอร์ด','เซิร์ฟเวอร์ผลลัพธ์ส่งคืนข้อผิดพลาด','หมดเวลาโหลดผลลัพธ์','เชื่อมต่อเซิร์ฟเวอร์ผลลัพธ์ไม่ได้','ไม่มีข้อมูลผลลัพธ์','ประมวลผลข้อมูลผลลัพธ์ไม่ได้','เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุ','ไม่มีข้อมูลชั้นเรียนให้แสดง','รายงานของนักเรียนไม่มีความถนัดอาชีพหรือ Top 5 งาน โปรดตรวจสอบการแมปฟิลด์','การวิเคราะห์ความถนัดจากรายงาน','ความเหมาะสม {score}','ความถนัดอาชีพจากรายงาน','Top 5 งานและความถนัดอาชีพเชื่อมจากรายงานนักเรียน โปรดพิจารณาความสนใจ คุณค่า ประสบการณ์ และความตั้งใจด้วย'],
  ar:['جارٍ تحميل بيانات الصف…','جارٍ تحميل بيانات المدرسة…','جارٍ تحميل بيانات التخصص…','تعذر تحميل البيانات.','حدّث الصفحة أو تواصل مع المسؤول.','معرّف البحث المطلوب مفقود: {key}','واجهة API للوحة غير مهيأة.','أعاد خادم النتائج خطأ.','انتهت مهلة تحميل النتائج.','تعذر الاتصال بخادم النتائج.','لم تُرجع بيانات نتائج.','تعذرت معالجة بيانات النتائج.','حدث خطأ غير معروف.','لا توجد بيانات صف لعرضها.','لا يتضمن تقرير الطالب الاستعداد المهني أو أفضل 5 وظائف. تحقق من ربط الحقول.','تحليل الاستعداد المهني من التقرير','الملاءمة {score}','الاستعداد المهني من التقرير','أفضل 5 وظائف والاستعداد المهني مرتبطان بتقرير الطالب. راجع أيضًا الاهتمامات والقيم والخبرة والطموحات.'],
  it:['Caricamento dati della classe…','Caricamento dati della scuola…','Caricamento dati del dipartimento…','Impossibile caricare i dati.','Aggiorna la pagina o contatta un amministratore.','Identificatore richiesto mancante: {key}','API del dashboard non configurata.','Il server dei risultati ha restituito un errore.','Richiesta dei risultati scaduta.','Impossibile connettersi al server dei risultati.','Nessun risultato restituito.','Impossibile elaborare i risultati.','Si è verificato un errore sconosciuto.','Nessun dato di classe da mostrare.','Il report non contiene attitudine professionale o Top 5 lavori. Verifica la mappatura.','Analisi attitudinale del report','Compatibilità {score}','Attitudine professionale del report','Top 5 e attitudine provengono dal report dello studente. Considera anche interessi, valori, esperienza e aspirazioni.'],
  az:['Sinif məlumatları yüklənir…','Məktəb məlumatları yüklənir…','İxtisas məlumatları yüklənir…','Məlumatları yükləmək olmadı.','Səhifəni yeniləyin və ya administratorla əlaqə saxlayın.','Tələb olunan identifikator yoxdur: {key}','Panel API-si qurulmayıb.','Nəticə serveri xəta qaytardı.','Nəticə sorğusunun vaxtı bitdi.','Nəticə serverinə qoşulmaq olmadı.','Nəticə məlumatı qaytarılmadı.','Nəticələri emal etmək olmadı.','Naməlum xəta baş verdi.','Göstəriləcək sinif məlumatı yoxdur.','Şagird hesabatında karyera uyğunluğu və ya Top 5 iş yoxdur. Sahə uyğunluğunu yoxlayın.','Hesabatın karyera uyğunluğu təhlili','Uyğunluq {score}','Hesabat üzrə karyera uyğunluğu','Top 5 iş və karyera uyğunluğu şagird hesabatından alınır. Maraqları, dəyərləri, təcrübəni və istəkləri də nəzərə alın.'],
  mn:['Ангийн өгөгдлийг ачаалж байна…','Сургуулийн өгөгдлийг ачаалж байна…','Хөтөлбөрийн өгөгдлийг ачаалж байна…','Өгөгдлийг ачаалж чадсангүй.','Хуудсыг шинэчлэх эсвэл админтай холбогдоно уу.','Шаардлагатай таних утга алга: {key}','Самбарын API тохируулаагүй.','Үр дүнгийн сервер алдаа буцаалаа.','Үр дүн ачаалах хугацаа дууслаа.','Үр дүнгийн серверт холбогдож чадсангүй.','Үр дүнгийн өгөгдөл ирсэнгүй.','Үр дүнг боловсруулж чадсангүй.','Үл мэдэгдэх алдаа гарлаа.','Харуулах ангийн өгөгдөл алга.','Сурагчийн тайланд мэргэжлийн тохирц эсвэл Top 5 ажил алга. Талбарын холболтыг шалгана уу.','Тайлангийн мэргэжлийн тохирцын шинжилгээ','Тохирц {score}','Тайлангийн мэргэжлийн тохирц','Top 5 ажил ба тохирц нь сурагчийн тайлангаас холбогдоно. Сонирхол, үнэт зүйл, туршлага, хүсэлтийг мөн харгалзана уу.'],
  km:['កំពុងផ្ទុកទិន្នន័យថ្នាក់…','កំពុងផ្ទុកទិន្នន័យសាលា…','កំពុងផ្ទុកទិន្នន័យជំនាញ…','មិនអាចផ្ទុកទិន្នន័យបាន។','សូមផ្ទុកទំព័រឡើងវិញ ឬទាក់ទងអ្នកគ្រប់គ្រង។','បាត់លេខសម្គាល់ចាំបាច់៖ {key}','មិនទាន់កំណត់ API ផ្ទាំងទេ។','ម៉ាស៊ីនមេលទ្ធផលបានបញ្ជូនកំហុស។','ការផ្ទុកលទ្ធផលអស់ពេល។','មិនអាចភ្ជាប់ម៉ាស៊ីនមេលទ្ធផលបាន។','គ្មានទិន្នន័យលទ្ធផល។','មិនអាចដំណើរការលទ្ធផលបាន។','មានកំហុសមិនស្គាល់។','គ្មានទិន្នន័យថ្នាក់សម្រាប់បង្ហាញ។','របាយការណ៍សិស្សគ្មានសមត្ថភាពអាជីព ឬការងារ Top 5។ សូមពិនិត្យការភ្ជាប់ទិន្នន័យ។','ការវិភាគសមត្ថភាពអាជីពពីរបាយការណ៍','ភាពសមស្រប {score}','សមត្ថភាពអាជីពពីរបាយការណ៍','ការងារ Top 5 និងសមត្ថភាពអាជីពត្រូវបានភ្ជាប់ពីរបាយការណ៍សិស្ស។ សូមពិនិត្យចំណាប់អារម្មណ៍ តម្លៃ បទពិសោធន៍ និងបំណងផងដែរ។']
};
for(const [code,values] of Object.entries(extras))extraKeys.forEach((key,index)=>{packs[code][key]=values[index];});
const careerTemplateKeys=['career.top5','career.uses','career.counsel.start','career.counsel.experience','career.counsel.job','career.essay.situation','career.essay.link'];
const careerTemplates={
  ja:['{student}のおすすめ職務・進路 Top 5','{strengths}を活用','探索の出発点：{strengths}の強みが実際の活動にどう表れたか確認します。','経験の質問：{prompt}の具体例を聞きます。','職務確認：{job}を含むTop 5から関心のある職務を選び、仕事内容・必要能力・環境を調べます。','状況・課題：{prompt}に関する経験を題材候補にします。','進路との接続：{job}の探索と今後伸ばす能力を結び付けます。'],
  'zh-CN':['{student} 推荐岗位与职业方向 Top 5','运用 {strengths}','探索起点：确认 {strengths} 优势如何体现在实际活动中。','经历提问：请具体说明一次 {prompt} 的经历。','岗位确认：从包括 {job} 在内的 Top 5 中选择感兴趣的岗位，调查实际工作、所需能力和工作环境。','情境与任务：寻找与 {prompt} 有关的经历作为素材。','职业连接：把对 {job} 的探索与今后需要提升的能力联系起来。'],
  'zh-TW':['{student} 推薦職務與生涯方向 Top 5','運用 {strengths}','探索起點：確認 {strengths} 優勢如何呈現在實際活動中。','經驗提問：請具體說明一次 {prompt} 的經驗。','職務確認：從包含 {job} 的 Top 5 中選擇有興趣的職務，調查實際工作、所需能力與工作環境。','情境與任務：尋找與 {prompt} 有關的經驗作為素材。','生涯連結：把對 {job} 的探索與未來要提升的能力連結起來。'],
  es:['Top 5 de carreras para {student}','Uso de {strengths}','Punto de partida: comprueba cómo se manifiestan las fortalezas de {strengths} en actividades reales.','Pregunta de experiencia: pide un ejemplo concreto de {prompt}.','Comprobación profesional: elige una opción del Top 5, incluida {job}, e investiga tareas, capacidades y entorno laboral.','Situación y tarea: busca una experiencia relacionada con {prompt}.','Conexión profesional: relaciona la exploración de {job} con las capacidades que desea desarrollar.'],
  fr:['Top 5 des métiers pour {student}','Mobilise {strengths}','Point de départ : vérifiez comment les forces en {strengths} apparaissent dans des activités réelles.','Question d’expérience : demandez un exemple concret de {prompt}.','Vérification métier : choisissez une piste du Top 5, dont {job}, puis étudiez les tâches, compétences et conditions de travail.','Situation et tâche : cherchez une expérience liée à {prompt}.','Lien professionnel : reliez l’exploration de {job} aux compétences à développer.'],
  ru:['Top 5 профессий для {student}','Использует {strengths}','Начало поиска: выясните, как сильные стороны {strengths} проявлялись в реальной деятельности.','Вопрос об опыте: попросите конкретный пример — {prompt}.','Проверка профессии: выберите интересную профессию из Top 5, включая {job}, и изучите задачи, навыки и условия труда.','Ситуация и задача: найдите опыт, связанный с {prompt}.','Связь с профессией: соедините изучение {job} с навыками для дальнейшего развития.'],
  vi:['Top 5 nghề nghiệp cho {student}','Vận dụng {strengths}','Điểm bắt đầu: kiểm tra cách thế mạnh {strengths} thể hiện trong hoạt động thực tế.','Câu hỏi trải nghiệm: yêu cầu một ví dụ cụ thể về {prompt}.','Kiểm tra nghề: chọn một nghề quan tâm trong Top 5, gồm {job}, rồi tìm hiểu công việc, năng lực cần thiết và môi trường.','Tình huống và nhiệm vụ: tìm một trải nghiệm liên quan đến {prompt}.','Liên kết nghề nghiệp: kết nối quá trình tìm hiểu {job} với năng lực cần phát triển.'],
  th:['Top 5 อาชีพสำหรับ {student}','ใช้จุดแข็ง {strengths}','จุดเริ่มต้น: ตรวจสอบว่าจุดแข็ง {strengths} ปรากฏในกิจกรรมจริงอย่างไร','คำถามประสบการณ์: ขอให้ยกตัวอย่างที่ชัดเจนเกี่ยวกับ {prompt}','ตรวจสอบอาชีพ: เลือกอาชีพที่สนใจจาก Top 5 รวมถึง {job} แล้วศึกษางาน ทักษะที่ต้องใช้ และสภาพแวดล้อม','สถานการณ์และภารกิจ: หาเหตุการณ์ที่เกี่ยวข้องกับ {prompt}','การเชื่อมโยงอาชีพ: เชื่อมการสำรวจ {job} กับทักษะที่จะพัฒนาต่อไป'],
  ar:['أفضل 5 مسارات مهنية للطالب {student}','توظيف {strengths}','نقطة البداية: تحقّق من ظهور نقاط القوة في {strengths} ضمن أنشطة فعلية.','سؤال الخبرة: اطلب مثالًا محددًا على {prompt}.','التحقق المهني: اختر مسارًا من أفضل 5، ومنها {job}، وابحث في المهام والقدرات المطلوبة وبيئة العمل.','الموقف والمهمة: ابحث عن تجربة تتعلق بـ {prompt}.','الربط المهني: اربط استكشاف {job} بالقدرات المطلوب تطويرها لاحقًا.'],
  it:['Top 5 professioni per {student}','Utilizza {strengths}','Punto di partenza: verifica come i punti di forza in {strengths} emergono nelle attività reali.','Domanda sull’esperienza: chiedi un esempio concreto di {prompt}.','Verifica professionale: scegli un’opzione tra le Top 5, inclusa {job}, e studia mansioni, capacità e ambiente di lavoro.','Situazione e compito: cerca un’esperienza relativa a {prompt}.','Collegamento professionale: collega l’esplorazione di {job} alle capacità da sviluppare.'],
  az:['{student} üçün Top 5 peşə istiqaməti','{strengths} güclərindən istifadə','Başlanğıc nöqtəsi: {strengths} güclərinin real fəaliyyətlərdə necə göründüyünü yoxlayın.','Təcrübə sualı: {prompt} barədə konkret nümunə istəyin.','Peşə yoxlaması: Top 5-dən, o cümlədən {job} istiqamətindən maraqlı olanı seçib vəzifələri, bacarıqları və iş mühitini araşdırın.','Vəziyyət və tapşırıq: {prompt} ilə bağlı təcrübə tapın.','Peşə əlaqəsi: {job} araşdırmasını inkişaf etdiriləcək bacarıqlarla bağlayın.'],
  mn:['{student}-д зориулсан Top 5 ажил мэргэжил','{strengths}-ийг ашиглана','Эхлэл: {strengths} давуу тал бодит үйл ажиллагаанд хэрхэн илэрснийг шалгана.','Туршлагын асуулт: {prompt}-ын тодорхой жишээг асууна.','Мэргэжил шалгах: Top 5-аас {job}-ыг оролцуулан сонирхсон ажлыг сонгож, үүрэг, чадвар, орчныг судална.','Нөхцөл ба даалгавар: {prompt}-тай холбоотой туршлагыг олно.','Мэргэжлийн холбоо: {job}-ын судалгааг цааш хөгжүүлэх чадвартай холбоно.'],
  km:['ការងារ Top 5 សម្រាប់ {student}','ប្រើប្រាស់ {strengths}','ចំណុចចាប់ផ្តើម៖ ពិនិត្យថាចំណុចខ្លាំង {strengths} បង្ហាញក្នុងសកម្មភាពពិតយ៉ាងដូចម្តេច។','សំណួរបទពិសោធន៍៖ សួរឧទាហរណ៍ជាក់លាក់អំពី {prompt}។','ពិនិត្យអាជីព៖ ជ្រើសអាជីពពី Top 5 រួមទាំង {job} ហើយសិក្សាភារកិច្ច សមត្ថភាព និងបរិយាកាសការងារ។','ស្ថានភាព និងភារកិច្ច៖ ស្វែងរកបទពិសោធន៍ទាក់ទងនឹង {prompt}។','ការភ្ជាប់អាជីព៖ ភ្ជាប់ការស្វែងយល់អំពី {job} ជាមួយសមត្ថភាពដែលត្រូវអភិវឌ្ឍ។']
};
for(const [code,values] of Object.entries(careerTemplates))careerTemplateKeys.forEach((key,index)=>{packs[code][key]=values[index];});
const promptKeys=['career.prompt.PLAN','career.prompt.ATT','career.prompt.SIM','career.prompt.SUC'];
const promptTranslations={
  ja:['目標を立て、役割と日程を調整して最後まで実行した経験','小さな誤りや変化に気づき、集中して質を高めた経験','複数の資料を結び付け、全体構造や新しい解決策を作った経験','複雑な手順を順序立てて整理し、正確に説明した経験'],
  'zh-CN':['设定目标、协调角色与日程并坚持完成的经历','发现细小错误或变化并专注提升质量的经历','连接多项资料并形成整体结构或新解决方案的经历','按顺序整理复杂流程或准确说明的经历'],
  'zh-TW':['設定目標、協調角色與時程並堅持完成的經驗','發現細小錯誤或變化並專注提升品質的經驗','連結多項資料並形成整體架構或新解決方案的經驗','依序整理複雜流程或準確說明的經驗'],
  es:['fijar una meta, coordinar funciones y plazos y completar el trabajo','detectar pequeños errores o cambios y mejorar la calidad con atención sostenida','conectar varias fuentes para crear una estructura global o una solución nueva','ordenar un procedimiento complejo o explicarlo con precisión'],
  fr:['fixer un objectif, coordonner les rôles et le calendrier, puis aller au bout','repérer une petite erreur ou un changement et améliorer la qualité par l’attention','relier plusieurs sources pour construire une vue d’ensemble ou une nouvelle solution','ordonner une procédure complexe ou l’expliquer précisément'],
  ru:['поставить цель, согласовать роли и сроки и довести дело до конца','заметить небольшую ошибку или изменение и повысить качество благодаря вниманию','связать несколько источников в общую структуру или новое решение','упорядочить сложную процедуру или точно её объяснить'],
  vi:['đặt mục tiêu, điều phối vai trò và thời gian rồi hoàn thành đến cùng','phát hiện lỗi hoặc thay đổi nhỏ và tập trung nâng cao chất lượng','kết nối nhiều nguồn để tạo cấu trúc tổng thể hoặc giải pháp mới','sắp xếp một quy trình phức tạp theo thứ tự hoặc giải thích chính xác'],
  th:['การตั้งเป้าหมาย ประสานบทบาทและเวลา และทำจนสำเร็จ','การพบข้อผิดพลาดหรือการเปลี่ยนแปลงเล็กน้อยและเพิ่มคุณภาพด้วยสมาธิ','การเชื่อมโยงข้อมูลหลายแหล่งเพื่อสร้างภาพรวมหรือทางแก้ใหม่','การจัดลำดับขั้นตอนที่ซับซ้อนหรืออธิบายอย่างถูกต้อง'],
  ar:['تحديد هدف وتنسيق الأدوار والمواعيد والاستمرار حتى الإنجاز','اكتشاف خطأ أو تغيير صغير وتحسين الجودة بالتركيز','ربط عدة مصادر لبناء صورة متكاملة أو حل جديد','ترتيب إجراء معقد بالتسلسل أو شرحه بدقة'],
  it:['definire un obiettivo, coordinare ruoli e tempi e portare a termine il lavoro','individuare un piccolo errore o cambiamento e migliorare la qualità con attenzione','collegare più fonti per creare una struttura complessiva o una nuova soluzione','ordinare una procedura complessa o spiegarla con precisione'],
  az:['məqsəd qoymaq, rolları və vaxtı əlaqələndirmək və işi sona çatdırmaq','kiçik səhv və ya dəyişikliyi görüb diqqətlə keyfiyyəti artırmaq','bir neçə mənbəni birləşdirib ümumi struktur və ya yeni həll yaratmaq','mürəkkəb prosesi ardıcıllıqla təşkil etmək və ya dəqiq izah etmək'],
  mn:['зорилго тавьж, үүрэг ба хугацааг зохицуулан ажлыг дуусгах','жижиг алдаа эсвэл өөрчлөлтийг анзаарч төвлөрлөөр чанарыг сайжруулах','олон эх сурвалжийг холбож ерөнхий бүтэц эсвэл шинэ шийдэл бүтээх','нарийн үйл явцыг дарааллаар зохион байгуулах эсвэл зөв тайлбарлах'],
  km:['កំណត់គោលដៅ សម្របសម្រួលតួនាទីនិងពេលវេលា ហើយអនុវត្តដល់ចប់','សង្កេតកំហុសឬការផ្លាស់ប្តូរតូចៗ ហើយបង្កើនគុណភាពដោយការផ្តោត','ភ្ជាប់ប្រភពច្រើនដើម្បីបង្កើតរចនាសម្ព័ន្ធទាំងមូល ឬដំណោះស្រាយថ្មី','រៀបចំនីតិវិធីស្មុគស្មាញតាមលំដាប់ ឬពន្យល់ឲ្យបានត្រឹមត្រូវ']
};
for(const [code,values] of Object.entries(promptTranslations))promptKeys.forEach((key,index)=>{packs[code][key]=values[index];});
const domSourceFile=path.join(root,'i18n-source','dom-ko.json');
const domTranslationDir=path.join(root,'i18n-source','translated');
const domSource=JSON.parse(fs.readFileSync(domSourceFile,'utf8'));
const manualSourceValues=new Set(Object.values(ko));
const domEntries=domSource.strings.filter(entry=>!manualSourceValues.has(entry.source));
const exactDomBySource=new Map(domSource.strings.filter(entry=>!entry.source.includes('__V')).map(entry=>[entry.source,entry.key]));
for(const entry of domEntries)ko[entry.key]=entry.source;
for(const code of Object.keys(labels)){
  if(code==='ko')continue;
  const translatedFile=path.join(domTranslationDir,`${code}.json`);
  if(!fs.existsSync(translatedFile))throw new Error(`${code}: DOM translation file missing`);
  const translated=JSON.parse(fs.readFileSync(translatedFile,'utf8')).messages||{};
  for(const entry of domEntries){
    const value=translated[entry.key];
    if(!value)throw new Error(`${code}: missing DOM translation ${entry.key}`);
    const expected=new Set([...entry.source.matchAll(/__V([0-9]+)__/g)].map(match=>match[1]));
    const actual=new Set([...value.matchAll(/__V([0-9]+)__/g)].map(match=>match[1]));
    const missing=[...expected].filter(marker=>!actual.has(marker));
    const unexpected=[...actual].filter(marker=>!expected.has(marker));
    if(missing.length||unexpected.length)throw new Error(`${code}: DOM placeholder mismatch ${entry.key}`);
    packs[code][entry.key]=value;
  }
  // 이미 DOM 번역 자원에 있는 동일 원문은 신규 번역하지 않고 안정 key에서도 재사용한다.
  for(const [key,source] of Object.entries(ko)){
    if(typeof source!=='string'||source.includes('{'))continue;
    const domKey=exactDomBySource.get(source),value=domKey&&translated[domKey];
    if(value)packs[code][key]=value;
  }
}
const sourceHash=crypto.createHash('sha256').update(JSON.stringify(ko)).digest('hex');
fs.mkdirSync(out,{recursive:true});
const manifest=Object.keys(labels).map(code=>({code,label:labels[code],dir:code==='ar'?'rtl':'ltr',status:code==='ko'?'ready':'ai-draft',file:code+'.json'}));
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
for(const item of manifest){
  const payload={locale:item.code,sourceLocale:'ko',direction:item.dir,status:item.status,sourceVersion:1,sourceHash,messages:packs[item.code]};
  const missing=Object.keys(ko).filter(key=>!payload.messages[key]);
  if(missing.length)throw new Error(item.code+' missing '+missing.join(', '));
  const sourceKeys=Object.keys(ko); const targetKeys=Object.keys(payload.messages);
  if(sourceKeys.length!==targetKeys.length)throw new Error(item.code+' key count mismatch');
  fs.writeFileSync(path.join(out,item.file),JSON.stringify(payload,null,2)+'\n');
}
console.log('Built '+manifest.length+' locale packs, '+Object.keys(ko).length+' keys each, sourceHash '+sourceHash);
