import {test} from 'node:test';import assert from 'node:assert/strict';
import {newWriting,commitWrittenPrediction,predictionFields,actPlan,saveWrittenStory,storyFields,saveWrittenComparison,bookStatus,validateWriting,editStoryField} from '../src/writing-contract.mjs';
import {reviewComplete} from '../src/reconsideration.mjs';
function ready(age='high-school'){
 let r=newWriting(age);r.conditionConfirmed=true;for(const k of predictionFields(r))r.predictionDraft[k]=`  learner ${k}\n`;
 r=commitWrittenPrediction(r);r=actPlan(r,'goal','hear');if(age==='high-school'){r=actPlan(r,'compare','tell');r=actPlan(r,'compare','time');}
 r=actPlan(r,'method','tell');r=actPlan(r,'start');r=actPlan(r,'outcome');if(age==='high-school'){r=actPlan(r,'fact');r=actPlan(r,'unknown','tell.language');r=actPlan(r,'limitText','limit');}
 r=actPlan(r,'connectionText','reason');r=actPlan(r,'judge');if(age==='high-school')r=actPlan(r,'fit','undetermined');return actPlan(r,'decision','keep');
}
test('written prediction needs every age-specific field and preserves whitespace',()=>{let r=newWriting('high-school');assert.throws(()=>commitWrittenPrediction(r));r.conditionConfirmed=true;for(const k of predictionFields(r))r.predictionDraft[k]='\u200b ';assert.throws(()=>commitWrittenPrediction(r));for(const k of predictionFields(r))r.predictionDraft[k]='  input\n';r=commitWrittenPrediction(r);assert.equal(r.prediction.expression.direct,'  input\n');const first=structuredClone(r.prediction);r.predictionDraft.direct='edited';assert.deepEqual(commitWrittenPrediction(r).prediction,first);});
test('writing alone cannot bypass planning',()=>{const r=newWriting('middle-school');for(const k of storyFields(r))r.story[k]='text';assert.throws(()=>saveWrittenStory(r));});
test('both ages retain PASS gate and independent comparisons even with identical strings',()=>{for(const age of ['middle-school','high-school']){let r=ready(age);assert.equal(reviewComplete(r),true);for(const k of storyFields(r))r.story[k]='  story\n';r=saveWrittenStory(r);for(const kind of ['history','prediction']){r.comparisonDrafts[kind]={difference:' same ',reason:' reason\n'};r=saveWrittenComparison(r,kind);}assert.notEqual(r.comparisons.history.eventId,r.comparisons.prediction.eventId);assert.equal(r.comparisons.history.resultId,r.resultId);assert.equal(r.comparisons.prediction.reason,' reason\n');assert.equal(bookStatus(r),'assembled');assert.equal(validateWriting(r),true);}});
test('deferred comparisons retain drafts and do not complete book',()=>{let r=ready();for(const k of storyFields(r))r.story[k]='text';r=saveWrittenStory(r);r.comparisonDrafts.history.difference='draft';r=saveWrittenComparison(r,'history',true);r=saveWrittenComparison(r,'prediction',true);assert.equal(bookStatus(r),'pendingComparison');assert.equal(r.comparisonDrafts.history.difference,'draft');assert.equal(r.comparisons.history.status,'deferred');});
test('revision needs changed method and renewed evidence',()=>{let r=ready();r=actPlan(r,'edit');r=actPlan(r,'judge');r=actPlan(r,'fit','insufficient');r=actPlan(r,'decision','revise');r=actPlan(r,'method','tell');assert.equal(reviewComplete(r),false);r=actPlan(r,'method','time');assert.equal(r.planning.history.length,1);assert.equal(r.planning.draft.connectionText,'');assert.equal(reviewComplete(r),false);});
test('version and context prevent old record conversion',()=>{const r=ready();assert.throws(()=>validateWriting({...r,writingVersion:'old'}));assert.throws(()=>validateWriting({...r,conditionId:'gutenberg.c1'}));assert.throws(()=>validateWriting({...r,prediction:{...r.prediction,attemptId:'another'}}));});
test('story or plan edits archive previous output and invalidate comparisons',()=>{let r=ready();for(const k of storyFields(r))r.story[k]='old';r=saveWrittenStory(r);for(const k of ['history','prediction']){r.comparisonDrafts[k]={difference:'old difference',reason:'old reason'};r=saveWrittenComparison(r,k);}const changed=editStoryField({...r,step:'story'},'text','new');assert.equal(changed.previousStoryVersions[0].story.text,'old');assert.equal(changed.comparisons.history.status,'empty');assert.equal(changed.story.saved,false);const plan=actPlan({...r,step:'path'},'edit');assert.equal(plan.previousStoryVersions[0].comparisons.history.difference,'old difference');assert.equal(plan.story.saved,false);});
