const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const ok=(v,m)=>{if(!v)throw Error(m);};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/tmp/nuvia-chromium',args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu','--disable-software-rasterizer']});
 const p=await browser.newPage({viewport:{width:1280,height:1000}});p.setDefaultTimeout(8000);const errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(pathToFileURL(path.resolve('deliverables/NUVIA_PLANNER_2_5D.html')).href);await p.evaluate(()=>localStorage.clear());await p.reload();
 const root=path.resolve('../font-runtime/package');if(fs.existsSync(root)){const css=['400','700'].map(w=>fs.readFileSync(path.join(root,w+'.css'),'utf8')).join('\n').replace(/url\(([^)]+)\)/g,(m,v)=>'url(data:font/woff2;base64,'+fs.readFileSync(path.join(root,v.replace(/["']/g,''))).toString('base64')+')');await p.addStyleTag({content:css+'\nbody,button,input,select,textarea{font-family:"Noto Sans KR",sans-serif!important}'});await p.addInitScript(c=>document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent=c;document.head.append(s);}),css+'\nbody,button,input,select,textarea{font-family:"Noto Sans KR",sans-serif!important}');await p.evaluate(()=>document.fonts.ready);}
 const get=()=>p.evaluate(()=>window.NUVIAPlanner.getWorkspace());
 const fill=async(label,value)=>p.getByLabel(label,{exact:true}).fill(value);
 const snap=async(name)=>{await p.locator('main').evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-20));await p.screenshot({path:'qa/'+name+'.png'});await p.setViewportSize({width:390,height:844});ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name+' mobile overflow');await p.screenshot({path:'qa/'+name+'-mobile.png'});await p.setViewportSize({width:1280,height:1000});};
 await p.getByRole('button',{name:'초등 생활 예시로 체험하기',exact:true}).click();await p.getByRole('button',{name:'운동하기 앞으로',exact:true}).click();ok((await get()).tasks[1].title==='운동하기','elementary reorder');await snap('age23-A-plan');
 await p.getByTestId('elementary-lower').click();ok((await get()).tasks.length===0,'lower isolated');await p.getByRole('button',{name:'숙제하기 +',exact:true}).click();ok((await get()).tasks.length===1,'lower picture add');ok(await p.getByLabel('오늘 사용 가능 시간',{exact:true}).count()===0,'lower simple scope');checks.push('초등 저학년 그림 선택/자료 분리, 고학년 순서 변경');await p.getByTestId('elementary-upper').click();
 await p.getByTestId('band-B').click();await p.getByTestId('age-example').click();await fill('수학 과제 할 날짜','2030-02-03');await fill('수학 과제 제출 마감','2030-02-01');ok((await get()).tasks[0].date==='2030-02-03'&&(await get()).tasks[0].deadline==='2030-02-01','independent date/deadline');ok(await p.getByText('할 날짜가 제출 마감보다 늦어요.',{exact:true}).isVisible(),'late warning');await snap('age23-B-plan');checks.push('중학생 주간 배치와 마감 충돌');
 await p.getByTestId('band-C').click();await p.getByTestId('age-example').click();await fill('중간 목표 이름','실험 결과 정리');await fill('중간 목표 날짜','2031-01-01');await p.getByRole('button',{name:'중간 목표 놓기',exact:true}).click();ok(await p.getByRole('alert').count()===1,'milestone guard');await fill('중간 목표 날짜','2026-09-15');await p.getByRole('button',{name:'중간 목표 놓기',exact:true}).click();await p.getByTestId('chronological-plan').click();const steps=(await get()).tasks[0].steps;ok(steps.length===5&&steps.every((s,i)=>i===0||s.date>=steps[i-1].date),'chronological application');await snap('age23-C-plan');checks.push('고등 중간 목표 검증·추가·날짜순 실행');
 await p.getByTestId('band-D').click();await p.getByTestId('age-example').click();await fill('발표 초안 취합 담당자','유하');ok((await get()).tasks[1].owner==='유하','owner update');const first=(await get()).tasks[0];const opts=await p.getByLabel('자료 조사 선행 작업',{exact:true}).locator('option').count();ok(opts===1,'cycle prevented');await p.getByLabel('자료 조사 답변 대기',{exact:true}).check();ok((await get()).tasks[0].waiting,'waiting update');await snap('age23-D-plan');checks.push('대학 담당 변경·선행 관계·순환 차단·답변 대기');
 await p.getByTestId('profile-1').click();
 for(const band of ['A','B','C','D']){
  await p.getByTestId('band-'+band).click();await p.getByRole('button',{name:'학년별 실행 예시로 체험하기',exact:true}).click();ok(await p.getByTestId('age-focus-'+band).count()===1,'age focus tools '+band);
  if(band==='A'){await fill('집중 준비물 직접 추가','줄넘기');await p.getByRole('button',{name:'챙길 것 추가',exact:true}).click();await p.getByRole('button',{name:'□ 줄넘기',exact:true}).click();ok((await get()).tasks[0].materials[0].done,'custom material');}
  if(band==='B'){await fill('이번 학습 범위','수학 20쪽 1~3번');await p.getByRole('button',{name:'이번 행동으로 정하기',exact:true}).click();ok((await get()).tasks[0].steps[0].title==='수학 20쪽 1~3번','range actual action');}
  await p.getByLabel('집중 준비 행동',{exact:true}).selectOption('park');await p.getByTestId('focus-start').click();
  if(band==='C'){await p.getByText('현재 행동을 두 구간으로 나누기',{exact:true}).click();await fill('작게 나눈 첫 행동','질문 후보 하나 적기');await fill('작게 나눈 나머지','후보 비교해 질문 정하기');await p.getByRole('button',{name:'둘로 나누고 다시 시작',exact:true}).click();ok((await get()).tasks[0].status==='paused'&&(await get()).tasks[0].steps.length===5,'split changes task');await p.getByTestId('focus-start').click();}
  if(band==='D'){await fill('결과물 인계 메모','조사 표 완성. 초안에 반영해 주세요.');}
  await fill('다른 일 보관 메모','나중에 연락하기');await p.getByTestId('focus-park').click();await fill('이어갈 위치','두 번째 줄부터');await p.getByTestId('focus-start').click();ok((await get()).tasks[0].practice.returns>=1,'return');await snap('age23-'+band+'-focus');
  while(await p.getByTestId('focus-step-done').count())await p.getByTestId('focus-step-done').click();
  await fill('집중 실제 시간','12');await p.getByTestId('focus-complete').click();ok((await get()).records.length===1,'completion '+band);
  if(band==='D')ok((await get()).tasks[0].adjustment.includes('조사 표'),'handoff persisted');
  const backup=await get();await p.reload();await p.getByTestId('profile-1').click();await p.getByTestId('band-'+band).click();ok((await get()).records.length===1,'reload '+band);ok((await p.evaluate(w=>window.NUVIAPlanner.setWorkspace(w),backup)).ok,'restore '+band);checks.push(band+' B 학년별 조작/중단/복귀/완료/재시작/백업 검증');
 }
 // Low elementary B separately
 await p.getByTestId('band-A').click();await p.getByTestId('elementary-lower').click();await p.getByRole('button',{name:'학년별 실행 예시로 체험하기',exact:true}).click();await fill('집중 준비물 직접 추가','필통');await p.getByRole('button',{name:'챙길 것 추가',exact:true}).click();ok((await get()).tasks[0].materials.length===1,'lower focus materials');
 ok(errors.length===0,errors.join(';'));fs.writeFileSync('qa/age23-results.json',JSON.stringify({passed:true,checks,jsErrors:errors},null,2));await browser.close();console.log(JSON.stringify({passed:true,checks}));
})().catch(e=>{console.error(e);process.exit(1);});
