const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const {pathToFileURL}=require('node:url');const {resolve}=require('node:path');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PLANNER_CHROMIUM_PATH||'/tmp/nuvia-chromium',args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu','--disable-software-rasterizer']});const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(5000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const click=id=>page.getByTestId(id).click();const demo=pathToFileURL(resolve('deliverables/NUVIA_PLANNER_2_5D.html')).href;
for(const profile of [0,1])for(const band of ['A','B','C','D']){await page.goto(demo);await click('profile-'+profile);await click('band-'+band);await page.getByTestId('project-mission').waitFor();assert.equal(await page.getByTestId('project-mission').locator('select,textarea,input').count(),0);assert.equal(await page.getByTestId('start-training').isEnabled(),false);
if(profile===0&&band==='A')await page.getByTestId('project-mission').screenshot({path:'qa/daily-desktop.png'});
const order=['C','D'].includes(band)?['fix','review','send','pack']:['fix','send','pack'];for(const id of order)await click('choose-'+id);await click('start-training');await click('skip-required');await click('peek-message');await click('pause-project');await page.getByText('하던 일은 그대로 있어요.').waitFor();await click('pause-project');await click('resume-project');if(order.includes('review'))await click('review-old');await click('send-draft');await click('pack-0');await click('pack-1');await click('pack-finish');await click('finish-day');assert.match(await page.locator('.ad-feedback').textContent(),/빠졌어요/);assert.equal((await page.evaluate(()=>window.NUVIAPlanner.getRecords())).length,0);await click('repair-name');if(order.includes('review'))await click('repair-review');await click('repair-file');await click('check-pack-1');await click('check-pack-2');await click('finish-day');const records=await page.evaluate(()=>window.NUVIAPlanner.getRecords());assert.equal(records.length,1);assert.equal(records[0].context.rulesVersion,'planner-1.8');assert.equal(records[0].measures.simulatedMinutes,22);assert.equal(records[0].measures.structuredCriteriaPassed,order.length);assert.equal(records[0].measures.revisionCompleted,true);assert.equal(await page.getByTestId('finish-day').count(),0);
if(profile===0&&band==='A'){await click('next-project');await page.getByTestId('real-task').fill('내 숙제');await page.getByTestId('real-first').fill('문제집 펴기');await click('start-real');await page.getByTestId('real-actual').fill('12');await page.getByTestId('real-completed').selectOption('yes');await click('save-real');const rs=await page.evaluate(()=>window.NUVIAPlanner.getRecords());assert.equal(rs.length,2);assert.equal(rs[1].source,'self_report');assert(!JSON.stringify(rs).includes('문제집 펴기'));}
console.log('PASS '+profile+' '+band);}
await page.goto(demo);await page.setViewportSize({width:390,height:844});await click('profile-1');await page.getByTestId('project-mission').screenshot({path:'qa/daily-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await click('choose-fix');await click('profile-0');assert.equal(await page.getByTestId('choose-fix').getAttribute('aria-pressed'),'false');
await page.goto(pathToFileURL(resolve('deliverables/NUVIA_PLANNER_PRODUCTION.html')).href);await page.getByText('검사 결과를 연결해 주세요').waitFor();assert.equal(await page.getByTestId('project-mission').count(),0);const report={schemaVersion:'1.0',assessmentId:'r1',subjectId:'s1',profileVersion:'1',educationStage:'high',axes:{planning:{level:'mid'},attention:{level:'low'},simultaneous:{level:'mid'},successive:{level:'high'}}};assert((await page.evaluate(r=>window.NUVIAPlanner.setAssessment(r),report)).ok);await page.getByTestId('choose-review').waitFor();assert.equal(await page.getByTestId('profile-0').count(),0);await page.evaluate(()=>window.NUVIAPlanner.clearAssessment());await page.getByText('검사 결과를 연결해 주세요').waitFor();assert.deepEqual(errors,[]);fs.writeFileSync('qa/daily-results.txt','PASS A/B × 4 age flows, mistake repair before record, interruption cost and pause, no plan form fields, real task report privacy, profile reset, mobile overflow, production assessment-only binding.\n');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
