const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const {pathToFileURL}=require('node:url');const {resolve}=require('node:path');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/tmp/nuvia-chromium',args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu','--disable-software-rasterizer']});
const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(4000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=id=>page.getByTestId(id).click();const select=(id,v)=>page.getByTestId(id).selectOption(v);const fill=(id,v)=>page.getByTestId(id).fill(v);
async function complete(profile,band,round){
if(round===0){assert.equal(await page.getByTestId('start-training').isEnabled(),false);await page.getByRole('button',{name:'모든 학생에게 의자가 부족하다',exact:true}).click();assert.equal(await page.getByTestId('start-training').isEnabled(),false);await page.getByRole('button',{name:'소음 문제를 먼저 살펴볼 필요가 있다',exact:true}).click();await click('start-training');}
await select('plan-first','read');await select('plan-check','draft');await select('plan-obstacle','return');await click('plan-start');for(let i=0;i<3;i++)await click('source-'+i);await page.getByTestId('evidence-0').check();await page.getByTestId('evidence-1').check();await fill('project-claim','자료를 근거로 필요한 안내를 먼저 적용하고 효과를 확인하겠습니다.');await select('initial-proposal','1');await click('draft-next');await page.getByRole('button',{name:'나중에 보기',exact:true}).click();await select('budget-response','ignore');await select('resume-choice','proposal');assert.equal(await page.getByTestId('resume-project').isEnabled(),false);await select('budget-response','check');if(profile===1){assert.equal(await page.getByTestId('resume-project').isEnabled(),false);await page.getByTestId('resume-confirm').check();}else assert.equal(await page.getByTestId('resume-confirm').count(),0);await click('resume-project');await click('submit-project');assert.match(await page.locator('.ad-feedback').textContent(),/3만 원/);await select('final-proposal','0');await select('project-limit','limited');await fill('revision-note','예산 감소로 안내부터 시행하고 관찰 후 확장하도록 수정했습니다.');if(band!=='A')await select('project-dependency','prepare');if(['C','D'].includes(band))await select('project-conflict','compare');if(band==='D')await select('project-approval','approve');await click('submit-project');await select('project-reflection','return');await click('save-project');assert.equal(await page.getByTestId('save-project').count(),0);
}
for(const profile of [0,1])for(const band of ['A','B','C','D']){
await page.goto(pathToFileURL(resolve('deliverables/NUVIA_PLANNER_2_5D.html')).href);await click('profile-'+profile);await click('band-'+band);assert.equal(await page.getByTestId('project-mission').getAttribute('data-depth'),String(['A','B','C','D'].indexOf(band)));if(profile===0&&band==='A')await page.screenshot({path:'qa/project-desktop.png',fullPage:true});await complete(profile,band,0);const r=await page.evaluate(()=>window.NUVIAPlanner.getRecords());assert.equal(r.length,1);assert.equal(r[0].context.rulesVersion,'planner-1.7');assert.equal(r[0].measures.structuredCriteriaPassed,4+['A','B','C','D'].indexOf(band));assert.equal(r[0].measures.errors,1);assert(!JSON.stringify(r).includes('예산 감소로'));
if(band==='A'){await click('next-project');assert.equal(await page.getByTestId('project-support').getByRole('button').getAttribute('aria-expanded'),'false');await complete(profile,band,1);await click('next-project');await page.getByTestId('real-task').waitFor();assert.equal((await page.evaluate(()=>window.NUVIAPlanner.getRecords())).length,2);}
console.log('PASS profile '+profile+' band '+band);
}
await page.goto(pathToFileURL(resolve('deliverables/NUVIA_PLANNER_2_5D.html')).href);await page.setViewportSize({width:390,height:844});await click('profile-1');await page.screenshot({path:'qa/project-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.goto(pathToFileURL(resolve('deliverables/NUVIA_PLANNER_PRODUCTION.html')).href);await page.getByText('검사 결과를 연결해 주세요').waitFor();assert.equal(await page.getByTestId('project-mission').count(),0);
const report={schemaVersion:'1.0',assessmentId:'official-project',subjectId:'test',profileVersion:'1',educationStage:'high',axes:{planning:{level:'mid'},attention:{level:'low'},simultaneous:{level:'mid'},successive:{level:'high'}}};assert((await page.evaluate(r=>window.NUVIAPlanner.setAssessment(r),report)).ok);await page.getByTestId('project-mission').waitFor();assert.equal(await page.getByTestId('project-mission').getAttribute('data-depth'),'2');assert.equal(await page.getByTestId('project-mission').getAttribute('data-target'),'attention');assert.equal(await page.getByTestId('profile-0').count(),0);await page.evaluate(()=>window.NUVIAPlanner.clearAssessment());await page.getByText('검사 결과를 연결해 주세요').waitFor();assert.deepEqual(errors,[]);fs.writeFileSync('qa/project-results.txt','PASS 8 profile/age flows; 2 new-task rounds for both demo profiles; incorrect budget blocked; B resume confirmation gate; A/B reset; fading; structured scores and event privacy; mobile width; production assessment-only injection and clearing. No browser errors.\n');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
